### ISSUE TITLE
Zopfli support?

### ISSUE THREAD

**Issue by xiaoxiachen** [archiverjs/node-archiver#101]
https://plus.google.com/+IlyaGrigorik/posts/1sxencNkbNS
Can we have Zopfli support?

**Comment by sindresorhus** [comment]
https://github.com/imaya/zopfli.js

**Comment by ctalkington** [comment]
hum, so i guess thats like precompiled then?

**Comment by ctalkington** [comment]
not familiar with emscripten and no movement here. if someone can come back with easily portable node library or some graceful way of handling bindings, ill put it up for consideration.
