### ISSUE TITLE
definition of an error

### ISSUE THREAD

**Issue by ctalkington** [archiverjs/node-archiver#106]
at this point, I am seeing that some may still expect an archive to be produced even if it can't add a file or such. this begs the question:
- what is an error to an archiving process?
- is a non-existent file considered an error when it could effect the overall integrity of the archive?

**Comment by chenshuiluke** [comment]
I personally would like the archiving process to continue if I can't add a single file due to it not existing or permission errors.

**Comment by ctalkington** [comment]
likely will end up adding error codes to the error objects in the near future to allow for people to easily ignore or only log such errors instead of fatal being thrown etc.

**Comment by chadbr** [comment]
what this ever done? I'd like to continue on error also...

basically I'd like to be able to continue when a file I'm trying to add is gzip'd without a known file extension, etc.

**Comment by DrYSG** [comment]
I might have 500K files, that I am adding. it might be that on is missing. For performance reasons, I would rather not do a fs.stat() to see if the file exists each time before adding. So this would be a "good" feature for me. (I just log the missing file, which is good for our scenario).

**Comment by ctalkington** [comment]
ok with v2.0.0 (hoping to release in next week), stat errors will now emit `warning`s as opposed to `error`s. the way pipes working was causing the destination streams to unpipe from archiver when it hit an `error`.

We can safely continue on from a stat error by just skipping that entry so no need to go scorched earth over it.
