### ISSUE TITLE
performance bottleneck with large number of files

### ISSUE THREAD

**Issue by ctalkington** [archiverjs/node-archiver#114]
this has been reported on #94 but i feel it deserves its own issue.

basically, when you get north of say 7000 entries in an archive, things start to really slow down to the point of even hanging and causing memory leaks.

**Comment by IonicaBizau** [comment]
:+1:

**Comment by ctalkington** [comment]
initial research points to a breakdown in the flow of data between the streams. this is most likely due to the amount of streams involved in the process.

dest <- archiver <- zipoutputstream <- zlib/checksum <- source file

**Comment by IonicaBizau** [comment]
Is there any example how to use the `directory` function?

**Comment by ctalkington** [comment]
it also might be interesting to see how things act when a stream just discards the info vs writing to fs stream.

@IonicaBizau `archive.directory('mydir');`

**Comment by IonicaBizau** [comment]
https://github.com/IonicaBizau/github-contributions/commit/4321dacce8a2c24c01d827c661c3a52e231faafa

I'm not sure this is the correct way. How can I specify the output directory?

**Comment by ctalkington** [comment]
@IonicaBizau doesn't work to well for those cases yet. its mainly for testing inspired by what @silverwind had to do for testing in #94

**Comment by silverwind** [comment]
@ctalkington I'm not sure if you're doing this yet, but it might be worth a try to use `graceful-fs`, if this problem is related to having too many files open.

**Comment by ctalkington** [comment]
@silverwind dont see that being the issue as its all streams ie in-memory and the actual fs.readStream ones are only ever opened 1 by 1.

@IonicaBizau 0.14.1 might make your case a little easier :) see README

**Comment by ctalkington** [comment]
i should also note that `directory` does NOT solve the actual bottleneck, just an improvement that came out of the testing.

**Comment by IonicaBizau** [comment]
@ctalkington [Upgraded to `0.14.2`](https://github.com/IonicaBizau/github-contributions/commit/f558e37965ab94f01c7f64629032330d6aaebc84). Using the directory call, the directory is archived fastly. Didn't test on a non-SSD, but I guess it should work as well.

How to set the out directory? When I `unzip` the zip file, it generates a `home/ionicabizau/Documents/github-contributions/lib/...` directory structure. How to avoid that?

**Comment by ctalkington** [comment]
@IonicaBizau so your saying this helper actually fixes the issue for your size repo? also see

https://github.com/ctalkington/node-archiver#directorydirpath-destpath-data

**Comment by IonicaBizau** [comment]
Yes, the issue is fixed! 

I released the latest version of `github-contributions`, where I used the `archiver` module. A retweet would help! :smile: 

https://twitter.com/IonicaBizau/status/560352971322834944

**Comment by ctalkington** [comment]
@IonicaBizau thanks for the feedback. not sure its fixed for all cases from my testing but good to hear nonetheless.
