### ISSUE TITLE
Will this work for my use case?

### ISSUE THREAD

**Issue by dovy** [archiverjs/node-archiver#117]
I'm curious if this library will work for my case or if I need to build my own.

I have a simple operation where I need to stream a file in via API-post, ship it to another URL which will then return a tar.gz. I then need to convert that file AS IS to a zip file, and return it to the post.

I am just seeing if this is possible with this framework or not. I'd love to just deploy to Heroku with this very simple API.

Please guide me? I appreciate the help and I'd be willing to even hire someone if they're interested.

**Comment by ctalkington** [comment]
im not 100% as I don't work with http in node much. id imagine as long as you have a source stream and archiver set to stream to some sort of http it should work but the actual code im not sure on at this point.
