### ISSUE TITLE
Express and error response

### ISSUE THREAD

**Issue by btmdave** [archiverjs/node-archiver#118]
When calling `archive.abort()`, this triggers the error event with `[Error: finalize: archive was aborted]` however, there doesn't seem to be anyway to send a response to the browser.  I've tried `res.send(500)` within the error event, but this doesn't seem to do anything.  The browser is still "waiting".

Any ideas?

**Comment by soyuka** [comment]
Follow the example here: https://github.com/ctalkington/node-archiver/blob/master/examples/express.js

I haven't tested abort but it should work just fine.

**Comment by btmdave** [comment]
Yeah, I have the same.  I'm testing in postman, maybe that's why... but should work the same.

**Comment by ctalkington** [comment]
please provide a gist or repo with the code your using.

**Comment by ctalkington** [comment]
imagine this specific error occurs because abort is called after finalize but files have queued up and when finalize finally gets run, it throws error.

**Comment by ctalkington** [comment]
some of the errors may get refactored in the future, some were removed in a previous release but there are some edges still.
