### ISSUE TITLE
Error 1 - extracting ZIP created on Windows

### ISSUE THREAD

**Issue by pavelbinar** [archiverjs/node-archiver#121]
Getting an error for extracting zip created on Windows machine. Works fine on Mac.

![screenshot 2015-02-10 22 27 32](https://cloud.githubusercontent.com/assets/1060032/6136775/e71aced8-b173-11e4-81c8-02466edd7796.png)

**Comment by ctalkington** [comment]
hum, i would need a sample repo of the code used and the resulting zip. not sure what would be different.

**Comment by ctalkington** [comment]
bump

**Comment by ctalkington** [comment]
this may be related to permissions issues that have been mentioned in a few newer issues but not 100% sure. going to close this for non-response but feel free to open a new issue with more detail.
