### ISSUE TITLE
io is blocking

### ISSUE THREAD

**Issue by mike-aungsan** [archiverjs/node-archiver#123]
When adding large folder to the zip, it is blocking the whole node process

archive.pipe(zip_output);
archive.directory(folder_path, archive_dir_name).finalize();

**Comment by ctalkington** [comment]
ill have to leave this for someone else to chime in on as i don't have any node projects using as part of a server application. i do know a lot of the sync code was remove where possible and that function uses a walker with async readdir so im open to being enlightened on what would cause blocking.

**Comment by ctalkington** [comment]
closing for lack of feedback

**Comment by soyuka** [comment]
FTR I'm using utf-8 without trouble
