### ISSUE TITLE
browser crashes sometime after zip.finalize(), not sending response correctly?

### ISSUE THREAD

**Issue by mixersoft** [archiverjs/node-archiver#125]
I've got this post on stackoverflow: 

http://stackoverflow.com/questions/29137729/strongloop-loopback-storage-service-how-to-use-storageservice-downloadstream

I'm trying to use archiverjs together with strongloop loopback-component-storage. I believe everything is working up until `zip.finalize()`. I don't seem to get the res.on 'close' event, and the Chrome browser crashes with an `Aw, Snap!`

**Comment by ctalkington** [comment]
im not too familiar with strongloop, but the way it works with express and such is that it streams the file before you even get to finalize.

i'm also thinking `res.attachment(container + '.zip');` has to come earlier.

a community member provided an express example here (assuming its http is anything like express)

https://github.com/archiverjs/node-archiver/blob/master/examples/express.js

**Comment by mixersoft** [comment]
I see this in their github repo, `LoopBack is an open source Node.js framework built on top of Express` and I tried to follow the example you gave. I moved res.attachment() before zip.pipe(res),  but same result.


		zip = Archiver('zip')
		zipFilename = container + '.zip'
		console.log 'attachment='+ zipFilename
		res.attachment( zipFilename )
		zip.pipe(res)


It crashes before the `res.on('close')` handler if triggered -- after `zip.finalize()`

**Comment by mixersoft** [comment]
These are the attr/methods for the reader, the object I pass to `zip.append()` - can you tell if that is the equivalent to `fs.createReadStream(files[i])`?

    reader = storageService.downloadStream(container, filename, function(stream) {
      return console.log('storageService.downloadStream() resp=', _.keys(stream));
    });
    zip.append(reader, {
      name: filename
    }); 
    // methods/attrs for reader = storageService.downloadStream()
    _appendFile, reader= [ '_readableState',
      'readable',
      'domain',
      '_events',
      '_maxListeners',
      'path',
      'fd',
      'flags',
      'mode',
      'start',
      'end',
      'autoClose',
      'pos' ]

**Comment by ctalkington** [comment]
can you please create a gist with the current code. this will allow for better reviewing and tracking of suggested changes.

**Comment by mixersoft** [comment]
I forked `loopback-component-storage` and added my code to the `example-2.0` folder. See my 3 commits ending here: https://github.com/mixersoft/loopback-component-storage/commits/master

but the gist is here: https://gist.github.com/mixersoft/7c3ad2aafb28c8ad5518

**Comment by mixersoft** [comment]
My mistake. I was trying to test via the strongloop API explorer. When I opened the URL directly,  I got the correct response.
