### ISSUE TITLE
stream from wkhtmltopdf not appending to zip archive

### ISSUE THREAD

**Issue by neouser99** [archiverjs/node-archiver#126]
For some reason, when appending a stream from stdout, the binary content is not properly placed into the archive. It creates an erroneous archive. Note, in this example, .on 'entry' is never called, nor are any of the .on 'error's ever called. Should I be doing something different? Is it possible there's an issue with 'lazystream' here?

node@0.10.26
archiver@0.14.3
async@0.9.0
wkhtmltopdf@0.1.5

```coffee-script
    archive = archiver 'zip'

    out = fs.createWriteStream 'emails.zip'
    out.on 'error', console.error.bind console
    out.on 'close', -> console.log 'output closed'

    archive.on 'error', console.error.bind console
    archive.on 'entry', (entry) -> console.log 'entry added...', entry
    archive.pipe out

    async.eachSeries ['email1.html', 'email2.html'], (name, cb) ->
      console.log 'pdfing and zipping', name

      html = fs.readFileSync name
      stream = wkhtmltopdf html.toString(), (err) ->
        console.log 'appending stream...', name, stream
        console.error err if err

        archive.append stream, name: "test/#{name}.pdf"
        cb null

      stream.on 'end', ->
        console.log 'stream ended...', name
    , ->
      console.log 'finalizing...'
      console.log archive.finalize()
```

```javascript
var archive, out;
archive = archiver('zip');
out = fs.createWriteStream('emails.zip');
out.on('error', console.error.bind(console));
out.on('close', function() {
  return console.log('output closed');
});
archive.on('error', console.error.bind(console));
archive.on('entry', function(entry) {
  return console.log('entry added...', entry);
});
archive.pipe(out);
return async.eachSeries(['email1.html', 'email2.html'], function(name, cb) {
  var html, stream;
  console.log('pdfing and zipping', name);
  html = fs.readFileSync(name);
  stream = wkhtmltopdf(html.toString(), function(err) {
	console.log('appending stream...', name, stream);
	if (err) {
	  console.error(err);
	}
	archive.append(stream, {
	  name: "test/" + name + ".pdf"
	});
	return cb(null);
  });
  return stream.on('end', function() {
	return console.log('stream ended...', name);
  });
}, function(err) {
  console.log('finalizing...');
  if (err) {
	console.error(err);
  }
  return console.log(archive.finalize());
});
```

**Comment by ctalkington** [comment]
any chance i could get a complied version of this. these short hands make it harder to follow for me.

**Comment by neouser99** [comment]
@ctalkington sure thing, I've added it to the original post, next to the coffee-script.

**Comment by ctalkington** [comment]
im thinking that the append needs to happen like this

```js
html = fs.readFileSync(name);
stream = wkhtmltopdf(html.toString());
stream.on('error', func) // iirc archiver should bubble up the error so this may be optional
archive.append(stream, {
  name: "test/" + name + ".pdf"
});
return cb(null);
```

**Comment by neouser99** [comment]
Hum... that doesn't seem to do the trick. Only one entry gets added the archive, and the output stream is never properly closed in the example below.

```javascript
var archive, out;
archive = archiver('zip');
out = fs.createWriteStream('emails.zip');
out.on('error', console.error.bind(console));
out.on('close', function() {
  return console.log('output closed');
});

archive.on('error', console.error.bind(console));
archive.on('entry', function(entry) {
  return console.log('entry added...', entry);
});
archive.pipe(out);

async.eachSeries(['email1.html', 'email2.html'], function(name, cb) {
  var html, stream;
  html = fs.readFileSync(name);
  stream = wkhtmltopdf(html.toString());
  archive.append(stream, {
	name: "test/" + name + ".pdf"
  });
  cb(null);
}, function(err) {
  archive.finalize();
});
```

It did force me to re-swizzle a little bit, and I do have an example that does work properly. The difference here is that we don't continue the async.eachSeries until wkhtmltopdf calls its callback, which is essentially called when the program ends. wkhtmltopdf uses spawn and stdout to do the heavy lifting. If you switch the **eachSeries** to **each**, it will fail sometimes, and sometimes it will actually work. This leads me to believe that the _stdout_ stream is the problem, or it has something to do with how _lazystream_ deals with _stdout_? I am little confused by this, and I'm not even sure how to continue gathering more information.

The below example will consistently print 2 entries added, and output closed:

```javascript
var archive, out;
archive = archiver('zip');
out = fs.createWriteStream('emails.zip');
out.on('close', function() {
  return console.log('output closed');
});

archive.on('entry', function(entry) {
  return console.log('entry added...', entry);
});
archive.pipe(out);

async.eachSeries(['email1.html', 'email2.html'], function(name, cb) {
  var html, stream;
  html = fs.readFileSync(name);
  stream = wkhtmltopdf(html.toString(), function() {
	cb(null);
  });
  archive.append(stream, {
	name: "test/" + name + ".pdf"
  });
}, function(err) {
  archive.finalize();
});
```

**Comment by ctalkington** [comment]
i havent personally worked with stdout streaming but lazystream only comes into play for `directory`, `file` and `bulk`.

have you tried an error listener on `stream` that callback isnt required looking at the module code.

https://github.com/devongovett/node-wkhtmltopdf/blob/master/index.js#L63

**Comment by neouser99** [comment]
That's the weirdest thing about this one. I've hooked into all of the error handling possible, and nothing. Everything just fails, and I can't quite figure out what is going on.

**Comment by ctalkington** [comment]
yah im not really sure but am fairly sure mixing the callback with the streaming is a bit unnecessary seeing as how once you pass the stream to archiver you dont have to care. archiver wraps the async process in a sync api.
