### ISSUE TITLE
Error with compressing and streaming multiple files simultaneously. 

### ISSUE THREAD

**Issue by dlinx** [archiverjs/node-archiver#127]
Cant zip and stream multiple files simultaneously, its just allowing only one file to stream.

**Comment by ctalkington** [comment]
please provide more detail and example of how your using.

**Comment by dlinx** [comment]
I created express application which compress directories and serves through response stream. When one user starts downloading a large directory, another user goes in queue, and after sometime, it returns error.

**Comment by ctalkington** [comment]
never got your response notification for some reason.

most likely its because your sharing a single instance of archiver.
