### ISSUE TITLE
the road to archiver v0.20

### ISSUE THREAD

**Issue by ctalkington** [archiverjs/node-archiver#129]
opening this issue as things are going to be changing in 0.15 for what i hope is the better.

now that we only support node 0.10+, we are free to use `vinyl` to pass data in streams via `through`.

im going to try to maintain as much of the existing functionality and api but essentially things will be simplifed in that streams which are inherently async will replace the queue system.

this moves us forward in providing a robust plugin platform as `gulp` has proven the data as stream with helpers to determine dir vs file and built in properties for stat/contents and such. all archiver formats will be plugins that use require to reduce the bulk of archiver core responsibilities and allow for use in a wider ecosystem at some point. vinyl also opens the door to support src/dest so that future releases can support say `src('archive.zip')` which is then internally extracted and appended as individual entries.

example of proposed api (inspired by imagemin):

```js
var archiver = require('archiver');
archiver() // ('zip', {options}) will call `use` internally for backcompat
  .use(archiver.zip({store: true}))
  .src('images/*.{gif,jpg,png,svg}') // will accept glob or array of globs
  .append() // will be kept for backcompat and for string/buffer use cases
  .bulk() // will most likely keep this for few releases until people start using things like `gulp-rename` etc
  .directory() // will be kept for backcompat
  .dest('build/images.zip')

finalize() // will most likely be removed as itll be handled at the plugin leve on data end etc.
abort() // will need some consideration if it still fits in a streams world
```

**Comment by ctalkington** [comment]
@sindresorhus would love some feedback as i know youve worked with gulp and a wealth of js that uses similar approaches.

**Comment by sindresorhus** [comment]
Not a big fan of chainable APIs like that, but the vinyl usage makes a lot of sense.

This looks very similar to mine and @kevva's [`imagemin` API](https://github.com/imagemin/imagemin#usage).

**Comment by kevva** [comment]
I think it looks kinda good. I'm using the same API in https://github.com/kevva/decompress.

**Comment by meteormatt** [comment]
Great to support node 0.12+ :clap:
