### ISSUE TITLE
Supported node versions

### ISSUE THREAD

**Issue by btmdave** [archiverjs/node-archiver#131]
Any idea if this is supported in v0.10.37 or what the highest v0.10.x version is supported?  It's working on v0.10.35, but seems on v0.10.37 that the zip's can't be open, (Error 2 - No Such file or directory).

When attempting to unzip with unzip (`unzip ~/Folder/file.zip -d ~/Folder`), it sees the file but has the error `bad CRC edcebfed  (should be afc275f9)`

**Comment by ctalkington** [comment]
there really should be a highest point release that it works up to. if its truly breaking on that version, there must be some change or maybe its related to dep updates. if you haven't might be best to wipe node_modules and install again to see if something was off.

**Comment by btmdave** [comment]
Thanks Chris, I'll close this issue, it's likely unrelated to the archiver itself
