### ISSUE TITLE
tar.gz archive created under Windows has invalid/corrupt file access rights under Linux

### ISSUE THREAD

**Issue by anvilvapre** [archiverjs/node-archiver#132]
I run into the following issue:

After creating a tar.gz file under Windows 8 and extracting it under Linux - without error messages - files - not directories - have the following incorrect ownership/permission flags:
<pre>
$ ls -l 
d????????? ? ? ? ?            ? .
d????????? ? ? ? ?            ? ..
-????????? ? ? ? ?            file1.txt
</pre>

A non root Linux user cannot remove the files. 

Using node archiver 0.14.3.

Using the code:
<pre>
	var archiver = require('archiver');
	var archive = archiver('tar', {
	  gzip: true,
	  gzipOptions: {
		level: 1
	  }
	});
	archive.on('error', function (err) { throw err; });
	archive.pipe(output);
	archive.directory(this.data_dir, this.basename_data_dir);
	archive.finalize();	

</pre>

**Comment by anvilvapre** [comment]
Using .zip gives similar results.

**Comment by ctalkington** [comment]
while i haven't tried such, i'm not aware as to why it would act like this and seems unrelated to compression as that doesn't do anything to permissions.

what version of node?

**Comment by ctalkington** [comment]
for this to effect both tar and zip tells me that its something with stating process. looking at the walker, it  would appear.

could you use `json` in place of `tar` or `zip` (ie `var archive = archiver('json', {`) and let me know the output

**Comment by anvilvapre** [comment]
The first entry looks like this. Others are similar, the mode, uid and gid etc. are the same everwhere.
<pre>
[{
	"name": "dev_2015520_090330/file_version.txt",
	"stats": {
		"dev": -895809459,
		"mode": 33206,
		"nlink": 1,
		"uid": 0,
		"gid": 0,
		"rdev": 0,
		"ino": 5910974510943355,
		"size": 3,
		"atime": "2015-05-20T07:03:30.741Z",
		"mtime": "2015-05-20T07:03:30.741Z",
		"ctime": "2015-05-20T07:03:33.455Z",
		"birthtime": "2015-05-20T07:03:30.741Z"
	},
	"sourcePath": "C:\\data\\dev_2015520_090330\\file_version.txt",
	"type": "file",
	"sourceType": "stream",
	"date": "2015-05-20T07:03:30.741Z",
	"mode": 438,
	"crc32": 2180199828,
	"size": 3
},
</pre>

**Comment by ctalkington** [comment]
`438 === 666` so it seems correct there as i believe node defaults for windows.

could you provide a sample zip/tar so i can review it?

**Comment by anvilvapre** [comment]
I think I found the cause. I had to strip my archive from some sensative information - so I ran some tests to see if the archive with less content also had the same issue.

The problem is caused by using - at least one - very long file name. I had file names - not path names -  that were 67 characters in length i.e. abc.... .txt. The content of the files is not relevant. 

Let me know if can reproduce the issue. If not I can send you an archive. Let me know how I can attach it or email it to you.

A fix would be appreciated. The long file names are auto generated in my case.

Thanks.

**Comment by ctalkington** [comment]
hum ok.

my profile has email you can send a sample to.

**Comment by ctalkington** [comment]
I'll try to put some longer filename tests together but looks like mode maybe incorrectly handled on windows according to another recently filed issue.

**Comment by anvilvapre** [comment]
I can send you my archive after tuesday. 

Date: Sat, 23 May 2015 21:23:23 -0700

**Comment by anvilvapre** [comment]
I sent you an archive Yesterday. Just in case it got lost as spam.

**Comment by ctalkington** [comment]
i haven't seen any email in email inbox or spam.

**Comment by anvilvapre** [comment]
I just resent it.

Date: Fri, 5 Jun 2015 11:37:29 -0700

**Comment by ctalkington** [comment]
do you still have issues after `0.15.1`? `mode` from stat should behave on windows now.

**Comment by anvilvapre** [comment]
i'm no longer able to test, i moved to calling 7zip and zip external executables.

**Comment by ctalkington** [comment]
closing as haven't been able to get feedback. feel free to open a new issue if the issue arises again.
