### ISSUE TITLE
archive.directory puts the result file in zipped file

### ISSUE THREAD

**Issue by FreeTymeKiyan** [archiverjs/node-archiver#135]
I want to zip the directory and put the zipped file in the same folder. 

The result file contains not only the original files, but the zipped file as well.

**Comment by ctalkington** [comment]
that is to be expected, in most use cases you going to have a secondary folder such as `dist` for such.

archiver itself has no knowledge of the destination path since its simple piping.

**Comment by ctalkington** [comment]
the next version will change to allow simple globs such as:

.src(['images/*.{gif,jpg,png,svg}', '!images/mydest.zip'])

i hope to have that in the next month
