### ISSUE TITLE
Can not work in `strict mode`.

### ISSUE THREAD

**Issue by JiangJie** [archiverjs/node-archiver#138]
When executing node with `--use_strict` option to force node-archiver run under strict mode, it caused such error.
```javascript
data.mode = isDir ? 0755 : 0644;
                               ^^^^
SyntaxError: Octal literals are not allowed in strict mode.
```
Could you please support strict mode?

**Comment by ctalkington** [comment]
can you provide details on what gained/required by strict mode. its not something I've used before.

**Comment by ctalkington** [comment]
0.15.0 will address this specific issue. let me know if theres any other changes that are sensible to make.

**Comment by britakin** [comment]
SyntaxError: Octal literals are not allowed in strict mode.

/node_modules/archiver/node_modules/zip-stream/node_modules/compress-commons/lib/compress-commons.js:10:20)

dosn't work, in version archiver 0.15.1

**Comment by ctalkington** [comment]
may i ask what the benefit to strict mode is? haven't seen it in use personally. these constants lose some readability by converting to decimal.
