### ISSUE TITLE
Small files are not added to zip (express+busboy+archiver)

### ISSUE THREAD

**Issue by zachrip** [archiverjs/node-archiver#141]
I am attempting to zip file uploads from busboy. If you're not familiar, busboy emits file events with readable streams, which I am feeding to archiver.append(). Larger files seem to work fine, but smaller ones that are only a few kilobytes don't seem to be getting added. Here is some of my code:

    var busboy = new Busboy({ headers: req.headers });
    var archive = archiver('zip');
	
    var transferStream = fs.createWriteStream(__dirname + '/uploads/' + req.transferIdentifier);
	
    archive.on('error', function(err) {
        console.log('ERROR');
    });

    archive.on('entry', function (entry) {
        console.log('ENTRY!');
    });
    
    archive.pipe(transferStream);

    busboy.on('file', function(fieldname, file, filename, encoding, mimetype) {
		file.on('data', function(data) {
			console.log('File [' + fieldname + '] got ' + data.length + ' bytes');
		});

		file.on('error', function (err) {
			console.log('error:', err);
		});

		file.on('end', function() {
			console.log('File [' + filename + '] Finished');
		});

		archive.append(file, {name: filename});
    });

    busboy.on('finish', function() {
    	archive.finalize();
	console.log('Done parsing form!');
    });

    req.pipe(busboy);

**Comment by zachrip** [comment]
I've done a bit of testing and it appears that removing the data event from the incoming file allows this script to work correctly.

**Comment by ctalkington** [comment]
i believe that listening to `data` will trigger data to start following in recent stream implementations.

**Comment by zachrip** [comment]
Is there any way I can listen to the data event? I'm using it for upload progress.

**Comment by ctalkington** [comment]
what version of node are you using?
