### ISSUE TITLE
Zip only the files/folders without creating a root directory?

### ISSUE THREAD

**Issue by ac360** [archiverjs/node-archiver#142]
Hi, 

First off, great library!  I've tried many zip libraries for node and this is by far the best.  

I'm creating zip files for AWS Lambda and Lambda can't read the files if they are put in a folder.

Is it possible to zip only the files and not include a root folder with node-archiver?

Thanks!

**Comment by ctalkington** [comment]
can you provide the current code your using to add files? just so have an idea of what to suggest.

**Comment by ac360** [comment]
Absolutely.  My goal is to append a file and a directory. 


        var file_system = require('fs');
        var archiver = require('archiver');

        var output = file_system.createWriteStream(__dirname + '/lambdas/' + folder + '/lambda.zip');
        var archive = archiver('zip');

        output.on('close', function() {
            console.log('done!');
        });

        archive.on('error', function(err) {
            throw err;
        });

        archive.pipe(output);
        archive.append(fs.createReadStream(__dirname + '/lambdas/' + folder + '/lambda.js'), {
            name: '../lambda.js'
        });
        archive.bulk([{
            expand: true,
            cwd: './lambdas/' + folder + '/node_modules',
            src: ['**'],
            dest: 'node_modules/'
        }]);
        archive.finalize();

**Comment by ctalkington** [comment]
one thing you might want to try is removing the `./` from your `cwd` i need to write a test as i always forget if it breaks it or not but not needed regardless.

```js
archive.append(fs.createReadStream(__dirname + '/lambdas/' + folder + '/lambda.js'), {
  name: 'lambda.js'
});

// can most likely be in recent versions of archiver
archive.file('/ambdas/' + folder + '/lambda.js', { name: 'lambda.js' });
```

**Comment by ctalkington** [comment]
also based on what i see your doing with bulk

you might try

```js
archive.directory('node_modules/');
``

**Comment by afram** [comment]
@ctalkington, this creates a 'node_modules' directory as root. Is there a way to place the contents of that directory at root without having a 'node_modules' directory at the root of the zip?

**Comment by soyuka** [comment]
@afram this might help : https://github.com/archiverjs/node-archiver/issues/156#issuecomment-135497173

**Comment by afram** [comment]
@soyuka that's not quite what I'm after. I am looking for this equivalent behaviour:

`zip -r ../dest.zip ./*` when run inside the directory I want to zip.

Unzipping the file should give me the contents of the directory I ran the zip command in above.

**Comment by afram** [comment]
actually sorry @soyuka my bad. That is what I'm after :-)

**Comment by afram** [comment]
I need to pass false or empty string as the name
