### ISSUE TITLE
Would be nice to have exclude files from folder by pattern

### ISSUE THREAD

**Issue by acierto** [archiverjs/node-archiver#145]
After reading a source code I found how to do it, but it is possible only by using bulk.

Maybe would be nice to document this scenario? Otherwise it looks like a limitation of the library

P.S.
and would be nice to have the same feature for directory method

**Comment by acierto** [comment]
After reading a source code I found how to do it, but it is possible only by using bulk.

Maybe would be nice to document this scenario? Otherwise it looks like a limitation of the library

**Comment by ctalkington** [comment]
ive been a bit busy with work and life but 0.15 or 0.16 will a new `src` method which will accept globs including negative ones. it will eventually replace `bulk` as that code doesn't work the best in async operations.

**Comment by yavorski** [comment]
Hi, any chance to know status of this? 
Thanks in advance.

**Comment by soyuka** [comment]
Why don't you implement the logic yourself?
Le mar. 24 nov. 2015 à 18:47, Yavor Ivanov <notifications@github.com> a
écrit :

**Comment by yavorski** [comment]
@soyuka yep, why not.
@ctalkington here is a pull request:
https://github.com/archiverjs/node-archiver/pull/167

**Comment by ctalkington** [comment]
0.18.0 should support this with glob options

**Comment by ctalkington** [comment]
released 0.19.0 to rename this to glob for forward compatibility with possible feature
