### ISSUE TITLE
Ignore some dot-files and folders

### ISSUE THREAD

**Issue by andeersg** [archiverjs/node-archiver#146]
Not sure if this is something that is impossible or if I'm doing it wrong.

But I try to zip a folder, and ignore .git and .gitignore. But if there are other dot-files i would let them be zipped.

My current code is like this:
```JS
archive.bulk([
  {
    cwd: filePath,
    src: ['**/*', '!.git', '!**/.git', '!.gitignore'],
    dot: true,
    expand: true,
    dest: fileName + '/test'
  }
]);
```
The gitignore-file is excluded, but not the .git-folder. Not sure how I can do this?

**Comment by ctalkington** [comment]
is the .git in root level or deeper?

you might try `!.git/**`
