### ISSUE TITLE
Tracking of archiving progress

### ISSUE THREAD

**Issue by acierto** [archiverjs/node-archiver#147]
Is it any way how it is possible to track the progress of archiving? 
Looking at documentation and skimming the code I can't find out how to do it.

In case of really missing this feature would be nice to have it, otherwise having quite large volumes to archive you are not aware what is going on

**Comment by soyuka** [comment]
```
archive.pointer()
```

https://github.com/archiverjs/node-archiver/blob/master/examples/express.js#L16

**Comment by ctalkington** [comment]
`pointer` and the `entry` event can help with logging. making a progress bar or such would be much harder since streams are variable. if you know the file count you could do the math on each entry event to get percent of files complete etc.

https://github.com/archiverjs/node-archiver#entry

**Comment by acierto** [comment]
Oh cool! I missed this part in the docs.. Thanks guys!

**Comment by anthlasserre** [comment]
You can do like this if you want:
```
archive.on("progress", (progress) => {
    console.log("TOTAL", progress.entries.total, "PROCESSED", progress.entries.processed)
})
```

**Comment by ArkinSolomon** [comment]
This no longer works, processed and total are the same, on MacOS anyway

`TOTAL 2808 PROCESSED 2808`

**Comment by ArkinSolomon** [comment]
Looks like this is mentioned in #475
