### ISSUE TITLE
How to detect an archive process is finished 

### ISSUE THREAD

**Issue by haledeng** [archiverjs/node-archiver#150]
Does node-archiver provide any event to detect the archive process is finished.

I need to tar some files in zip and download to the client. So I need to know when the archive process is finish and so generate a download link to client.

**Comment by haledeng** [comment]
I have found a solution. Add an event listener to the output stream
```
var output = fs.createWriteStream(zipPath);
// some archiver code
output.on('close', function(){
// whole archive process is finished
})
```

**Comment by ctalkington** [comment]
archiver doesn't know when the archive is actually fully finished streaming so listening to your output is usually best for this.
