### ISSUE TITLE
why I can‘t use it with chinese file name

### ISSUE THREAD

**Issue by kooksee** [archiverjs/node-archiver#151]
How can I use it with chinese path?

**Comment by ctalkington** [comment]
are there any errors? have a before/after text example, charset, and where this doesn't work?

zip doesn't really define a charset so mostly text is just forced to UTF-8 currently.

https://github.com/archiverjs/node-compress-commons/blob/master/lib/archivers/zip/zip-archive-entry.js#L171

**Comment by ctalkington** [comment]
closing for lack of feedback
