### ISSUE TITLE
How to set compression rate?

### ISSUE THREAD

**Issue by jabrena** [archiverjs/node-archiver#153]
Hi, 

I am using this library to stress an upload process, uploading zips with different weight.
How to set the compression rate?

Many thanks in advance

Juan Antonio

**Comment by ctalkington** [comment]
`options: { zlib: { level: 6 } }`

https://github.com/archiverjs/node-archiver#zlib-object

https://nodejs.org/api/zlib.html#zlib_options

**Comment by jabrena** [comment]
Tested.

**Comment by gaeldupont44** [comment]
Hi,
I don't want to compress zip archives, but I did not succeed to do it.
I've tried: 
var archive = archiver('zip', { zlib: { level: 0 } } );
var archive = archiver('zip', { options: { zlib: { level: 0 } } } );
I didn't found any help anywhere.. please could you help me ?

thanks in advance.

**Comment by seajean** [comment]
I have the same problem, not works

**Comment by ctalkington** [comment]
level: 0 is treated the same as STORE (ie no compression) as it doesnt make much sense to fire up zlib for such when it would be faster to use "store" the raw data.
