### ISSUE TITLE
Provide Changelog

### ISSUE THREAD

**Issue by landau** [archiverjs/node-archiver#155]
It is difficult to tell what changes occurr through version by looking through commits. 

Thanks!

**Comment by soyuka** [comment]
Take a look at: https://github.com/archiverjs/node-archiver/releases 

I did not see breaking changes in the last releases, but +1 for the changelog anyway.

**Comment by ctalkington** [comment]
mainly use releases feature these days but will see about coming up with a workflow that produces changelog.
