### ISSUE TITLE
How to set destination directory for zip when appending streams?

### ISSUE THREAD

**Issue by integrity-dev** [archiverjs/node-archiver#156]
Is there a way to set a destination directory at creation for zips when appending streams or an option I'm missing for append? I see options when using bulk or directory but not append.

**Comment by soyuka** [comment]
What are you meaning by "appending streams"?

You're piping archive to streams, so destination should already be set.

**Comment by integrity-dev** [comment]
The use case is I have an AWS Lambda function which is taking objects from S3, creating a zip, then putting the zip to another bucket in S3. So the inputs are streams from S3 and the output is then streamed to S3, as well. So the entire operation is piping streams to Archiver through append, then piping to S3. 

The zip Archiver creates creates a directory structure when unzipped which correlates to the S3 key.  

Example key: "example-key/folder/object.jpg" produces a folder structure when unzipped which mirrors the key structure.

This behavior is fantastic except the zip filename, which I set, needs to be dynamic. And the user expects a zip with xxx.zip filename to unzip to directory xxx. So what I'm looking to do is set a destination directory on the zip which matches the filename being set.

This seems possible when working with files being pulled from disc using the bulk or directory methods, but is not shown as an option with append based on the docs. 

Does that make sense?

**Comment by soyuka** [comment]
Assuming:

```
zip /home/user/example-key/folder/object.jpg to name.zip
# unzip result :
example-key/folder/object.jpg
```

You'll need to set the directory path in the name argument, for example using `directory(dirpath[, destpath, data])`:

```
archive.directory('/home/user/example-key/folder', '/example-key/folder');
```

The same goes for `archive.file`. With `append` modify the name property.

Am I correct?

**Comment by integrity-dev** [comment]
Thank you. Seems so obvious now. Prepending the name with the desired destination folder path worked perfectly.
