### ISSUE TITLE
Rename file instead of overwrite when file with same name exists

### ISSUE THREAD

**Issue by tgijbels** [archiverjs/node-archiver#157]
Is their an option to rename a file when adding it to an archive if their already exists a file with this name in the archive or do we need to write this logic ourselves?

For example: rename a file called 'foo.txt' to 'foo(1).txt' if their already exists a file called 'foo.txt' in the archive. 

The code snippet below overwrites the file if it already exists.  
```javascript
var zip = archiver('zip');
zip.pipe(this.response);

_.each(files, function(file){
      var readStream = file.createReadStream('files');
      zip.append(readStream, {
        name: file.name
      });
});
```

**Comment by soyuka** [comment]
No, there is not. You should implement the logic yourself.

**Comment by tgijbels** [comment]
Thought so. Thanks anyway!
