### ISSUE TITLE
symbolic links are not stored when zipping files

### ISSUE THREAD

**Issue by xileffelix** [archiverjs/node-archiver#158]
I am not sure if this is an issue or a feature.
When i try to zip a folder that containts files and symlinks only the files are stored and the symlinks are ignored.

For example:
libXdamage.so -> libXdamage.so.1.1.0
libXdamage.so.1 -> libXdamage.so.1.1.0
libXdamage.so.1.1.0

results in a zip file only containing "libXdamage.so.1.1.0".

zip for linux for example has a command line switch "-y" which takes care of this problem
"-y   store symbolic links as the link instead of the referenced file"

Would be nice to see something like this in node-archiver or did I miss something?

Kind Regards

**Comment by ctalkington** [comment]
this is expected behavior. symlinks are currently not preserved. not sure what itd really take to support such

**Comment by ctalkington** [comment]
this is something i hope to support in a future release. its going to be a matter of archiver and its underlying libraries supporting this and the calling code to properly detect symlinks.

thus its going to take a bit of time to get all the aspects handled.

**Comment by plrthink** [comment]
Any updates on this?

**Comment by lukas-gitl** [comment]
Also looking for this... Thanks!

**Comment by rthideaway** [comment]
+1 for this, need to package some symlinks as well

**Comment by laurenzlong** [comment]
Is there a manual workaround for resolving the symlinks before zipping?

**Comment by laurenzlong** [comment]
Figured it out: first find the real path using fs.realPath: https://nodejs.org/api/fs.html#fs_fs_realpath_path_options_callback, and then copy the linked file to the symlink.

**Comment by ctalkington** [comment]
I'm going to try and work this out early in 2017 with any free time that I have. I do see it had some value and it's been more a lack of time to explore options.

**Comment by brucewar** [comment]
support "tar" ?

**Comment by MurzNN** [comment]
for support symlinks - we must use additional key:
```
zip --symlinks -r foo.zip foo/
```

**Comment by DragonRaider5** [comment]
Hey @ctalkington ,

please excuse the stupid question, but I can't seem to find it in the documentation... How do I set my archive to replace symlinks with copys? AWS Lambda sadly doesn't seem to be able to resolve symlinks 😞

**Comment by AngeloGulina** [comment]
Hello there 😄 

Is the `symlinks` option provided or someone working on it?
Just asking 'cause not/having it is affecting some the behaviour of some other libs.

If any help needed, I can try to provide.

Thanks!

**Comment by faizy-ahmed** [comment]
Old Command: `zip -r ../myfile.zip *`
New Command: `zip -yr ../myfile.zip *`

Old command was handling symbolic links (shortcuts) as regular files, hence the framework was corrupted. New Command resolved my issue. The command was deployed on CD pipeline on Azure DevOps.
