### ISSUE TITLE
Corrupt zip files

### ISSUE THREAD

**Issue by jamessharp** [archiverjs/node-archiver#161]
I'm having issues identical to those in #32 (using archiver 0.15.1). Generating zips in production (I can't repro on a dev machine) _sometimes_ get corrupted. As mentioned in #32 the file sizes are always exactly the same and the corruption is inconsistent (different files get corrupted on different attempts).

I've tried disabling compression entirely (setting the `store` option to true) but still get CRC errors.

Any help would be greatly appreciated

Thanks!

**Comment by jamessharp** [comment]
Ah I should probably add that the source is a stream here

**Comment by jamessharp** [comment]
From doing some more digging the only thing I can think of is that makes any sense is that the buffers are being overwritten somewhere

**Comment by ctalkington** [comment]
i haven't had a chance to try things out with iojs but the basic tests seem to function on Travis.

Can you provide code used for generation?

**Comment by jamessharp** [comment]
Sure - I'm piping things through from amazon S3

```javascript
  var archive = archiver('zip', {
    store: true
  });

  files.forEach(function(file) {
    if (file.s3Key) {
      var params = {
        Bucket: storageBucket,
        Key: file.s3Key
      };

      // Lazy requesting - only request when something is listening
      var fStream = new streams.PassThrough();
      var sent = false;
      fStream.on('newListener', function(event) {
        if (!sent && event === 'data') {
          var req = s3Client.getObject(params);
          var rStream = req.createReadStream();
          rStream.pipe(fStream);
          rStream.on('error', err => fStream.emit('error', err));
          sent = true;
        }
      });

      archive.append(fStream, {name: file.name, date: file.date});
    } 
  });
  
  archive.finalize();

  archive.pipe(response);
```

From looking through the code of your libraries it would seem that the buffered data from the S3 should be passed through to the response unchanged (just with some zip CRCs and file entries and whatnot inserted). The fact that when unzipping, some CRCs fail and some files are corrupted, but the archive and each individual file are all of the correct length suggests to me that some buffers are being overwritten before being sent out in the response but after all the CRC calculations are performed.

**Comment by ctalkington** [comment]
really should be piping to output before finalize is called. usually want to do that upfront.

**Comment by jamessharp** [comment]
Yeh I tried that as well, but still had the same issues

**Comment by jamessharp** [comment]
I actually tried just doing a simple `zip-stream` only implementation, but that was still corrupt

**Comment by ctalkington** [comment]
have you tried listening on archive `error` to make sure theres not something else at play here?

**Comment by jamessharp** [comment]
Yup - nothing :(

**Comment by ctalkington** [comment]
also are you setting a proper content-type/disposition. i know other users have used this with s3 in the past. have you tried removed the lazy loading? could be something in that tripping things up.

**Comment by jamessharp** [comment]
Yep and yep - I've also tried listening to the s3 request `httpData` events directly rather than piping it through.

**Comment by ctalkington** [comment]
are you on mac? it could be somewhat related to:

archiverjs/node-zip-stream#4

**Comment by jamessharp** [comment]
It could be the same issue, but the mac thing may be a red herring. The node instances I'm using are all on linux (official node docker containers) and downloading on both windows and mac we get corruption. Also with `store: true` set the zip files appear to extract fine on macs, but are in fact corrupted when you look with `unzip -t` - it may be what @cantidio has been seeing. I've also noticed that it seems to occur more on large zips. Smaller archives tend to escape without corruption (but not all the time)

**Comment by ctalkington** [comment]
is the error spread between files or do all of them fail crc?

**Comment by jamessharp** [comment]
It's rather sporadic. Not all of them fail, sometimes none of them fail, but it's never consistent e.g. here's some output from `unzip -t` on two zips downloaded one after the other:

```
    testing: Enbid-2.0.b/Documentation/users-guide.pdf   OK
    testing: Enbid-2.0.b/Documentation/users-guide.tex   OK
    testing: Enbid-2.0.b/Examples/hernquist1_small/snapshot_ici_typelist   OK
    testing: Enbid-2.0.b/Examples/hernquist1_small/snapshot_ici   bad CRC 853430b1  (should be bb4a695f)
    testing: Enbid-2.0.b/Examples/uniform_6d_box_4/snapshot_ici   bad CRC a3119760  (should be 37d73cc6)
    testing: Enbid-2.0.b/Examples/uniform_6d_box_4/snapshot_ici_3d.ascii   bad CRC 7fa2a3c0  (should be 279f9ddd)
    testing: Enbid-2.0.b/Examples/uniform_6d_box_4/snapshot_ici_6d.ascii   bad CRC fae47908  (should be eea9ebf2)
    testing: Enbid-2.0.b/src/IMG_0001.JPG   OK
```

```
    testing: Enbid-2.0.b/Documentation/users-guide.pdf   OK
    testing: Enbid-2.0.b/Documentation/users-guide.tex   OK
    testing: Enbid-2.0.b/Examples/hernquist1_small/snapshot_ici_typelist   OK
    testing: Enbid-2.0.b/Examples/hernquist1_small/snapshot_ici   bad CRC 853430b1  (should be bb4a695f)
    testing: Enbid-2.0.b/Examples/uniform_6d_box_4/snapshot_ici   OK
    testing: Enbid-2.0.b/Examples/uniform_6d_box_4/snapshot_ici_3d.ascii   bad CRC 7fa2a3c0  (should be 279f9ddd)
    testing: Enbid-2.0.b/Examples/uniform_6d_box_4/snapshot_ici_6d.ascii   bad CRC fae47908  (should be eea9ebf2)
```

**Comment by jamessharp** [comment]
And it only appears to be under load that it happens - it's very reproducible in production, but not at all reproducible in development (using exactly the same docker image)

**Comment by ctalkington** [comment]
this would likely be happening in main zip format builder somewhere:

https://github.com/archiverjs/node-compress-commons/blob/master/lib/archivers/zip/zip-archive-output-stream.js#L156

https://github.com/archiverjs/node-crc32-stream/blob/master/lib/deflate-crc32-stream.js

are the file size length different than they should be? maybe try listening for `entry` and logging out size of each as they are added to archive, should be able to see the crc32 too at the point.

**Comment by ctalkington** [comment]
all the crc32 happens on `write` so events being called out of order shouldn't impact things and it should work even if passed to `end(buffer)`

**Comment by ctalkington** [comment]
one thought i have is maybe node/v8 is doing some kind of optimization that is causing the checksum var to not get updated reliably under load.

this used to be noticeable more on `deflate` only, but maybe because deflate increased load.

**Comment by jamessharp** [comment]
Actually the checksums and file sizes are correct (even in corrupted archives) - it's the data that is corrupted (but still the right length). I think you're right about node/v8 doing something here, possibly reusing memory sooner than it should.

**Comment by jamessharp** [comment]
I've also tried increasing the memory available to the process (no joy) and copying the buffer when it comes from s3 before it enters archive. Again no joy :(

**Comment by jamessharp** [comment]
So a bit more of an update - I tried also piping to disk as well as to the request. The file on the disk was uncorrupted. The file that arrived from the network _was_ corrupted. I wonder if this is some express middleware getting in the way. It doesn't seem like it's a problem directly with this library though

**Comment by jamessharp** [comment]
I've finally sorted this and it wasn't, in fact, a problem with node/express/archiver at all. For those that are interested or maybe hitting similar problems I am using nginx as a reverse proxy/loadbalancer in front of my node instances. It turns out that by default nginx buffers the responses from the origin server before sending them onto the client. It looks like this was causing problems when proxying large responses. Disabling this feature by setting `proxy_buffering off;` seems to have fixed the problem.

Thanks for your help with this!

**Comment by ctalkington** [comment]
@jamessharp interesting. i thought it was weird how random the issue seemed. not sure if other issues related to similar used a proxy or what. thanks for the research!

**Comment by pure-react-carousel-hang** [comment]
@ctalkington https://stackdev.space/questions/submit-compressed-files-to-the-platform-for-users-to-access-and-download
