### ISSUE TITLE
0-byte zip file produced; no errors reported

### ISSUE THREAD

**Issue by emptyset** [archiverjs/node-archiver#164]
I'm attempting to use archiver to zip the entire contents of a node.js application; doing this by creating a grunt task `archive`.  Here's the contents of `GruntFile.js` and calling the following function:

```javascript
// ...
module.exports = function(grunt) {
// ...
    grunt.registerTask('archive', archive);
};

var archive = function() {
    var fs = require('fs');
    var archiver = require('archiver');

    var target = __dirname + '/application.zip';
    var output = fs.createWriteStream(target);
    var zip = archiver('zip', {});

    output.on('close', function() {
        console.log("output.onClose");
    });

    output.on('pipe', function() {
        console.log("output.onPipe");
    });

    output.on('finish', function() {
        console.log("output.onFinish");
    });

    output.on('error', function(err) {
        console.log("output.onError");
        throw err;
    });

    var workingDirectory = __dirname + '/';

    console.log('target = ', target);
    console.log('workingDirectory = ', workingDirectory);

    zip.on('error', function(err) {
        console.log(err);
        throw err;
    });

    zip.pipe(output);
    zip
        .append(fs.createReadStream(workingDirectory + 'somefile.txt'), { name: 'somefile.txt' })
        .finalize(function(err) {
            console.log(err);
            throw err;
        });
}
```

Produces the following output:
```
$ grunt archive
output.onPipe

Done, without errors.
```

And there's an `application.zip` in the directory, but it is 0-bytes.

**Comment by ctalkington** [comment]
you may want to use `__dirname` with the somefile.txt might be missing depending on where running from. though that should result in an error. otherwise im not immediately seeing an issue.

**Comment by emptyset** [comment]
Oops!  Good catch.  I did remove my console.log() statements from this code; but I went ahead and checked the path again and I'm passing in the correct path now (corrected code above).  

It still produces a 0-byte file (obviously, somefile.txt is not 0-bytes...).  In my code I also try:

```javascript
zip.directory(workingDirectory + 'someDirectory')
```

But this doesn't work (again, someDirectory is not empty either.)

Shouldn't it fire output's 'close' and 'finish' events when zip.finalize() is called?  I'm trying to understand why I don't see that output.

**Comment by ctalkington** [comment]
thinking on it you issue here is most likely that you don't have task setup for async:

```
// at beginning
var done = this.async();

// and this after close
done();
```

**Comment by romain10009** [comment]
Hello, I run in the same issue, here is my code : 

        var archive = archiver('zip');
        archive.on('error', function(err) {
            console.error(err);
            res.status(500).send({error: err.message});
        });

        //on stream closed we can end the request
        res.on('close', function() {
            console.log('Archive wrote %d bytes', archive.pointer());
            return res.status(200).send('OK').end();
        });

        res.attachment('myzip.zip');

        //this is the streaming magic
        archive.pipe(res);

        archive.append('hello zip1',{name : 'text1.txt'});
        archive.append('hellooooo zip2',{ name : 'test2.txt'});

        setTimeout(function(){
                archive.finalize(function(err, bytes) {
                    if (err) {
                        throw err;
                    }
                    console.log(bytes + ' total bytes');
                });
            },3000
        );

here is what i get as a file : 
![image](https://cloud.githubusercontent.com/assets/7512202/11440750/324216b8-9540-11e5-918e-d73c9cfe0ae2.png)

the example i'm inspired by is this one : 
http://stackoverflow.com/questions/20107303/dynamically-create-and-stream-zip-to-client/25210806#25210806

**Comment by boknoypatotoy** [comment]
My problem is ... I'm able to create a zip file but the contents are all 0 size bytes ... I've been researching to this problem for 2 days but I haven't found anything helpful .... then ... after a few hours of break ... after eating my favorite meal ... I thought to do this ...

`        return archive
            .glob("**/*", {
                cwd: tempFilesPath,
                ignore: ["export.zip"],
            })
            .finalize();
`
and ... SUCCESS ... I have a fully working zipped file ...

finalize() is a promise ... it should be clearly explain in the documentation ...
