### ISSUE TITLE
Zip password

### ISSUE THREAD

**Issue by jeprojects** [archiverjs/node-archiver#168]
Can this create a zip with a password?

I couldn't find it anywhere in the docs.

**Comment by ctalkington** [comment]
passwords are not currently supported.

**Comment by manishcalling** [comment]
Any update on the password protection?

**Comment by oaleynik** [comment]
@ctalkington can you please give us a hint - is it something in plans to add soon? Thanks!

**Comment by ctalkington** [comment]
sorry it's something that would be nice to support but involves a devotion of time to implement. I've been busy with paid work so archiver has mostly received bug fixes this year but I do intend to continue doing several small releases a year as features or bugs can addressed.

**Comment by payitforwardnow** [comment]
I'll see if I can take care of this in a new project.

**Comment by BiiSmiiLLAH** [comment]
Hey community, some news ?

**Comment by forivall** [comment]
This plugin exists now: https://github.com/artem-karpenko/archiver-zip-encrypted

**Comment by ctalkington** [comment]
oh that's cool. I'd be open to integrating something like that into zip-stream and carry the options into archiver. now to find time to experiment.

**Comment by BiiSmiiLLAH** [comment]
as @forivall  Said, IT works and it's a great tool.
