### ISSUE TITLE
Streaming to res not working, getting empty errored file

### ISSUE THREAD

**Issue by romain10009** [archiverjs/node-archiver#170]
Hello, I run in quite the same issue (when streaming to file it works, when streaming to http client it gives corrupt files.), #161 seems to have same issues, but i'm runing on local with nodejs and nodemon, on windows. version of node is 4.2.1, archiver 0.17.0 here is my code. the res 'end' event is not raised. Nor is the res 'data' event.

        var archive = archiver('zip');
        archive.on('error', function(err) {
            console.error(err);
            res.status(500).send({error: err.message});
        });

        //on stream closed we can end the request
        res.on('close', function() {
            console.log('Archive wrote %d bytes', archive.pointer());
            return res.status(200).send('OK').end();
        });

        res.attachment('myzip.zip');

        //this is the streaming magic
        archive.pipe(res);

        archive.append('hello zip1',{name : 'text1.txt'});
        archive.append('hellooooo zip2',{ name : 'test2.txt'});

                archive.finalize(function(err, bytes) {
                    if (err) {
                        throw err;
                    }
                    console.log(bytes + ' total bytes');
                });
        );

here is what i get as a file : 
![image](https://cloud.githubusercontent.com/assets/7512202/11440750/324216b8-9540-11e5-918e-d73c9cfe0ae2.png)

the example i'm inspired by is this one : 
http://stackoverflow.com/questions/20107303/dynamically-create-and-stream-zip-to-client/25210806#25210806

**Comment by ctalkington** [comment]
guessing your using express here? as it looks similar to the community provided example. finalize no longer supports a callback however.

is there a proxy in your setup as it does sound similar to #161. I don't personally do web servers in nodejs so I have limited guidance in that department.

**Comment by chenshuiluke** [comment]
@ctalkington I apologize in advance since I only picked up node earlier this week, but how will I know that finalize has finished executing without the use of a callback?

**Comment by soyuka** [comment]
By using `on('end')` event. See [this example](
https://github.com/archiverjs/node-archiver/blob/master/examples/express.js)
with expressjs.
Le dim. 29 nov. 2015 à 00:35, Sky Lightna <notifications@github.com> a
écrit :

**Comment by chenshuiluke** [comment]
@soyuka It seems blaringly obvious to me right now, thanks :+1:

**Comment by ElsewhereGames** [comment]
I use something very similar to the example, but the on('close') event is never called?

**Comment by soyuka** [comment]
I'm using on('end') event

Le jeu. 3 déc. 2015 à 20:51, ElsewhereGames <notifications@github.com> a
écrit :

**Comment by ElsewhereGames** [comment]
Also not called. The only one I get is 'finish', but it is too late to set headers at that point. This results in a zip that downloads fine in Chrome, but is corrupt in IE or Firefox (the size of the zip is too big even!).

**Comment by ctalkington** [comment]
i have had reports of issues with proxy_buffering in proxy servers such as nginx. otherwise I would need an exact code sample to review.

**Comment by soyuka** [comment]
@ElsewhereGames Can you post the code?

I see that in my example I'm waiting for the piped stream to close, on the other hand I'm using `.on('end')` on the `archive` object in another project.

**Comment by ElsewhereGames** [comment]
```
function(name, paths, output) {

  output.attachment(name);
  output.setHeader('Content-Type', 'application/zip');
  
  // This streams the files to the output, so no local zip is generated.
  var archive = archiver('zip');
  archive.pipe(output);

  archive.on('error', function(error) {
    logger.warn('Unable to archive ' + paths);
  });

  output.on('close', function() {   
    return output.status(200).send('OK').end();
  });

  paths.forEach(function(path) {
    var stats = fs.lstatSync(path.source);
    if (stats.isDirectory()) {
      archive.directory(
        path.source,
        path.destination
      );
    } else {
      archive.file(
        path.source, { 
          name: path.destination
        }
      );
    }
  });
  
  logger.info('Diagnostics exported.');
  archive.finalize();
};
```

Where `name` is the name of the zip file, `paths` is an array of source and destination paths, and `output` is the express `res` object.

**Comment by ctalkington** [comment]
i think the example sets the attachment after the pipe has started. have you tried this? I think what you have is correct just needs a little re-ordering.

@soyuka may have further knowledge though.

**Comment by ctalkington** [comment]
also, you may be able to avoid that sync stat check, as technically, `file` uses `_append` which does the stat async via a queue which then does a `isFile/isDirectory` test and does same thing as calling `directory`

**Comment by ElsewhereGames** [comment]
Tried to reorder the calls, same result. I also tried Windows 10, and downloading the zip works for both MSEdge and IE11 (although, again, the 'close' event is not triggered).

**Comment by soyuka** [comment]
I'm assuming you're using expressjs? `output` is in fact the `response` object?

@ElsewhereGames I'm trying to fix it give me 10 min ;)

**Comment by ElsewhereGames** [comment]
Correct, `output` is the response object. And whoa, thanks for the quick responses everyone!

**Comment by soyuka** [comment]
```
function(name, paths, output) {

  //just make sure that nothing sent headers already, you'll end the request here

  //if name extension is zip, attachment will set the content-type header
  output.attachment(name + '.zip');

  // This streams the files to the output, so no local zip is generated.
  var archive = archiver('zip');

  //better register events before piping
  archive.on('error', function(error) {
    archive.abort(); //not always useful but might save trouble
    logger.warn('Unable to archive ' + paths);
    return output.status(500).send('Error while zipping') //you might want to end the request here
  });

  archive.on('end', function() {
    //no need to send a response, if the archive is piped to the response, it'll end it when the stream closes
    console.log('Archive finished')
  })

  archive.pipe(output);

  //you might want to stat with async.each or Promises instead of keeping this sync
  paths.forEach(function(path) {
    var stats = fs.lstatSync(path.source);
    if (stats.isDirectory()) {
      archive.directory(
        path.source,
        path.destination
      );
    } else {
      archive.file(
        path.source, { 
          name: path.destination
        }
      );
    }
  });

  logger.info('Diagnostics exported.');
  //if previous call is async, do this on the global callback, if you try to add files and archive is finalized it'll most likely give an error
  archive.finalize();
};
```

I have not tested this, but it works the same way [here](https://github.com/soyuka/explorer/blob/master/plugins/archive/job.js). What I changed is that I don't send `status(200)`. When `archive` stream gets closed it'll also end the response. On the other hand, you should end the request when catching an `error` event.

I could make an example to stat async, but I'm sure you could manage it. Try [bluebird#Promise.all](http://bluebirdjs.com/docs/api/promise.all.html) to keep it simple and clean :).

**Comment by ElsewhereGames** [comment]
Hmm, the change did not help my particular case. Looking at the headers, it seems somewhere along the line Express is setting the wrong content length (543 bytes, should actually be 335). I will fall back to writing the zip to disc before streaming, that should work for now.

**Comment by soyuka** [comment]
I fixed the example, and it works on my osx. Could you try to run [this express example](https://github.com/soyuka/node-archiver/tree/fix-example/examples)?

**Comment by ElsewhereGames** [comment]
I don't think node-archiver is the issue. I put together a test which just writes a JPEG to the response stream, and I see the same failures with that (file comes out too big in some browsers). Thanks for helping me figure this out though!

**Comment by ElsewhereGames** [comment]
Ha, this explains the problem: https://github.com/intesso/connect-livereload/issues/39

**Comment by romain10009** [comment]
I use livereload indeed. I will give it a try and let you know. It is very difficult to link this behaviour to livereload. I'm really amazed a bug like that can exist in livereload!

**Comment by wi-ski** [comment]
what exactly was the conclusion here? we just have to write to disk?

**Comment by thxmxx** [comment]
This is the fix:
app.use(require('connect-livereload')({ ignore: ['download'] }));
