### ISSUE TITLE
zip not expanding

### ISSUE THREAD

**Issue by Yedidya** [archiverjs/node-archiver#172]
Im having an issue getting the zipped folder or expand. When I try to expand it, it just makes a duplicate .zip file. I have it set up as basic as I could possibly do, from my understanding. 

```
 var zipPath = configuration.readSettings('screenshotDirectory') + fileNameURL + "_" + dateTime;

 var output = fs.createWriteStream( zipPath + '.zip');
    var archive = archiver('zip');

 output.on('close', function() { console.log('done') });
 archive.on('error', function(err) { throw err });

 archive.pipe(output);

 archive.bulk([
   { expand: true, cwd: zipPath, src: ['**/*'], dest: 'screenshots' }
 ]).finalize();
```

What should I be doing to make the file expand properly?

**Comment by soyuka** [comment]
What are you trying to do?

Do you want to zip the content of a directory?

**Comment by Yedidya** [comment]
Yes, I'd like the contents of the zip

**Comment by soyuka** [comment]
Just use [`archive.directory`](https://github.com/archiverjs/node-archiver#directorydirpath-destpath-data) then:
```
archive.directory('myDir', 'screenshots');
```

**Comment by Yedidya** [comment]
`archive.directory('myDir', 'screenshots');` instead of the current `archive.bulk` that I'm using?

**Comment by ctalkington** [comment]
`archive.directory(zipPath, 'screenshots');` should be interchangeable with your example of `bulk`.

assuming that zipPath is a directory

**Comment by izhekov** [comment]
Indeed the adm-zip library have a bug not properly creating the archives. Replacing the library with archiver seems as a good soluition.

**Comment by ctalkington** [comment]
re-reading this it sounds like you want to *extract* a zip file. this is not supported by this module.

**Comment by Yedidya** [comment]
The error is "Unable to expand 'name-of-archive.zip'" into "Desktop".

Myabe the term for what I am trying to do is unarchive or unzip?

**Comment by inca** [comment]
Having the same here:

```
const arch = archiver.create('zip', {});
const out = fs.createWriteStream('extension.zip');
console.log('Creating extension.zip');

arch.on('end', function() {
    console.log('Created extension.zip');
    process.exit(0);
});

arch.on('error', function(err) {
    console.error(err);
    process.exit(1);
});

arch.pipe(out);
arch.directory('extension', 'extension');
arch.finalize();
```

Created archive seems to contain all necessary files (size looks ok), but I can't extract it using Finder on Mac OS X with "Unable to expand ... (Error 2: No such file or directly)", also it doesn't open using vim plugin. Seems like some headers or "root" entry is missing.

Also, it opens ok with "RAR Archiving Utility" for Mac (which I believe is a Windows port), so I assume it is specific to Mac OS X.

**Comment by ctalkington** [comment]
this

```
arch.on('end', function() {
    console.log('Created extension.zip');
    process.exit(0);
});
```

should be

```
out.on('end', function() {
    console.log('Created extension.zip');
    process.exit(0);
});
```

**Comment by inca** [comment]
@ctalkington Yep, makes complete sense. Thank you!
