### ISSUE TITLE
glob does not work with cwd option

### ISSUE THREAD

**Issue by MojoJojo** [archiverjs/node-archiver#173]
Hi,
It seems like the glob method on the plugin fails if glob cwd option is used. For instance, consider the directory structure:

|-A
|  |---b.txt
|  |---c.txt
|  |---D
|      |---e.txt
|-buildScript.js

So if inside my build script, I use the following:

archive.glob(options.awsArchiveGlobPattern,{cwd:'D'}).finalize();

the archiving step fails with error as the archiver is running from base directory while glob returns a path which says e.text (not D/e.txt)

I do not want to use the directory method as I still want to apply pattern filters. The objective is to create a zip file say test.zip which on expanding has e.txt at the root, instead of D/e.txt.

**Comment by ctalkington** [comment]
its likely that logic will have to be created so that it can find the files when cwd is set.

let me see if this is something thats as straight forward as it sounds.

**Comment by ctalkington** [comment]
this should be covered in v0.21
