### ISSUE TITLE
Large zip files not finalizing correctly

### ISSUE THREAD

**Issue by mattpen** [archiverjs/node-archiver#176]
Hello, I'm having some trouble using this utility for large files.  When I create a zip that is large (say >500MB), the zip file does not finalize correctly.  When I run the same code on a file <100MB, it works as expected.  When I try to open the resulting file of this program with `less flash-sims.zip`, I get the error `End-of-central-directory signature not found.`  Similarly the windows zip utility has trouble reading the file.  However, jar and 7-zip are able to extract the content normally.  All the content is added to the file and zipped, its just not closed properly.  I've attached the troulesome code below.

```
var request = require( 'request' );
var fs = require( 'fs' );
var zip = require( 'zip-stream' );
var async = require( 'async' );

var file = 'file.zip';
var out = fs.createWriteStream( file );
var archive = new require( 'zip-stream' )();
var funcs = [];

archive.pipe( out );
archive.on( 'error', function( err ) {
  console.log( err );
})

function functionFactory( archive, fileName ) { 
  return function( callback ) { 
    try {
      archive.entry( 
        fs.createReadStream( fileName ), 
        { name: fileName }, 
        callback ); 
      console.log( fileName + " writing to zip.");
    }
    catch (e) {
      console.log( fileName + " not found.");
    }
  };
};

request( 'http://phet-dev.colorado.edu/services/metadata-api?format=json&type=flash&summary=true', function(err, res, body) {
  if ( err ) throw err;
  var projects = JSON.parse( body ).projects;
  for ( var i in projects ) {
    /**
     * additional code here for parsing target filename
     **/
    funcs.push( functionFactory( archive, '/path/to/' + projects[i].name + '.jar' ) );
  };
  async.series( 
    funcs, 
    function( err, results ) { 
      console.log( 'zip finished.' ); 
      archive.finalize();
      archive.end();
    } );
} );
```

**Comment by mashaly100200** [comment]
for me my problem was using archive.end() after archive.finalize()
removing archive.end()   solved my problem

**Comment by soyuka** [comment]
```
archive.pipe( out );
archive.on( 'error', function( err ) {
  console.log( err );
})
```

You should listen for events before you pipe.

```
      archive.finalize();
      archive.end();
```

`finalize` will suffice.

Please read https://github.com/archiverjs/node-archiver/issues/170 lots of informations there :)

**Comment by mattpen** [comment]
@mashaly100200 @soyuka - Thanks for the help!  I moved the error handling before the pipe call and removing the archive.end() call.  I'm still getting the same problem though.  The content is all in the zip file, I can open it with `jar xf', but not with less or with the windows zip utility.

The content that is being zipped is all .jar files.  Would this cause any problems?

**Comment by ctalkington** [comment]
hey, sorry i've been in a job transition and have been busy.

ok so your using `zip-stream` not `archiver` there are some major differences in how `zip-stream` works as it doesn't have built in queue logic.

does `store: true` work any better for you?

What OS are you creating on?

**Comment by francispelland** [comment]
As soon as the files reach 4.2GB it appears that they get corrupted.  I am unable to open any ZIP files made above that size.  4.1GB works fine though.

Good (4.1GB)
![2016-03-15_1449](https://cloud.githubusercontent.com/assets/4448538/13790096/291ea092-eabd-11e5-9c65-bcff90ba1f04.png)

Bad (4.7GB)
![2016-03-15_1449_001](https://cloud.githubusercontent.com/assets/4448538/13790271/03a8d2f0-eabe-11e5-8f47-0f608715ae92.png)

Here is the code
`var archiver = require('archiver');
				
				var output = fs.createWriteStream(zipPath);
				var zipArchive = archiver('zip');
				
				output.on('end', function() {
					var source = fs.createReadStream(zipPath);
					var mantaStream = mantaClient.createWriteStream("~~/stor/customers/"+clientInfo.backupLogin+"/backups/"+backupInfo.data.id+"_"+backupInfo.data.uuid+".zip");
			
				    source.pipe(mantaStream);
				
				    mantaStream.once('end', function (res) {
				        callback();
				    });
				
					mantaStream.on('error', function(err) {
						console.error(err);
						
					  	// TODO handle err as appropriate
						helpers.fail(updated.info.type, updated.info.id, {message: 'Unable to upload backup. '+err.message}, function(data){
					
						});
					});	
				});
				
				zipArchive.pipe(output);
				
				zipArchive.bulk([
		 				{ src: [ '**/*' ], cwd: filePath, expand: true }
					]);
				
				zipArchive.finalize(function(err, bytes) {
					if(err) {
				    	throw err;
					}
				});`
