### ISSUE TITLE
textEntry not work

### ISSUE THREAD

**Issue by erdogankaya** [archiverjs/node-archiver#177]
var file2 = __dirname + '/erka.txt';
.bulk({src:file2,data:{name:'tr.txt'},dest:'kaya/',expand:true,flatten:true})

i try to save with new name but its use already old name

**Comment by ctalkington** [comment]
the easiest way to add a file is using the fuction designed for it.

http://archiverjs.com/docs/Archiver.html#file

```js
archive.file(file2, { prefix: 'kaya/', name: 'tr.txt' });
```
