### ISSUE TITLE
Unable to zip files above 4.2GB

### ISSUE THREAD

**Issue by francispelland** [archiverjs/node-archiver#179]
Looks like I am running into some 32 bit issue.  As soon as the files reach 4.2GB it appears that they get corrupted.  I am unable to open any ZIP files made above that size.  4.1GB works fine though.

Good (4.1GB)
![2016-03-15_1449](https://cloud.githubusercontent.com/assets/4448538/13790096/291ea092-eabd-11e5-9c65-bcff90ba1f04.png)

Bad (4.7GB)
![2016-03-15_1449_001](https://cloud.githubusercontent.com/assets/4448538/13790271/03a8d2f0-eabe-11e5-8f47-0f608715ae92.png)

Here is the code

```
var archiver = require('archiver');

var output = fs.createWriteStream(zipPath);
var zipArchive = archiver('zip');

output.on('end', function() {
                    var source = fs.createReadStream(zipPath);
                    var mantaStream = mantaClient.createWriteStream("~~/stor/customers/"+clientInfo.backupLogin+"/backups/"+backupInfo.data.id+"_"+backupInfo.data.uuid+".zip");

                    source.pipe(mantaStream);

                    mantaStream.once('end', function (res) {
                        callback();
                    });

                    mantaStream.on('error', function(err) {
                        console.error(err);

                        // TODO handle err as appropriate
                        helpers.fail(updated.info.type, updated.info.id, {message: 'Unable to upload backup. '+err.message}, function(data){

                        });
                    }); 
});

zipArchive.pipe(output);

zipArchive.bulk([
    { src: [ '**/*' ], cwd: filePath, expand: true }
]);

zipArchive.finalize(function(err, bytes) {
    if(err) {
        throw err;
    }
});
```

**Comment by soyuka** [comment]
Fat32 limit per file is around this value. Think it might be related?

**Comment by ctalkington** [comment]
when you get into that size, you do hit a few possibilities. testing is a bit tricky to automate as it would pretty harsh on the CI server to generate or pull that big of a file each time a change is made.

**Comment by soyuka** [comment]
+1 @ctalkington anyway I've build bigger files than this with archiver

**Comment by francispelland** [comment]
@soyuka I don't believe that is the issue, as the drive is formatted to NTFS.

@ctalkington for sure. However I am able to use WinRAR, Windows Explorer, and WinZip to compress the same files without a problem. This leads me to believe there is some sort of issue with Archiver.

I'm going to attempt a TAR compression to see if there is any luck there.  This looks like a 32 bit vs 64 bit issue. Not sure if that is possible?

**Comment by francispelland** [comment]
Just my luck, it looks like TAR does not work with a read stream.

[TypeError: Bad argument]
TypeError: Bad argument
    at new Buffer (buffer.js:194:21)
    at Readable.<anonymous> (D:\ASM\node_modules\archiver\node_modules\archiver-utils\index.js:39:15)
    at Readable.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)

**Comment by francispelland** [comment]
Tried to compress 3 files
- data.bak (4,703,843 KB)
- framework.bak (21,063 KB)
- repository.bak (67,636 KB)

The resulting ZIP from Archiver is 4,757,154KB.  Produced a ZIP of the same files with both WinRAR and Windows Explorer creating a ZIP that is 4,748,085KB.  

The one created by Archiver is corrupted, the others worked.

**Comment by francispelland** [comment]
I've switch to targz and everything is working fine as expected.  It is evident that the issue is in Archiver.

**Comment by nickmerwin** [comment]
Hi, I'm bumping up against this 4GB+ limit on a 64bit EC2 Ubuntu instance while streaming files from S3 to a zip stream then to a response stream.

Has anyone found a solution? Or an alternative streamable zip library?

Thanks.

**Comment by graywithanA** [comment]
I think I'm in a similar situation as @nickmerwin.  My setup has been working flawlessly for over a year but today I ran into an issue.  The files in question are quite large, a few are almost 6GB each and there's a lot more in the 100 - 500 MB range.

I'm using Archiver to stream files from S3 into a zip stream then to a response stream but my server (Digital Ocean 1GB memory, 30 GB disk, Ubuntu 14.04) is running out of memory and killing Node.  From the user's end the download appears to have finished but the zip is corrupted and cannot be opened since it wasn't properly finalized.

**Comment by aethant** [comment]
I'm adding my +1 to the streaming from S3 to an archive on a Ubuntu EC2 instance. Kills my server. Has anyone figured out a solution for this?

**Comment by Prinzhorn** [comment]
This is a limitation of the zip format **itself** as the file size for each entry is stored with 4 bytes.
There's an extension called ZIP64 which removes this limitation but comes at the cost of compatibility with clients that don't support it https://en.wikipedia.org/wiki/Zip_(file_format)#ZIP64

**Comment by ctalkington** [comment]
zip64 is supported and if anyone still has issues id love to work through them in a new issue. closing due to age and lack of ongoing discussion.
