### ISSUE TITLE
Root directory inside tar file

### ISSUE THREAD

**Issue by adenys** [archiverjs/node-archiver#180]
Hi
I can't get rid of the root directory inside the tar file.
I have a pretty simple gulp task:

```
var output = fs.createWriteStream('tgz/target.tgz');
var archive = archiver('tar');
archive.pipe(output);
archive.directory('build', '');
return archive.finalize();
```

But when I unpack target.tgz there is the folder "target" with build folder content...
I'd like my build folder content to be on the root level of the archive.

I've seen this issue - https://github.com/archiverjs/node-archiver/issues/142
But leaving the second parameter of the **directory()** method does not do the trick. I only change the name of the wrapping folder if provide the second argument.

**Comment by ctalkington** [comment]
sorry for you troubles, have you tried passing false (boolean) instead of empty string, think the documentation might be lacking in this case

**Comment by adenys** [comment]
sorry, but the problem remains:
`
archive.directory('build', '');
`
and 
`
archive.directory('build', false);
`
will end up with "target" folder as a wrapper...

**Comment by ctalkington** [comment]
are you passing `gzip: true` since using tgz? it might change how its parsed.

**Comment by adenys** [comment]
I changed this line of code: 
`var archive = archiver('tar');`
to :
`        var archive = archiver('tar', {
            gzip: true
        });
`
but wrapping "target" folder is still present.

**Comment by ctalkington** [comment]
that wrapping comes from prefixing the destpath (second argument of `directory` but `false` should fully disable that. i would have to double check tar-stream to see if it changed its behavior recently.

**Comment by scautank** [comment]
I have the same problem. When there are multiple files, will create a folder as a wrapper.

**Comment by j** [comment]
I too was trying to do the same thing.

Any status @ctalkington  ?

**Comment by Prinzhorn** [comment]
> But when I unpack target.tgz there is the folder "target" with build folder content...

How do you unpack the archive? E.g. the default behavior on Ubuntu when unpacking an archive is to create a folder with the same name and put the contents inside. That does **not** mean the archive itself contained a root folder. Given your code I don't see where a `target` folder could potentially even come from. If there would be a root folder it would be called `build`.

Example code

```js
var fs = require('fs');
var archiver = require('archiver');

var output = fs.createWriteStream('./target.tgz');
var archive = archiver('tar');
archive.pipe(output);
archive.directory('build', '');
archive.finalize();
```

Where `build` contains just "1.txt" and "2.txt". The archive does not have a root folder.

`strings < target.tgz` (which kinda lets you look into the entries of the file) gives

```
1.txt
000664 
000000 
000000 
00000000000 13000123675 010112 
ustar
000000 
000000 
2.txt
000664 
000000 
000000 
00000000000 13000123677 010115 
ustar
000000 
000000
```

**Comment by deshazer72** [comment]
has anyone solved this I am having the same issue everything works fine it creates my zip and zips all the videos from my videos directory but it also puts another videos directory with more videos inside of it here is my code 
![videozippic](https://cloud.githubusercontent.com/assets/20157793/25056370/0041467c-212e-11e7-8b33-933b69f77c88.PNG)


```
`upload(req, res, function (err) {
    let hasError = false;
    const output = fs.createWriteStream('./videos.zip');
    const archive = archiver('zip', undefined);

    output.on('close', function () {
      console.log(archive.pointer() + 'total bytes');
      console.log('archiver has been finalized and the output file descriptor has closed.' + ' ' + 'came from upload');
      if (!hasError) {
       return res.status(200).send({ SopVideo: 'received' });
      }
    });

    archive.on('error', function (err) {
      hasError = true;
     return res.status(500).send({ SopVideo: 'error', error: err });
    });
    archive.pipe(output);
    archive.directory('./videos', false);
    archive.finalize();
  });`
```

**Comment by ctalkington** [comment]
have you tried it as:

```archive.directory('videos', false);```

also what version of archiver/node?

**Comment by deshazer72** [comment]
that fixed it thank you
