### ISSUE TITLE
Archiver error event

### ISSUE THREAD

**Issue by simon-p-r** [archiverjs/node-archiver#181]
Hi

I can't seem to simulate an error on the archiver object created by archiver.create method.  I am trying to zip a folder like below and want to test an error condition.

  
    const root = destination.root || process.cwd();
    const outputDir = Path.resolve(root, destination.path);
    const archiver = Archiver.create('zip');
    const writeStream = new WriteStream(outputDir);

    writeStream.on('error', (err) => {

        return cb(err, null);
    });

    writeStream.on('close', () => {

        return cb(null, `Success`);
    });

    archiver.on('error', (err) => {

// Can't get this error here!
        
        return cb(err);

    });

    archiver.pipe(writeStream);
    archiver.append('someString, { name: 'file1' });
    archiver.append('anotherString', { name: 'file2' });
    archiver.finalize();

Thanks
Simon

**Comment by Prinzhorn** [comment]
If all you want is to trigger an error then look out the source code for possible causes of errors. For example using `append` when the archive is already finalized (https://github.com/archiverjs/node-archiver/blob/0adf12c34f856267a05fe40f8bfef8dbca4d234d/lib/core.js#L498). Switch your last two lines and you get an error.

```js
archiver.finalize();
//Will cause "Error: append: queue closed"
archiver.append('anotherString', { name: 'file2' });
```

**Comment by simon-p-r** [comment]
Thanks @Prinzhorn I will close issue
