### ISSUE TITLE
Generated tar archives not compatible with `node-tar`

### ISSUE THREAD

**Issue by gcnm-pgeil** [archiverjs/node-archiver#182]
The tar archives generated by node-archiver are not compatible with `node-tar` and thus they can, for example, not be interpreted by `npm` which uses node-tar internally. 

Steps to reproduce:

`npm install a-tarball-generated-by-archiverjs.tar`

**Comment by ctalkington** [comment]
can you provide output you get?

ill try to look into this weekend but we simply use node-tar and im not too familiar with npm tar requirements. does the file work with other commands/tools?

**Comment by gcnm-pgeil** [comment]
Sorry for my late feedback. I will provide a sample tar file soon.

**Comment by ctalkington** [comment]
closing for lack of response. feel free to provide any additional information in a new issue if things persist
