### ISSUE TITLE
Excluding files

### ISSUE THREAD

**Issue by jsloyer** [archiverjs/node-archiver#185]
Since `bulk` has been deprecated it doesn't seem there is a way to exclude files, whats the recommended approach?

**Comment by rribou** [comment]
You can use glob()
```
archive.glob('**/*', {
    cwd: '/home/user/project',
    ignore: ['file1', 'file2', 'file3']
}, {})
```

**Comment by leefsmp** [comment]
Do you mind providing a slightly more explicit example, I'm struggling finding how to do that simple thing:
I have a directory named "folder1" that may contain multiple files and nested sub directories, I want to zip "folder1" into "folder1.zip"... how do I get that job done? Thanks in advance

**Comment by wenxiongid** [comment]
maybe you can try this:

```js
archive.glob('folder1/**/*', {
  cwd: '/home/user/project',
  ignore: ['file1', 'file2', 'file3']
}, {});
```

**Comment by arichiardi** [comment]
I had the need for this feature, but one that would exclude a glob instead of individual files. Is there any doc regarding `:ignore`? I guess it is compression dependent?

**Comment by ledlamp** [comment]
does `**/*` mean it will include all files in the directory regardless of depth?
I need to zip.directory() but exclude a directory inside that directory.

**Comment by ravindra237** [comment]
> does `**/*` mean it will include all files in the directory regardless of depth?
> I need to zip.directory() but exclude a directory inside that directory.

By using this, it will zip all files and subfolders
Archive.glob('**/*', 
            {
                cwd: source,
                ignore: ignore,
                nodir: true,
                dot: true,
                follow: true
            }
        )
