### ISSUE TITLE
Resuming Remote Archive 

### ISSUE THREAD

**Issue by JAForbes** [archiverjs/node-archiver#186]
Is it possible to manually concatenate zip file entries so that I can use a multi part upload across multiple sessions?  Possibly finalizing a zip that has already been built over multiple sessions?

My understanding is that the zip file has a central directory structure that sits at the end of the file.  And that the rest of the file is the compressed file content + headers for every file.  I'm hoping I can manually assemble/construct the constituent parts over many sessions, is that possible?

I have hundreds of thousands of RAW photo and video files sitting on an s3 bucket.  I need to be able to archive an arbitrary number of these files.  I can't do it in a single session because the processing would be happening on an AWS Lambda function which has a 5 min time limit (and therefore a size limit).

The low level API I'm hoping for is something like:

```js
var compressedFile = archiver('zip').singleFile()
var download = s3.getObject(...).createReadStream()
download.pipe(compressedFile)

s3.uploadPart({
  Key: 'somefile.zip',
  Body: compressedFile,
  PartNumber: 0
})
```

And in the final session when I've uploaded the last file.

```js
var filenames = [{ filename, created, partNumber }, ...]
var centralDirectory = archiver('zip').centralDirectory()

s3.uploadPart({
  Key: 'somefile.zip',
  Body: centralDirectory,
  PartNumber: 10000
})
```

I'm assuming the hardest part would be creating an accurate central directory after the fact..

Any help or direction would be greatly appreciated.  Thank you.

**Comment by meteormatt** [comment]
you can use `append` method  manually concatenate zip file entries.

**Comment by JAForbes** [comment]
That won't work in this situation.  I'm talking about manually generating the respective headers in separate processes (on separate servers in parallel).  Unless I am misunderstanding you, you're suggesting there is an archive to `append` to, whereas I require generating a binary segment of a zip file to be manually assembled via something like AWS Multipart Upload.

I've since written my own solution though so I'll close this issue.

**Comment by meteormatt** [comment]
Oh. sorry :sweat_smile:

**Comment by JAForbes** [comment]
no problem :)

-----Original Message-----
