### ISSUE TITLE
Unhandled stream error in pipe - When close tab or browser

### ISSUE THREAD

**Issue by JohanAlvarado** [archiverjs/node-archiver#192]
when archiverjs is working , and I close a tab or browser node throws the following error

`stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

Error: Parse Error
    at Error (native)
    at Socket.socketOnData (_http_client.js:309:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:531:20)`

**Comment by ctalkington** [comment]
i havent worked with http streams but maybe the new release will help as it bubbles errors. you are always expected to have an error handler of your own at the highest level or you will see those unhandled errors still.

**Comment by Prinzhorn** [comment]
Can you create a simple demo? I'm using express and `archive.pipe(res);`. If the client (curl) cancels the request midstream, nothing happens on the server.

Does this issue still exist?

**Comment by ctalkington** [comment]
closing based on age. we have an example of express here.

https://github.com/archiverjs/node-archiver/blob/v1.3/examples/express.js

feel free to report via new issue if this is still relevant.
