### ISSUE TITLE
Archiver is not releasing memory?

### ISSUE THREAD

**Issue by mprokopowicz** [archiverjs/node-archiver#195]
I have problem with memory consumption while using archiver, attached simple demo with forced GC (I'm taring ~200 files with total size ~70mB):

``` javascript
'use strict';
var archiver = require('archiver');


console.log(process.memoryUsage());


var backupStream = archiver.create('tar', {gzip: false});
for(var i = 1; i <= 200; i += 1) {
  backupStream.file(__dirname + '/../fixtures/data/backup-dir-2/' + i + '.jpg');
}
backupStream.finalize();
backupStream.on('finish', function() {
  console.log(process.memoryUsage());
  global.gc();
  process.nextTick(function() {
    console.log(process.memoryUsage());
  });

  setTimeout(function() {
    console.log(process.memoryUsage());
  }, 5000);
});
backupStream.resume(); //let all data be lost
```

This gives me following results:

```
{ rss: 31371264, heapTotal: 14675968, heapUsed: 9370664 } //process started
{ rss: 130125824, heapTotal: 23064576, heapUsed: 10496192 } //tar finished
{ rss: 117293056, heapTotal: 24113152, heapUsed: 9178552 } //forced GC after finished
{ rss: 117301248, heapTotal: 24113152, heapUsed: 9201624 } //5s after finish
```

After a few such operations my production process is getting out of memory. Any ideas what could be wrong?

**Comment by soyuka** [comment]
Weird, I'm using this on much bigger files (with zip) and my web server does release memory afterwards. I didn't try using tar though.

**Comment by ctalkington** [comment]
whats the server environment?

**Comment by mprokopowicz** [comment]
@ctalkington Prudction env is an embeded linux, but I've reproduced same problem on OS X and node 0.10.26.

**Comment by ctalkington** [comment]
there is a case where certain streams don't get closed based on a PR received and recent lyrics merged into compress-commons.

https://github.com/archiverjs/node-compress-commons/pull/19

https://github.com/archiverjs/node-compress-commons/commit/ac653606223934cc117314c1a83c1789f1b107e5

keep an eye out for a release soon and let me know if that helps.

**Comment by ctalkington** [comment]
this was all merged and released a while back. please try the latest versions which includes other optimizations as well
