### ISSUE TITLE
Windows: compressed zip folder has invalid format

### ISSUE THREAD

**Issue by vitalets** [archiverjs/node-archiver#196]
I'm creating zip on Mac osx and it is uncompressed correctly on mac finder.
But when I try to uncompress it on Windows 7 using standard "Extract all..." from right click menu of zip folder, I'm getting error:

```
compressed zip folder has invalid format
```

Using cmd unzip command works fine, using 7-zip also works fine.
What can be wrong?

**Comment by tmiller71** [comment]
Any luck with this?  I'm having the same issue.

**Comment by vitalets** [comment]
Currently not. 
I\m doing it using cli now:
```js
const fs = require('fs-extra');
const path = require('path');
// zip files created by this module are not extractable window default uncompress folder command
// see: https://github.com/archiverjs/node-archiver/issues/196
const archiver = require('archiver');
const exec = require('child_process').exec;

function createCli(dir, outFile) {
  return new Promise((resolve, reject) => {
    const relPath = path.relative(dir, outFile);
    exec(`zip -r ${relPath} .`, {cwd: dir}, error => error ? reject(error) : resolve());
  });
}
```

let's ping @ctalkington directly =)

**Comment by tmiller71** [comment]
All is good for me.  It turns out the directory I was archiving had too many nested folders (thanks to Node).  Once I excluded the node_modules directory the compressed file was valid.

**Comment by ctalkington** [comment]
thanks for the ping, notifications on github never seem to work the way i want so I dont see alot of the initial reports.

as far as im aware this should be working fine, i don't have a CI that runs mac so its a bit harder to make tests to confirm such.

the paths being long could cause some issue for windows, i dont think built in explorer tool supports the extended paths feature of windows.

**Comment by DmitryKrekota** [comment]
+1
I also have same error on Windows 10.

**Comment by ctalkington** [comment]
haven't personally been able to create this, if anyone encounters this still with v2.0.0 please open a new issue and provide as much detail and reproduction guidance as possible.
