### ISSUE TITLE
npm size

### ISSUE THREAD

**Issue by ecmel** [archiverjs/node-archiver#197]
Uncompressed node_modules size is around 2.13 MB. More than half of it stems from loadash.

Is there a way to trim the size? (May be https://www.npmjs.com/browse/keyword/lodash-modularized can be used)

**Comment by ctalkington** [comment]
hum i think I did this previously but reverted due to dep trees but maybe with newer npm its not as much of an issue.

**Comment by ctalkington** [comment]
with the latest release, im seeing the uncompressed size is about 500kb. this might vary because im using the newer npm which better organizes deps to avoid duplication.

**Comment by ecmel** [comment]
Using node.js 6.9.1 LTS, `lodash` still contributes a lot:

<img width="372" alt="capture" src="https://cloud.githubusercontent.com/assets/1858678/19835436/fe9d8a28-9e8e-11e6-9446-f52b1c616e83.PNG">

**Comment by ctalkington** [comment]
I may re-evaluation the usage of lodash or tweak it slightly as its usage is limited to a few areas last I checked anyways. will see what the new year brings in terms of free time to do so.

**Comment by ctalkington** [comment]
i think our deps are pretty solid and with move to node v4+ ill likely re-eval this further but for now closing as its a common package and other deps depend on it and newer versions of npm handle directory tree/size better.
