### ISSUE TITLE
Add examples to the docs

### ISSUE THREAD

**Issue by fewstera** [archiverjs/node-archiver#200]
As someone who has never used archiver before, not having any examples inside the documentation make it much harder to use.

It's be nice if you provided a few basic examples in the documentation. Like you do in the examples/ directory of this repo.

Thanks

**Comment by Krossmaskinen** [comment]
The docs for usage (or even api methods) are horrible. Please update!

**Comment by soyuka** [comment]
https://github.com/archiverjs/node-archiver/tree/master/examples ?

**Comment by soyuka** [comment]
Hmm you've the `examples` directory, api docs are always ugly but look fine to me ^^.

**Comment by ctalkington** [comment]
@Krossmaskinen do you have an example of API docs that aren't horrible? constructive criticism is preferred over a blanket statement that doesn't help anything move forward.

**Comment by Krossmaskinen** [comment]
@ctalkington very sorry about this, I should've provided an example and not being a douchebag. I also realized I was looking at the wrong places for answers in the API.

I think I was caught up in being a bit annoyed by not finding any examples on how to use the library and also didn't find the help i needed in the API docs.
This:
```
var archiver = require('archiver');
var archive = archiver.create('zip', {}); // or archiver('zip', {});
```
didn't help me understand how to actually zip anything, just how to initialize the library.

**Comment by ctalkington** [comment]
@Krossmaskinen it happens. i have some ideas for this that I will try to incorporate in the near future.

**Comment by ctalkington** [comment]
@Krossmaskinen we now have a quick start section as part of the readme which hopefully with aid new users.

https://archiverjs.com/docs/#quick-start
