### ISSUE TITLE
Promise API

### ISSUE THREAD

**Issue by stevenvachon** [archiverjs/node-archiver#207]
like [archiver-promise](https://npmjs.com/archiver-promise)

**Comment by ctalkington** [comment]
this seems like something that could be implemented. If I have time over the holiday break, I'll try to put something together.

**Comment by stevenvachon** [comment]
Awesome

**Comment by imravichaudhary** [comment]
+1

**Comment by sangoon** [comment]
+1

**Comment by stevenvachon** [comment]
This pending `Promise` needs to be `resolve()`'d.

**Comment by dougpuob** [comment]
+1

**Comment by stevenvachon** [comment]
@ctalkington which holiday break were you referring to? :)

**Comment by soyuka** [comment]
@stevenvachon no need to push if @ctalkington doesn't had the time to look into this ;). I'm sure he hasn't forget and is just busy elsewhere. This remains an open source software done on his free time. 

In the mean time you can either propose a pull request on the repository or use `archiver-promise` no?

**Comment by stevenvachon** [comment]
@soyuka it was a joke

**Comment by soyuka** [comment]
I didn't felt as one, especially that it's your 4th interaction on this topic with no constructive addition. I'm sorry if I overreacted but IMHO we can't joke about this (especially since open source burnout is a real sensitive subject nowadays).

**Comment by stevenvachon** [comment]
My third was a joke as well, but the author may have missed it since I didn't mention his username. Burnout isn't a sensitive subject -- the project can be forked or a new maintainer can step in. 4 months isn't a length of time to communicate burnout, anyway.

**Comment by ctalkington** [comment]
its all good, i just got busier than expected and have been since with my full time job. i have looked into it a few times since my last message and am just learning more about promises and possible negatives (ie memory leaks in some versions of node and the various userland options) before i implement such.

**Comment by DiegoZoracKy** [comment]
Today i knew about this module and it saved me a plenty of time. Thanks for that @ctalkington.
I found this thread now and i will leave here a function that i had to create quickly to archive directories using promises. Maybe it can be useful for someone to use, or to follow as a guidance when creating promise based methods.

```javascript
function archiveDirectory(src, dest, format = 'zip', { archiverOptions = {}, directoryData, directoryDestPath = false } = {}) {
	return new Promise((resolve, reject) => {
		const archive = archiver(format, archiverOptions);
		const output = fse.createWriteStream(dest);

		archive.pipe(output);
		archive.directory(src, directoryDestPath, directoryData);
		archive.finalize();

		output.on('close', () => resolve(archive));
		archive.on('error', (err) => reject(err));
	});
}
```

**Comment by soyuka** [comment]
Closing, continue in #242 if discussion it needs. https://github.com/archiverjs/node-archiver/commit/55e8b7b78b0bb1a764e00ff32876188b82bed245 introduces promise support on `.finalize`.
