### ISSUE TITLE
directory structure?

### ISSUE THREAD

**Issue by jzzj** [archiverjs/node-archiver#212]
I'm trying to zip several folders like:
a
  => b
  => c
  => d

The result I want is:
file.zip
=> b
=> c
=> d

I had tried change the working directory, but it ends up like this:
file.zip
file
  => b
  => c
  => d

So, what can I do to strip the root folder?

**Comment by ctalkington** [comment]
do you have a sample of code being used?

**Comment by jzzj** [comment]
@ctalkington Yes, here is my code:
```js
var fs = require('fs');
var archiver = require('archiver');

module.exports = function(dir, outputFile, callback){
  var originalDir = process.cwd();
  // create a file to stream archive data to.
  var output = fs.createWriteStream(originalDir + '/' + outputFile);
  // strip the root dir, like: a/b/c => b/c
  var stripDir = /^\//.test(dir) ? '' : dir.replace(/^(.+?\/).*$/, '$1');
  chdir(stripDir);
  dir = dir.replace(stripDir, '');

  var archive = archiver('zip', {
      store: true // Sets the compression method to STORE.
  });

  // listen for all archive data to be written
  output.on('close', function() {
    console.log(archive.pointer() + ' total bytes');
    console.log('archiver has been finalized and the output file descriptor has closed.');
    chdir(originalDir);
    callback();
  });

  // good practice to catch this error explicitly
  archive.on('error', function(err) {
    throw err;
  });

  // pipe archive data to the file
  archive.pipe(output);
  // append files from a directory
  archive.glob(dir);
  // finalize the archive (ie we are done appending files but streams have to finish yet)
  archive.finalize();
}

function chdir(dir){
  try {
    process.chdir(dir);
    console.log('New directory: ' + process.cwd());
  }catch (err) {
    console.error('chdir: ' + err.stack);
  }
}
```

**Comment by ctalkington** [comment]
have you tried directory? I believe this might do same thing and work better:

archive.directory(dir, false)

You should be able to drop any cwd changing and stripping logic as it internally makes all files relative to dir and then adds it back if not overrides by parameter. setting a destpath to false means root of archive. no prefix

https://archiverjs.com/docs/Archiver.html#directory

**Comment by jzzj** [comment]
@ctalkington I just found why always have the prefix folder when I unzipping the zip file. It's the default action when I double-click the .zip file on my mac. When I use the command-line ```unzip```, it works as expected: no extra prefix folder.  
By the way, both of change working dir and use directory(dir, false) works.
Really sorry for that.
