### ISSUE TITLE
Compression options do not work

### ISSUE THREAD

**Issue by dailypixie** [archiverjs/node-archiver#213]
Using various levels of compression the zip file size does not change significant. The size variation is smaller  than 1%.

**Comment by dailypixie** [comment]
Between zlib level 6 and level 9, the difference is too small. The size of the archives are 2,840,356,143 bytes ( level 6), 2,840,353,295 bytes (level 9), 2,850,082,816 bytes (uncompressed folder).

**Comment by dailypixie** [comment]
`
var folder = (some path...);
var output = fs.createWriteStream(folder + '.zip');
zipClient = new archiver('zip', {
		  'zlib': {
		  	'level': 9
		  }
		}); 
zipClient.pipe(output);
zipClient.directory(folder + '\\');
zipClient.finalize();`

**Comment by ctalkington** [comment]
please keep in mind, not all things are able to be fully compressed. text based files tend to show better results. these levels come from node and arent something that archiver really controls. the OS in use and its zlib libraru could possibly make a difference as well.

**Comment by dailypixie** [comment]
Why did you close the issue? The response does not resolve the issue nor does it provide a reasonable explanation.

**Comment by dailypixie** [comment]
The operating system is Windows 10, the data that it archives are picturesin .jpg format.
