### ISSUE TITLE
Bulk method should not be deprecated | not same as directory or glob

### ISSUE THREAD

**Issue by attilavago** [archiverjs/node-archiver#215]
https://archiverjs.com/docs/Archiver.html#bulk should not be deprecated and here's why. Both directory and glob zip with all root folder included, whereas bulk does not. Here's 2 lines of code that I expect to do the same, but it does not.

`archive.bulk([{ src: [ '**/*' ], cwd: './temp/books/', expand: true }]);`
and 
`archive.glob('./temp/books/**/*');`

**Comment by ctalkington** [comment]
hi so you can pass options to glob such as `cwd` via the second parameter.

```js
archive.glob('**/*', { cwd: './temp/books' });
```

you can also use `directory` with a destpath of `false` or `''` as such:

```js
archive.directory('./temp/books', false);
```

do these produces the expected results for you?

**Comment by attilavago** [comment]
@ctalkington , that worked! Did I miss that in the docs? I read through it like 5 times... :) Anyway, this sorted it, and if it's not in the docs, please add it, it's very useful for zipping up .ePub files.

Kind regards,
Attila

**Comment by PierBover** [comment]
So how do you include files in a directory and it's subdirectories at the root of the zip file?

I've tried all sorts of glob patterns and subdirectories are never included. For example `./path/directory/**/*.*`, `./path/directory/**`, `./path/directory/**/*`.

And then the directory structure `/path/directory` is maintained in the zip file. I've used `cwd:"./"` but maybe I'm not understanding what it does.
