### ISSUE TITLE
Is it possible to write to memory rather then fs?

### ISSUE THREAD

**Issue by eugenekgn** [archiverjs/node-archiver#216]
I want to write/pipe to some sort of buffer rather than file system, and then send it of to the server in binary format, how would one do that?

**Comment by soyuka** [comment]
Just pipe it to your writable stream? 

https://github.com/archiverjs/node-archiver/blob/master/examples/express.js#L23 for example

**Comment by imravichaudhary** [comment]
Here is a good article explain about creating writable memory stream: http://codewinds.com/blog/2013-08-19-nodejs-writable-streams.html

**Comment by ctalkington** [comment]
thanks everyone for chiming in here. closing but most any writable stream should work just fine. the beauty of steams is that the medium doesnt matter as much.
