### ISSUE TITLE
Archive hanging near the end of zipping

### ISSUE THREAD

**Issue by Kullersj** [archiverjs/node-archiver#217]
I'm trying to create an application to download images from AWS S3 and zip them into a file. 

I'm running into an issue where the application just stops and doesn't appear to continue.

```
var output = fs.createWriteStream(__dirname + "/" + zipName);

  var archive = archiver('zip');

  archive.on('error', function(err) {
    throw err;
  });

  archive.pipe(output);

  //Add Files to Zip Archive
  var count = 0;

  async.each(fileList, function iterator(item, callback){
    var fileName = item.name + "/" + count + ":" + item.caption.trim() + path.extname(item.asset);
    count++;
    var bucket = urlPrefix.substring(0, urlPrefix.indexOf("/"));
    var fileLocation = urlPrefix.substring(urlPrefix.indexOf("/") + 1) + item.asset;

    var params = {
      Bucket: bucket,
      Key: fileLocation
    };
    s3.getObject(params, function(err, data){
      if(err){
        console.log(err);
        callback(err);
      } else {
        console.log("zipping ", fileName, "...");
        archive.append(data.Body, {name: fileName});
        callback();
      }
    });
  }
  ,function(done){
    console.log("here");
    output.on("close", function() {
      console.log(archive.pointer() + " total bytes");
      console.log("archiver has been finalized and the output file descriptor has closed.");
    });
    archive.finalize();
  });
```

The code will run and I see the archiving happen but when I have ~100 or more photos it never gets to the console.log("here") line so the zip is never finalized. The archive finalized correctly where I only had ~80 photos.

Am I doing something wrong here or is there a better way to optimize this?

Thanks!

**Comment by ctalkington** [comment]
you would need to listen for the output streams `end` or `close` event (usually `close` with fs) to ensure your data is fully written to destination otherwise the steams may stop steaming before its all written (in your case, to disk).
