### ISSUE TITLE
"Quick Start" unclear on compression

### ISSUE THREAD

**Issue by ssorallen** [archiverjs/node-archiver#218]
From the [Quick Start](https://archiverjs.com/docs/#quick-start) guide:

```
// create a file to stream archive data to.
var output = fs.createWriteStream(__dirname + '/example.zip');
var archive = archiver('zip', {
    store: true // Sets the compression method to STORE.
});
```

I copied the Quick Start code because I'm a Zip/compression noob, and it took me a while to figure out why Archiver was producing a massive .zip file compared to OS X Finder's right click "Compress 'folder'" menu option. Noting that "STORE" means "no compression" would be hugely useful.

    // Sets the compression method to STORE (no compression)

**Comment by ctalkington** [comment]
ive updated the quick start to show configuring level instead. its been store as its quick to debug if compression bug or such but i can see how it might be confusing so dont mind changing the docs here.
