### ISSUE TITLE
Fails to create an extractable tar.gz archive including a unicode directory with some specific pattern

### ISSUE THREAD

**Issue by Mensu** [archiverjs/node-archiver#220]
The archive ``result.tar.gz`` generated by the following codes fails to be unpacked:

``` js
const archiver = require('archiver');
const archive = archiver('tar', { store: true, gzip: true });
const writeStream = require('fs').createWriteStream('result.tar.gz');
archive.pipe(writeStream);

// the specific pattern I found:
// here, a '0' represents an ASCII character and a '哈' represents a unicode character
const prefix = './0000000哈哈000哈哈0000哈哈00哈00哈0哈哈哈哈哈0哈/0000哈哈哈/';
const name = 'somefile.txt';
archive.append('any text', { prefix, name });

archive.finalize();

```

I think it might be a problem with the ``tar`` part, not the ``gzip`` part.

I have tried the codes on node of both version 6.9.1 and 7.5.0, producing the same result.

I know I can just switch to another directory pattern to avoid this pattern because in almost all of the cases the ``archiver`` module works perfectly, but I am afraid it is not the only pattern that would produce an unextractable archive.

Sorry if there are anything I failed to make clear.

**Comment by ctalkington** [comment]
does it work as a zip? store has no effect on tar btw.

**Comment by Mensu** [comment]
@ctalkington Yeah, there are no problems with zip. I have tried this as well, and found ``tar-stream`` also produced an unextractable tar. Now I take it that it may be a problem lying in ``tar-stream``, which ``node-archiver`` relies on if I am right.

```js
const tar = require('tar-stream');
const writeStream = require('fs').createWriteStream('result.tar');
const pack = tar.pack();
pack.pipe(writeStream);

const directory = './0000000哈哈000哈哈0000哈哈00哈00哈0哈哈哈哈哈0哈/0000哈哈哈/';
const name = directory + 'somefile.txt';
const entry = pack.entry({ name }, 'any text');

pack.finalize();

```

**Comment by ctalkington** [comment]
@Mensu let me know if i need to do anything on my side to update tar-stream once its fixed upstream.

**Comment by Mensu** [comment]
@ctalkington No, I don't think it is a problem on your side, and the team of tar-stream doesn't seem to be working on [this problem](https://github.com/mafintosh/tar-stream/issues/66)...

**Comment by Mensu** [comment]
Fixed on upstream https://github.com/mafintosh/tar-stream/pull/77
