### ISSUE TITLE
Exclude directories/files?

### ISSUE THREAD

**Issue by dsgill** [archiverjs/node-archiver#221]
I need to exclude specific directories and files while tarring others. I have not seen a way to do this in your documentation. Is it possible to exclude while tarring?

**Comment by ctalkington** [comment]
the best option for excluding is `glob`  (https://archiverjs.com/docs/Archiver.html#glob) with ignore option:

> ignore Add a pattern or an array of glob patterns to exclude matches. Note: ignore patterns are always in dot:true mode, regardless of any other settings.
> https://github.com/isaacs/node-glob#options

should be something like this:

```js
archive.glob('**', {
ignore: ['mydir/**', 'file.txt']
})
```

**Comment by dsgill** [comment]
That worked. Thanks!

**Comment by fwon** [comment]
@ctalkington Can archive.glob work like archive.directory('subdir/', false)?
The second parameter will put its contents at the root of archive, if i use glob, how can i do the same thing?

**Comment by MarkusKonk** [comment]
@fwon In case you're still trying to remove the destination directory, which I also had to do: use the `cwd` option of the glob:

```JavaScript
archive.glob('**/*', {
              cwd: '/the/path/to/the/data/',
              ignore: ['file1', 'file2']
            })
```

**Comment by foch01** [comment]
> @fwon In case you're still trying to remove the destination directory, which I also had to do: use the `cwd` option of the glob:
> 
> ```js
> archive.glob('**/*', {
>               cwd: '/the/path/to/the/data/',
>               ignore: ['file1', 'file2']
>             })
> ```



This answer does not work.

This does not rule out the full path ...

This excludes only files present in subfolder
