### ISSUE TITLE
is there a way to test archive file integrity?

### ISSUE THREAD

**Issue by pantchox** [archiverjs/node-archiver#222]
like with `zip -T` and `7z t` could not find anything about it.

thank you!

**Comment by ctalkington** [comment]
currently there isnt. id be curious what those actually do to see if we could recreate the logic.

**Comment by pantchox** [comment]
https://github.com/quentinrossetti/node-7z/ do it, but its a wrapper around 7z command line, also i was held by issues of file permissions on windows machine.
anyway integrity basically extract the file as specified he should be when extracted and and do a checksum and then deletes it - these are my own assumptions.
Thanks hope i could be in node-archiver it would really be usefull!

**Comment by ctalkington** [comment]
will punt this for time being but if someone wants to put together the legwork on what all this would entail i could be persuaded to explore it more.
