### ISSUE TITLE
archive.glob doesn't exist inside d.ts file

### ISSUE THREAD

**Issue by RPDeshaies-playster** [archiverjs/node-archiver#226]
![image](https://cloud.githubusercontent.com/assets/24959029/24357844/fd67e22c-12cc-11e7-80ce-456ad35d5d49.png)

**Comment by ctalkington** [comment]
whats your environment / usage?

**Comment by ctalkington** [comment]
feel free to tag me or open a new issue if you can provide more details. closing for now.
