### ISSUE TITLE
Excluding root directory

### ISSUE THREAD

**Issue by ctdany86** [archiverjs/node-archiver#229]
Hi,
I am using ArchiverJS to zip a directory for my PhoneGap application but I have not yet managed to achieve what I want to.

I have a folder structured like this: 
```
- www
      - css
      - images
      - scripts
      - config.xml
      - index.html
```

Now what I would like to have is a zip file containing the CONTENT of the www folder but NOT the folder itself.

```
BAD
 - www.zip
   - www
      - css
      - images
      - scripts
      - config.xml
      - index.html
GOOD
 - www.zip
   - css
   - images
   - scripts
   - config.xml
   - index.html
```

The code I have in place is the follow:

```
var archiver = require('archiver');

var output = fs.createWriteStream('./www/www.zip');
var archive = archiver('zip', {
   store: true // Sets the compression method to STORE.
});

output.on('close', function() {
  console.log(archive.pointer() + ' total bytes');
  console.log('archiver has been finalized and the output file descriptor has closed.');
});

archive.on('error', function(err) {
  throw err;
});

archive.pipe(output);
archive.directory('www/');
archive.finalize();
```
I have tried to add something like: archive.directory('www/*'); or archive.directory('www/**'); but it throws an error.

Any other way I can accomplish that? Thanks

**Comment by ctdany86** [comment]
Ok - I'll reply to myself since I managed to do that and I also fell silly now :(

So I have solved the problem with this:
`archive.directory('www','/');

That's it :)

Thanks

**Comment by ctalkington** [comment]
yah, its a common task so the function supports '/' or false to strip it back a level. you can also rename with like `www2/` as the value.

**Comment by RoyXun** [comment]
How to rename the folder `www` in the zip file with a custom name when using glob method then? 
Sometimes I would like to exclude some files in the `www` fold but I can't achieve that with the `directory` method.

**Comment by RoyXun** [comment]
Problem solved! 
I have seen a solution to my problem in #259 and #221 .
```
archive.glob('**', {
  cwd: 'www',
  ignore: ['script/**'],
}, {
  prefix: 'foo'
} )
```

**Comment by dylanbathurst** [comment]
was this removed since this issue had been closed? I'm trying:
```
const output = fs.createWriteStream('./example.zip');
...
archive.directory('dist', '/');
...
```
I'm hoping that the files inside of `dist/` will be at the top level of my zipped file but there is still a directory `example` at the root when I unzip it. I just want the files to be at the root of the zip.

**Comment by IVleafclover** [comment]
@dylanbathurst 
Just use `archive.directory('dist', '/');`

**Comment by buinguyentung** [comment]
> Problem solved! I have seen a solution to my problem in #259 and #221 .
> 
> ```
> archive.glob('**', {
>   cwd: 'www',
>   ignore: ['script/**'],
> }, {
>   prefix: 'foo'
> } )
> ```

Perfect. The prefix ('foo') is also the destination path for archive.glob.
Thank you.
