### ISSUE TITLE
Remove directory structure from archived file.

### ISSUE THREAD

**Issue by Abubakar63** [archiverjs/node-archiver#230]
I have my nodejs code placed at /home/node_app

I have a directory /var/www/abc/css So what I want is to zip css folder as css.zip and placed in /var/www/abc

and when I unzip it, it should become /var/www/abc/css back.

what I currently get when I unzip it is /var/www/abc/var/www/abc/<files>

My code is

var output = fs.createWriteStream('/var/www/abc/css.zip');
    var archive = archiver('zip', {
      store: true // Sets the compression method to STORE.
    });

    output.on('close', function() {
      console.log(archive.pointer() + ' total bytes');
      console.log('archiver has been finalized and the output file descriptor has closed.');
    });

    archive.on('error', function(err) {
      console.log(err);
    });
    archive.pipe(output);
    archive.directory('/var/www/abc/css', '/var/www/abc');
    archive.finalize();

Please let me know where I am wrong.

**Comment by khaledabbas** [comment]
Same problem here

**Comment by khaledabbas** [comment]
this might help : [#156 (comment)](https://github.com/archiverjs/node-archiver/issues/156#issuecomment-135497173)

**Comment by ctalkington** [comment]
`directory('/var/www/abc/css', 'css')` should do what you are looking for.

**Comment by edencorbin** [comment]
Old closed ticket, and I'm sure its well documented,, but I would recommend including this in your example, or even just edit: 

// append files from a directory 
archive.directory('subdir/');

to

// append files from a directory 
archive.directory(__dirname + 'subdir/', 'subdir');

It wasn't clear to me until I read this that was the way to do it, and it seems this would be the most common way people intend to append a directory, IE relative path.

Regardless amazing repo/module, great work!
