### ISSUE TITLE
Filesize ?

### ISSUE THREAD

**Issue by warpdesign** [archiverjs/node-archiver#232]
When generating a file using archiver.finalize() is there a way to get the size of the created file or do I have to get it myself using NodeJS fs methods?

**Comment by andrewpatrickburns** [comment]
You can use `archive.pointer()` to get the amount of bytes emitted by the archiver. Use this when your createFileStream has closed to get the whole file size.

**Comment by ctalkington** [comment]
above answer is current that is the recommended function to use for getting final size.

**Comment by warpdesign** [comment]
Thank you! I used fs methods but will use `archive.pointer()` instead.
