### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by MineDoubleSpace** [archiverjs/node-archiver#233]
I'm trying to create a zip of a large directory of 21GB, which contains small 0.5-1MB image files. 

```
var output = fs.createWriteStream(zip_name);
var archive = archiver('zip', {store: true);

output.on('close', function () {
    return cb(null, 'wrote');
});

archive.on('error', function (err) {
    console.error(err);
});

archive.pipe(output);

// zipFiles is a list of directories and files needs to be zipped. 
async.each(zipFiles, function (zipFile, next) {
    fs.lstat(zipFile, function (err, stats) {
        if (!err) {
            if (stats.isFile()) {
                archive.file(zipFile);
            } else if (stats.isDirectory()) {
                archive.directory(zipFile);
            }
        }
        next();
    });	
}, function () {
    archive.finalize();
});
```

This is the error I'm getting: JavaScript heap out of memory. RAM usage goes up to 4GB and then the program crashes.  Is there a better memory optimized way to do this?

**Comment by ctalkington** [comment]
good question, are you on a 32 bit windows by chance?

**Comment by MineDoubleSpace** [comment]
I was running 64 bit Ubuntu. There were around 4.5 million files on that folder, which is probably why it was running out of RAM. I ended creating a process and running the zip command.

**Comment by ctalkington** [comment]
i wonder if the storing of each entries metadata was the bottleneck there since the amount of files.

**Comment by soyuka** [comment]
Anyway storing entries metadata is useful sometimes (https://github.com/archiverjs/node-archiver/issues/234 for example). Or maybe we can introduce a progress event and remove the in-memory metadata storage.

**Comment by soyuka** [comment]
@MineDoubleSpace could you try the master branch on this matter? https://github.com/archiverjs/node-archiver/commit/d8e324635ea332a037e94e4eb81f9bb8a99b7871 should fix the memory issue.

**Comment by ctalkington** [comment]
v2.0.0 has been published to npm. for those interested in numbers, this is the 50th release to date.
