### ISSUE TITLE
zip.directory() path issues with windows

### ISSUE THREAD

**Issue by zaynv** [archiverjs/node-archiver#235]
I'm having an issue with using `zip.directory` in Windows.

This is the file structure I'm trying to create:

```
.
├── file1.txt
├── file2.txt
└── file3.txt
```

`file2.txt` and `file3.txt` are coming from a directory called `dir`.

Here is the code I have on my server:

```js
const zip = archiver('zip')

zip.append('some text', { name: 'file1.txt' })   
zip.directory('dir/', '.')
zip.finalize()
```

This works fine on Mac. However, using the `'.'` to put everything in the same directory seems to not work on Windows (basically only `file1.txt` makes it into the zip). 

The following, however, DOES work:

```js
const zip = archiver('zip')

zip.append('some text', { name: 'file1.txt' })   
zip.directory('dir/', 'somename')
zip.finalize()
```

However, this gives a folder structure like this:

```
.
├── file1.txt
└── somename
    ├── file2.txt
    └── file3.txt
```

which isn't really what I'm looking for. Is there a way around this? I'm using Node v7.8 btw.

**Comment by zaynv** [comment]
After asking around in the `#node.js` IRC channel, I found that changing

```js
zip.directory('dir/', '.')
```

to

```js
zip.directory('dir/', '../')
```

seems to make the issue fixed.

**Comment by ctalkington** [comment]
ive debated catching a few more of these characters like `.` to the catch for no path prefix because what happens is that `.../` most likely gets normalized to empty but you can always use `false` as well to get the same effect.
