### ISSUE TITLE
Is there a way to pipe a stream directly to Archiver?

### ISSUE THREAD

**Issue by matylla** [archiverjs/node-archiver#237]
What I'm trying to do is download files with `request` and pipe them directly to ZIP archive. For instance:

````js
request("https://website.com/file.jpg").pipe(archiver({
    name: "file.jpg"
}));
````

**Comment by EyMaddis** [comment]
You have to create the zip first and then stream a file entry.
This should work:

```
const zip = archiver('zip')
const stream = request("https://website.com/file.jpg")
zip.entry(stream, { name: 'file.jpg'})
zip.finalize()
```

**Comment by matylla** [comment]
Works like a charm, thanks. The only problem was that `archiver` does not expose `.entry()` method. Had to use `.append()` instead.
