### ISSUE TITLE
Streaming large file into archive is really slow

### ISSUE THREAD

**Issue by newmanw** [archiverjs/node-archiver#238]
I am creating a zip archive and streaming a large xml file into that zip archive.

```
// Setup response type
res.type('application/zip');
res.attachment('file.zip');

// Create archive and passthrough stream
var archive = archiver('zip');
archive.pipe(res);
var passthroughStream = new stream.PassThrough();
archive.append(passthroughStream, { name:'large.xml' });

// Stream a bunch of stuff to the xml file
while (notDone) {
   passthroughStream.write('xml data');
}

passthroughStream.end();
archive.finalize();
```

An example XML file that I am trying to write is around 350MB.  I complete the loop successfully and finalize the archive, however even when that is done the stream is still writing very slowly and for a very long time.

Since I was not sure if I was using a passthrough stream correctly I removed archiver from the test to see what would happen.  I removed archiver (send back XML file, not zip), and piped the passthroughStream to the res.  Writing completes in around the same amount of time, but in this case the stream finishes writing shortly after the call to close().

Let me know if you need more info.  Thanks for the help!

**Comment by soyuka** [comment]
May this be because you have small chunks (those written in the loop)? 

Could you try to:
1. write xml data to fs.createWriteStream()
2 `append` that file to archiver

and check if performances are still low?

**Comment by newmanw** [comment]
@soyuka good idea.  I wasn't able to write to a file easily as the request would timeout.  However I did change the code to write larger chunks of string data to the stream.  Good news is that this 'fixed' the problem.

Assuming that is due to a limitation with writing small chunks to a stream.  Might also be outside the scope of this module.  Thoughts?

**Comment by soyuka** [comment]
Yes, it's related to how streams are working :).

**Comment by miracledev02** [comment]
great
