### ISSUE TITLE
Zipping a folder with ouput zip in the folder will cause recursive that used up all system space

### ISSUE THREAD

**Issue by nabito** [archiverjs/node-archiver#240]
// create a file to stream archive data to. 
    var output = fs.createWriteStream("./dir/foo.zip");
    var archive = archiver(format, {
        store: true // Sets the compression method to STORE. 
    });
     
...
    // pipe archive data to the file 
    archive.pipe(output);

    // append files from a directory 
    archive.directory("./dir");

**Comment by soyuka** [comment]
Obvious no ? You're zipping the zip ^^

**Comment by nabito** [comment]
I shot myself on the foot :)

This is because I'm so used to zip cmd in linux (Info-Zip 3.0); it allows you to do:

in-a-dir> zip -r output.zip * 

so all the contents of that dir is zipped recursively but not including the output zip itself.

May be node-archiver is too powerful for being a stream-based library?

**Comment by soyuka** [comment]
Not really, instead of appending the directory you can achieve the same behavior by using a [glob](https://archiverjs.com/docs/Archiver.html#glob) and ignoring the zip file.

**Comment by nabito** [comment]
Aha, sounds good, thx!
