### ISSUE TITLE
explore promise api

### ISSUE THREAD

**Issue by ctalkington** [archiverjs/node-archiver#242]
by popular request and something ive wanted to try out. main concern was performance but maybe by moving newer node and such thats less of an issue. need to research options. open to suggestions

**Comment by ctalkington** [comment]
closes #207

**Comment by soyuka** [comment]
I think that performances may be improved on memory usage by removing processed entries from `archiver._entries`. Though, I find this array is a usefull when you want to compute progress (see https://github.com/archiverjs/node-archiver/issues/234). 

Btw, not really related but WDYT about adding an event `progress` that would send the total bytes processed? With the `pointer()` it could also give live data about the compression ratio :D.

Lmk your thoughts, I may be able to work on these.

**Comment by ctalkington** [comment]
i do like the idea of a `progress` event over keeping so much in memory. this way someone can decide what to do with the progress data. lets give its own issue #244 for v2.1.0 most likely.

**Comment by ctalkington** [comment]
still need to me, but given we internally handle queuing and have our own chainability, i dont really want to go overkill and lose all that
