### ISSUE TITLE
Full Steam Ahead: v2.0.0

### ISSUE THREAD

**Issue by ctalkington** [archiverjs/node-archiver#243]
this issue summarizes the changes v2.0.0 brings.

1) support for node v4+ only
2) basic symlink support 
3) support for promises on `finalize`
4) removal of `bulk` functionality
5) modernization (promises, code base cleanup etc) over the coming months

Note: v1.3.0 will only receive reasonable bug fixes (until 2017-12-31) and no new features. a separate branch has been created for these maintenance releases.

cc @soyuka

**Comment by abetomo** [comment]
Thank you for the new version!
I want to use symlink support of zip.
When will the next release be around?

**Comment by ctalkington** [comment]
I'm hoping to set some time aside this weekend. there was some movement on a few things when I originally planned to release so didn't want to slow the momentum.

**Comment by ctalkington** [comment]
v2.0.0 has been published to npm. for those interested in numbers, this is the 50th release to date.

**Comment by abetomo** [comment]
congratulations! And thank you!
