### ISSUE TITLE
explore progress event

### ISSUE THREAD

**Issue by ctalkington** [archiverjs/node-archiver#244]
storing all the entries could be axed and reduce memory usage if we used events.

**Comment by ctalkington** [comment]
@soyuka some initial thoughts you might have feedback on:

how would you calculate this? files streamed vs total files? with the total being dynamic based on ability to add more until finalize, concerns about progress being all over the place until you finalize?

**Comment by soyuka** [comment]
By playing with values from #247 and `archiver.pointer()` the end user should be able to compute whatever he needs.

My idea of compression rate was some kind of ratio between `archiver.pointer()` (compressed size in bytes) and `total` (see #247). 

If you want a progression, you need to know the total size of what you're archiving and compute this with `total`. I'd left this task to the end user (who can recursively compute a directory size before archiving for example).

**Comment by ctalkington** [comment]
ah ok i guess this applies more to #245 then? general progress event would just tell you current status? not a true percent or such.

**Comment by soyuka** [comment]
Indeed, and I think it's just enough like this! If someone wants to compute any of the above, he has the current data.

**Comment by ctalkington** [comment]
closed by d8e324635ea332a037e94e4eb81f9bb8a99b7871
