### ISSUE TITLE
explore calculating and exposing compression savings

### ISSUE THREAD

**Issue by ctalkington** [archiverjs/node-archiver#245]

**Comment by soyuka** [comment]
Leave this open for now, I want to add a bunch of examples on how to compute zipping progression. IMO this task should be left to the library user. Thanks to https://github.com/archiverjs/node-archiver/commit/d8e324635ea332a037e94e4eb81f9bb8a99b7871 we have all we need :).

**Comment by ctalkington** [comment]
sounds good.
