### ISSUE TITLE
behavior of on('error')

### ISSUE THREAD

**Issue by DrYSG** [archiverjs/node-archiver#252]
I have hooked up my event processing as shown below to capture the close, entry, and error  events. All works fine until I get errors. I know what the errors are (file not found). I want the error processor to log the error and the work to continue.

What I am seeing is that my done event is never being called if there were missing files. I would rather not add test to see of that the file exists, but rather do the catching of missing files.

How can I get that behavior?

```
        this.stream.on('close', this.done.bind(this))
        this.archive.on('entry', this.update.bind(this))
        this.archive.on('error', this.fail.bind(this))

done() {
        this.count-- // update will increment count
        this.update()
        this.makeLog()
        this.finished = true
    }

   fail(err) {
        this.errors++
        logger.addLog('info', 'Builder.fail(): File Missing Error: %s', err.pathe)
        this.filesMissingList.push(err.path)
        this.filesMissing++
    }
```

**Comment by soyuka** [comment]
You can try the `end` event. Not sure that you can continue on error though.

**Comment by soyuka** [comment]
See #106 it's an open discussion.

**Comment by DrYSG** [comment]
The end event does not occur  either in the presence of errors. Does End have a different semantics than stream.close? I.e. does it fire earlier or later, and when does it fire?

```
        // this.stream.on('close', this.done.bind(this))
        this.archive.on('end', this.completed.bind(this))
``

**Comment by soyuka** [comment]
`end` occurs when there is no more data to process
`close` occurs when the file descriptor has been closed

see https://nodejs.org/api/stream.html

**Comment by DrYSG** [comment]
so end is slightly before close? Any idea what has to be done after all the data has been processed but the file is not yet closed?

**Comment by soyuka** [comment]
Haha no, for this I invite you to read the nodejs stream source code :).

**Comment by ctalkington** [comment]
the time between end and close is likely going to be the time it takes drain and file system io time.

**Comment by DrYSG** [comment]
@ctalkington thank you that is a good piece of info. Maybe stick in in the FAQ?

**Comment by edovino** [comment]
I have the same issue(s) with v2.10 - when an error occurs, no 'end' or 'close' events are sent. (No 'warning's either). I've resorted to using fs.statSync before adding the individual files, but wasn't this supposed to be fixed? Perhaps I have a special combination that the fix doesn't catch?
