### ISSUE TITLE
Small nitpick: Changelog type

### ISSUE THREAD

**Issue by joelgriffith** [archiverjs/node-archiver#262]
I think you have a typo in your changelog:

> change: support for node v0.4+ only. node v0.10 and v0.12 support has been dropped. (#241)

Think you mean `node v4.0+ only`?

**Comment by soyuka** [comment]
Yes, would you mind issuing a PR?

**Comment by ctalkington** [comment]
oh hah, guess im going back in time. dang. fixed.
