### ISSUE TITLE
Getting Queue Closed error , please help urgently 

### ISSUE THREAD

**Issue by nidhiag** [archiverjs/node-archiver#265]
app.post("/downloadCertsZip", function (req, res) {
console.log(req.body);
var hostPath = __dirname +'/certificate/'+req.body.dp_hostname;
var interPath = __dirname +'/certificate/'+req.body.dp_hostname+'/intermediate/';
if (fs.existsSync(hostPath) && fs.existsSync(interPath)){
  fs.readdir(interPath,function(err, interfiles){
   if (err) {
      return console.error(err);
   }
   var fl = interfiles.length;
   console.log("length",fl);
   if(fl >0){
     var certPath = __dirname +'/certificate/'+req.body.dp_hostname+'/certificate/';
     res.type('application/zip');
     res.attachment('file.zip');
     var archive = archiver('zip');
     archive.pipe(res);
     fs.readdir(certPath,function(err, files){
      if (err) {
        return console.error(err);
      }
      archive.append(fs.createReadStream(certPath+files[0]),{name:files[0]})
      });
      interfiles.forEach(function(interfile){
      if(interfile){
      archive.append(fs.createReadStream(interPath+interfile),{name:interfile})
      }
      });
      archive.finalize();
   }
});
}

});

**Comment by nidhiag** [comment]
app.post("/downloadCertsZip", function (req, res) {
console.log(req.body);
var hostPath = __dirname +'/certificate/'+req.body.dp_hostname;
var interPath = __dirname +'/certificate/'+req.body.dp_hostname+'/intermediate/';
if (fs.existsSync(hostPath) && fs.existsSync(interPath)){
  fs.readdir(interPath,function(err, interfiles){
   if (err) {
      return console.error(err);
   }
   var fl = interfiles.length;
   console.log("length",fl);
   if(fl >0){
     var certPath = __dirname +'/certificate/'+req.body.dp_hostname+'/certificate/';
     res.type('application/zip');
     res.attachment('file.zip');
     var archive = archiver('zip');
     archive.pipe(res);
     fs.readdir(certPath,function(err, files){
      if (err) {
        return console.error(err);
      }
      archive.append(fs.createReadStream(certPath+files[0]),{name:files[0]})
      });
      interfiles.forEach(function(interfile){
      if(interfile){
      archive.append(fs.createReadStream(interPath+interfile),{name:interfile})
      }
      });
      archive.finalize();
   }
});
}






});

**Comment by nidhiag** [comment]
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: queue closed
    at Archiver.append (c:\Users\IBM_ADMIN\git\C2CGateway-28\node_modules\archiv
er\lib\core.js:544:24)
    at c:\Users\IBM_ADMIN\git\C2CGateway-28\src\server\server.js:50:15
    at FSReqWrap.oncomplete (fs.js:123:15)

**Comment by soyuka** [comment]
Please take a look at the [express example](https://github.com/archiverjs/node-archiver/blob/master/examples/express.js) and try to fix your code accordingly. 

This error means that you're trying to add files but the archive is already close. My guess is because you're using `archive.append` in an asynchronous call and the `archive` has already been closed when you reach that (`finalize` is called before `append`).

Wrap `fs.readdir` around the whole archive code.

**Comment by nidhiag** [comment]
Hi i am struggling with it since 2 daz. I am doing same as in example. How to wrap fs,readdir around the archive code? Please help.

**Comment by nidhiag** [comment]
@soyuka  please help me to get it working. I have checked all the post on this .

**Comment by nidhiag** [comment]
@soyuka  i tried adding timeout also , but no luck , i was suspecting that finalize is getting called before.

**Comment by soyuka** [comment]
```javascript
app.post("/downloadCertsZip", function (req, res) {

  var hostPath = __dirname +'/certificate/'+req.body.dp_hostname;
  var interPath = __dirname +'/certificate/'+req.body.dp_hostname+'/intermediate/';

  if (fs.existsSync(hostPath) && fs.existsSync(interPath)){
    fs.readdir(interPath,function(err, interfiles){
      if (err) {
        //this is not how you should handle errors, you need to give a response to the user.....
        return console.error(err);
      }
        
      var fl = interfiles.length;
      console.log("length",fl);

      if(fl >0){
        var certPath = __dirname +'/certificate/'+req.body.dp_hostname+'/certificate/';
        res.type('application/zip');
        res.attachment('file.zip');
        var archive = archiver('zip');
        archive.pipe(res);
        
        fs.readdir(certPath,function(err, files){
          if (err) {
            //this is not how you should handle errors...
            return console.error(err);
          }

          archive.append(fs.createReadStream(certPath+files[0]),{name:files[0]})

          interfiles.forEach(function(interfile){
            if(interfile){
              archive.append(fs.createReadStream(interPath+interfile),{name:interfile})
            }
          });

          archive.finalize();
        });
      }

      // nothing here again?
    });
  }
  //nothing happens when files does not exist? You need to close the request...

});

```

You've a lot too learn... Don't rush and try to understand before coding. The above code will work because I'm calling `archive.finalize` in the last asynchronous code. However, this is bad code:

1. you're error handling is bad, if you don't send data back to the client he will wait for the request to end indefinitely
2. nothing is sent to the client when one of your condition isn't matched
3. the second `readdir` you take `files[0]` and it's a bad assumption (run the code on osx you'll probably get `.DS_Store` instead of your wanted file.
4. `fs.existsSync` is deprecated since a long time now, you should not use it
5. When joining paths, my advise is to use the [path](https://nodejs.org/api/path.html) api
etc.

Good luck and please try to understand what you do.

**Comment by nidhiag** [comment]
@soyuka  Thank you for your quick support!
Archive is getting written now : Archive wrote 4644 bytes
But in Response i am not getting that file. Response { type: "basic", url: "https://9.78.205.111:8800/downloadC…", redirected: false, status: 200, ok: true, statusText: "OK", headers: Headers, bodyUsed: false }

**Comment by nidhiag** [comment]
@soyuka Please help me getting the response in client , i am getting the "Archive wrote 4644 bytes" on Archiver.on('end') , which means that it has been piped the data to response. But on client side i am not seeing anything in response.
