### ISSUE TITLE
Archive piping data to response , but on client side response is empty . How to get data from response .

### ISSUE THREAD

**Issue by nidhiag** [archiverjs/node-archiver#266]
Response { type: "basic", url: "https://9.78.205.111:8800/downloadC…", redirected: false, status: 200, ok: true, statusText: "OK", headers: Headers, bodyUsed: false }

in Server code : 
res.writeHead(200, {
         'Content-Type': 'application/zip',
         'Content-disposition': 'attachment; filename=myFile.zip'
     });
var archive = archiver('zip');

output.on('close', function() {
console.log(archive.pointer() + ' total bytes');
console.log('archiver has been finalized and the output file descriptor has closed.');
});

     archive.on('end', function() {
  console.log('Archive wrote %d bytes', archive.pointer());
}); 
Archiver code.......

**Comment by soyuka** [comment]
Please use markdown to format your issues. Also, this is a bug tracker not meant for support (try stackoverflow). I already gave you some informations in the other issue that should be enough.

To send the zip file I'd recommend to use expressjs (see the [express example](https://github.com/archiverjs/node-archiver/blob/master/examples/express.js)).
