### ISSUE TITLE
Archiver Sometimes Incorrectly Skips Directories On Windows When Using directory Method

### ISSUE THREAD

**Issue by pspaulding** [archiverjs/node-archiver#267]
The root problem is with node https://github.com/nodejs/node/issues/12115 and the walkdir library that archiver depends on.  I've filed an issue on walkdir https://github.com/soldair/node-walkdir/issues/31 .  Until walkdir is updated, I would consider the `directory` method to be unreliable.  I was able to work around the issue in my case by using the `glob` method instead of `directory`.

This skipped directories and files: `archive.directory('foo/')`

This works: `archive.glob('foo/**/*.*')`

**Comment by ctalkington** [comment]
interesting bug. lets give that module dev a little more time to implement a fix. otherwise we will look at other modules  or maybe just create a wrapped that reuses glob.

**Comment by soldair** [comment]
Ill take a loom at the issue again tonight. Thanks for the ping

**Comment by ctalkington** [comment]
im working on a solution to reuse glob, should have a PR to further test in the next week or so

**Comment by soldair** [comment]
added suppport for track_inodes:false option to walkdir@0.0.12 if you want to try that. should use max_depth with it just in case. glob is also a really great choice. :100:

**Comment by ctalkington** [comment]
this should have been resolved in the most recent release. feel free to open a new issue if you feel otherwise.
