### ISSUE TITLE
Firefox : getting the large data in firefox than actual sreamed bytes. 

### ISSUE THREAD

**Issue by nidhiag** [archiverjs/node-archiver#268]
Hi , 
In Firefox i am getting the bytes larger than actual bytes sent. In chrome i am able to download proper zip. 
Code : 
              var promise = res.blob(); // res is the Response containing the streamed data .
               promise.then(function(result){               
                fileDownload(result,"Certificates.zip");//result is Blob object in Chrome with actual bytes sent(4644)          
              })                                                                // result is binaryArray , when converting in blob, size is   much greater than actual bytes sent.

**Comment by nidhiag** [comment]
![streamsizediffersinffandchrome](https://user-images.githubusercontent.com/22441670/28859761-ea7d291a-7776-11e7-974a-60941a9fdbc7.png)

**Comment by ctalkington** [comment]
i believe this is an issue with the library being used to stream or content type. not sure the specifics of the implementation to really dig deeper.
