### ISSUE TITLE
Is documentation up to date?

### ISSUE THREAD

**Issue by Nargonath** [archiverjs/node-archiver#269]
The documentation like 'Quick Start' seems to be off. It mentions the `close` event but it doesn't appear in the API documentation not it has been triggered in my app.

I'll be happy to make a PR to update the doc but I just wanted to make sure of it.

By the way I used the event `end` instead.

**Comment by soyuka** [comment]
Yes use the `end` event instead. `close` might not be present when there is no file descriptor involved https://github.com/archiverjs/node-archiver/issues/252#issuecomment-309818614

Feel free to send a patch to update the documentation!

**Comment by Nargonath** [comment]
Alright thank you, I'll send a PR when possible (I'm on vacation soon).

**Comment by ctalkington** [comment]
i think we can add a note somewhere in the docs; feel free to suggest via PR or once i work through a few remaining tasks for the next release, Ill try to work something in

**Comment by Nargonath** [comment]
Thanks for your answer. I haven't been able to work on it so far. Got soaked up by work and personal after the vacations. If I haven't done anything by the time you are available to make it, feel free to add that note. Thanks for your time again. :+1:
