### ISSUE TITLE
Finalize Callback / Pointer Error

### ISSUE THREAD

**Issue by Vardemont** [archiverjs/node-archiver#278]
Hello there, 

I have some questions and problems. I couldn't see that in documents so it might be not fully implemented yet but finalize function actually returns a promise. When I used it, I realised that sometimes it doesn't get fired. After some test, I can say that if the total size of the files bigger than 2-3 mb, it doesn't get fired. When total size of the files less than that, there is no problem. (By the way I use append function with buffer array. ) I try to pipe an archive to express server response. Also realised that  this piping starts long before finalize callback. So is it piping all the files without keeping them in the memory ?  That can be good thing because using standard memory size for every operation can be dramatically drops required ram amount for my server.  It also explains why finalize doesn't get fired without piping it. But if it is like that, I have another problem. If I want to show download percentage on browser I need to provide content size in header. But it seems impossible in that case.  If I provide content size without waiting the callback by using archive.pointer(),  it is not correct. For example: My archive suppose to be bigger than 2 mb but it says around 1mb. So browser stops the download at 1 mb and archive becomes broken. My approach might be totally wrong. I am just thinking and asking. May you guide me to right direction ? 

Thanks a lot for your time :)

**Comment by soyuka** [comment]
pointer is the compressed size, it'll differ from the total size from the original files. Please check out https://github.com/archiverjs/node-archiver/blob/master/examples/progress.js

**Comment by Vardemont** [comment]
I know its the compressed size and it is not equal to total file size but it is still not correct if you dont wait for finalize callback.

**Comment by soyuka** [comment]
Because it's a stream and that the bytes are computed while it's being compressed. As you said, the size will be known only at the end.

If you use something like [send](https://www.npmjs.com/package/send) you should be able to provide a download without fixed content-size. 

If you need the proper size, you'll have to first archive, then retrieve the size.

**Comment by Vardemont** [comment]
Well I was asking it to be able to show download percentage on browser. I will try to find another way. Even if I can't, using less ram is better than showing download progress I think. Thanks for your time by the way.

**Comment by soyuka** [comment]
Yeah I struggled on this one too once. The only thing you could do is to work with what you know for sure, meaning using the uncompressed size as total. It'll just jump from `~90%` to `! 100%` at the end :p.

Good luck! Cheers.
