### ISSUE TITLE
Archived files have different modified and created date than the originals

### ISSUE THREAD

**Issue by andrisarkameru** [archiverjs/node-archiver#279]
Files in the .zip archive have different modified and created dates than the originals.

The difference in my case is exactly 3hours. 
For example I have a new file that is modified 12:00 as shown in windows file details. after running the zip package and extracting the file - same properties show creation and modification time of 9:00.

I am in a GMT+2 time zone, so the 3h difference is deffinately a UTC time (plus 1h for summer time diff)
Windows10, node 6.11.2, archiver 2.0.3

**Comment by ctalkington** [comment]
so with zip there is no concept of timezone. archiver is potentially getting back a UTC time from fs.stat which is why you see this. we at one point tried to force local timezones in another part of the code but i think we came back not altering the timezone at all.

**Comment by YSHIDM** [comment]
+1
