### ISSUE TITLE
Problem creating entry for directory

### ISSUE THREAD

**Issue by newmanw** [archiverjs/node-archiver#280]
I apologize as I realize I a reference a very old release, but I have just gotten around to updating and I am having problems.

From release 0.14.0 using the bulk function:

`archive.bulk([{src: ['**'], dest: 'one/two', expand: true, cwd: '/tmp/stuff'}]);
`

I would get a directory entry for 'one/two' in the archive:

```
$ unzip -vl test.zip 
Archive:  test.zip
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
       0  Stored        0   0% 09-05-2017 15:03 00000000  one/two/
   15784  Defl:N    15789   0% 08-04-2017 15:58 4d62150a  one/two/other/foo.png
   10284  Defl:N    10289   0% 08-03-2017 16:47 38ba62d5  one/two/bar.png
--------          -------  ---                            -------
```

I am having problem replicating that with directory or glob:

```
archive.glob('**/*', {cwd: '/tmp/stuff'}, {name: 'two', prefix: 'one'});
archive.directory('/tmp/stuff', 'two', {prefix: 'one'});
```

Neither of these will create a /one/two entry in the zip.  Is there a way with the current version to add this directory entry?

**Comment by ctalkington** [comment]
ok so with glob when you use `cwd` its going to force the name to the relative name since data there refers to individual file data thats then extended. you should be able to use `prefix: 'one/two'` as i dont think we block multiple levels since its purely prefix added to the name and the archive tools are responsible for mapping it out visually to directories.

**Comment by newmanw** [comment]
@ctalkington can you give an example?

I have tried:
`archive.directory('/tmp/stuff', 'one', {prefix: 'one/two'});
`
However this does not create a 'Stored one/two' entry in the archive.
