### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by bpcw** [archiverjs/node-archiver#281]
Environment: 
- node v6.11.3
- Linux (ubuntu 16.04.3 LTS, kernel 4.10.0-35)

Hi,
I wrote a simple node app to reproduce what we are facing in a cloud foundry environment. We are zipping a directory (test2 in the code sample) with about 4500 files (almost exclusively text) distributed in many subfolders. Total size is about 50MB. We use the .glob() function since we also want to exclude certain files from being zipped into the resulting archive, but a similar behavior could be observed when using .directory()

When running the following app, using ```node``` with ```--expose-gc``` option:
```
"use strict";

let path = require("path");
let archiver = require("archiver");
let fs = require("fs");

console.log(process.memoryUsage());

let output = fs.createWriteStream(__dirname + "/example.zip");

let archive = archiver("zip", {
    zlib: { level: 9 }
});

archive.pipe(output);

output.on("close", function () {
    console.log(archive.pointer() + ' total bytes');

    console.log(process.memoryUsage());
    global.gc();
    process.nextTick(function () {
        console.log(process.memoryUsage());
    });

    setTimeout(function () {
        console.log(process.memoryUsage());
    }, 5000);
});

archive.glob("**/*", {
    cwd: "./test2"
}, {});

archive.finalize();
```

The output printed  is as follows:

```
{ rss: 33296384,
  heapTotal: 14811136,
  heapUsed: 9375944,
  external: 83823 }
10409753 total bytes
{ rss: 161857536,
  heapTotal: 85094400,
  heapUsed: 47894592,
  external: 2025148 }
{ rss: 124391424,
  heapTotal: 56705024,
  heapUsed: 11572280,
  external: 124604 }
{ rss: 124391424,
  heapTotal: 56705024,
  heapUsed: 11608624,
  external: 124604 }
```

The whole process uses about 162 MB for zipping up 50 MB worth of files into a ~10 MB archive (does this sound right?), but what is worse, RSS decreases only to 124 MB upon completion, compared to the about 33 MB we started out with. 
In the CF server environment, this leads to RSS constantly increasing and eventually crashing the instance.

Could you please comment on this.

Thank you very much

**Comment by soyuka** [comment]
https://github.com/archiverjs/node-archiver/issues/233
https://github.com/archiverjs/node-archiver/issues/81

I need to study this more in-depth. May you try without glob (should not make a big difference but just in case)?

What'd be also interesting is to have memory usage `on('progress')` (with nb files written).

**Comment by bpcw** [comment]
Hi soyuka,

thanks for your reply. As I stated in my first post, we also used .directory() instead of .glob() and see the same memory behavior.

As for the progress event with memory information, please have a look into the attachment. This time, we started with rss 38 MB and ended up with 136 MB after finalizing and gc().

[packlog.zip.tar.gz](https://github.com/archiverjs/node-archiver/files/1322023/packlog.zip.tar.gz)

**Comment by bpcw** [comment]
It might be of interest that other modules for handling zip files, especially for reading (which archiver unfortunately doesn't do ;-)), have similar memory footprints and gc behavior for the zip extraction process.
Could this indicate that the observed problems have a root cause somewhere deeper in the stack, e. g. with node streams and zlib?

**Comment by soyuka** [comment]
Maybe @bpcw, this module should not use much memory except the one necessary to open streams (it's done in a queue, metadata are not kept in-memory since last version see quoted issues)

**Comment by hoangleanhtu** [comment]
Hi,

Is there any update on this?
We are working on a feature that requires using low memory.
So the conclusion is very useful for us.

Thank you very much.

**Comment by ctalkington** [comment]
this really shouldnt be as much of an issue anymore with efforts made over the past few releases. feel free to open a new issues with details if you run into issues.
