### ISSUE TITLE
archive success callback function

### ISSUE THREAD

**Issue by Myqilixiang** [archiverjs/node-archiver#282]
Is there any callback function to use when a archve operation is finished

**Comment by soyuka** [comment]
you can use a promise:

```
archiver.finalize()
.then(function() {})
```

**Comment by Myqilixiang** [comment]
got it, thank you very much,by the way i found the listener archiver.on('close',calc()) is also a good way to solve the problem

**Comment by soyuka** [comment]
You're welcome! Have a good day!

**Comment by BharathKumarRavichandran** [comment]
I did something like this. But the promise is undefined. I'm using archiver inside a function which archives and returns promise or responses. Is there anything, that I'm doing wrong?
```
let responsePromise = await archive.finalize();
```
