### ISSUE TITLE
zip at level 0 generates corrupted file

### ISSUE THREAD

**Issue by pablodenadai** [archiverjs/node-archiver#285]
Fresh install.
Node v6.5.0

```
    const archive = archiver( 'zip', {
        store: true // Sets the compression method to STORE
        level: 0 // No compression
    } );
```

![image](https://user-images.githubusercontent.com/3250667/31365741-74368ec0-adc9-11e7-8122-ceaa25902233.png)

Seems to be related to having `store` set to `true`.

**Comment by pablodenadai** [comment]
The issue seems to have been introduced with the latest version of https://github.com/archiverjs/node-compress-commons

**Comment by ctalkington** [comment]
@pablodenadai this was a bug introduced in compress-commons due trying to enhance compatibility with archivers that don't like data descriptors when entries are STORE (ie java). ive reverted and if you clear your node_modules / npm cache, this should be fixed.
