### ISSUE TITLE
Release an update to npm?

### ISSUE THREAD

**Issue by natomato** [archiverjs/node-archiver#287]
In working with Archiver I noticed the documentation references changes to `.directory` that are not released in latest npm module v2.0.3
The latest release still uses `function onWalkPath(filepath, stats)`

When do you plan to release another version?

I want to use the newer glob options described in the docs to create a zip archive that excludes the node_modules directory.

**Comment by natomato** [comment]
awesome! thanks for the version bump

**Comment by ctalkington** [comment]
no problem, i was just trying to give it time to sit for review before i merged since a change in a related library last week didn't work so well.
