### ISSUE TITLE
archive.finalize - Bluebird - Uncaught TypeError: Cannot read property 'objectMode' of undefined

### ISSUE THREAD

**Issue by bfle** [archiverjs/node-archiver#288]
Hi. I'm having an issue and haven't been able to find a way to make this work.

I am using Bluebird to orchestrate my processing.             

Main main routine looks like this:
...
Bluebird.resolve()
                .bind(that)
                .then(module.downloadFiles)
                .then(module.appendFilesToArchive)
                .then(function(result) {
                    var buffer = result.output.toBuffer();
                })
...

Inside of the appendFilesToArchive, it looks like this:
...
return Bluebird.map(result, function(image, index) {
                log.log('ZIPFILE - Appending buffer to archive');
                promises.push(archive.append(image.buffer, {name: uuidv4() + '.jpg'}));
    })
    .then(function() {
        return archive.finalize();
    })
...

I've rewritten this code a number of times, but always end up back with an error stating:
  "Uncaught TypeError: Cannot read property 'objectMode' of undefined"

Thanks!!

**Comment by bfle** [comment]
I should also mention one more thing. When running my code directly it works fine and generates the archive file. I only get this ObjectMode error when running from my mocha/chai unit tests.

**Comment by bfle** [comment]
Just for fun, I pulled down the bf fork that contains addFile and snagged the sample code and modified it a little bit into my Bluebird chain. My test seems to just hang on the addFile line and never returns. I'm not sure if it's related, but thought I'd throw out as much info as possible. I'm a bit of a noob when it comes up Node.js, so I'm hoping this is something silly.

    archive.pipe(output);

    var index = 0;
    async.forEachSeries(result, function(file, next) {
        index++;
        archive.addFile(file.buffer, {name: uuidv4() + '.jpg'}, function() {
              next();
         });
      }, function(err) {
        archive.finalize(function(written) {
          return { someresult };
        });
      });

**Comment by ctalkington** [comment]
im not familiar with bluebird but finalize is the only method that returns a promise so if its using the append calls somehow then you are just going to get back the archiver object each time.

**Comment by izure1** [comment]
It seems to be a problem with require.cache.
In my case, the above problem occurred when I deleted the cache stored in require.cache.

**Comment by soyuka** [comment]
I'm closing this because:
1. bluebird is not used here
2. as said, `finalize` is the only method returning a promise (`append` isn't one)
3. no require hacks in this library
