### ISSUE TITLE
Getting the list of files that have been added into the archive?

### ISSUE THREAD

**Issue by nico-onmap** [archiverjs/node-archiver#289]
I am adding lots of files using `archive.directory()` and would need to keep track of the files that have been added (including their path inside the archive): is there an easy way to get the list of files that have been added into the archive before calling `finalize()`?

**Comment by ctalkington** [comment]
we don't keep track of entry meta for performance/memory issues but you can use the `entry` event to build such a list.

https://archiverjs.com/docs/Archiver.html#event:entry
