### ISSUE TITLE
It's possible to add twice the same file

### ISSUE THREAD

**Issue by warpdesign** [archiverjs/node-archiver#291]
Typing the following code

```js
archive.append(fs.createReadStream('./video.mp4'), {
    name: 'videos/video.mp4'
});

archive.append(fs.createReadStream('./video.mp4'), {
    name: 'videos//video.mp4'
});
```

Will add the same file twice to the archive. While this technically works and most unarchivers will simply ask to replace the file that was first extracted, some online tools which take zip files as input will fail with an error.

Suggestion 1: Throw an error when path already exists
Suggestion 2: Replace the already added file by the new one

**Comment by ctalkington** [comment]
since its streaming #2 isnt really possible and #1 would be a bit more resource intensive as you would have to track more but we might have that data already so ill have to look into it further. thanks for the thoughts.

**Comment by ewindisch** [comment]
Different archive formats might handle this differently, but this is definitely an expected behavior of tar, and something I've intentionally done before!
