### ISSUE TITLE
time it take to archive

### ISSUE THREAD

**Issue by kalima26** [archiverjs/node-archiver#292]
hi,
this line take time ( big archive):
            archive.finalize();

i want to follow to archiving execution of my directories, same thing like a progress bar for the archiving operation.

**Comment by soyuka** [comment]
Sure thing, take a look [here](https://github.com/archiverjs/node-archiver/blob/master/examples/progress.js)

**Comment by kalima26** [comment]
Thanks a lot

**Comment by soyuka** [comment]
You're welcome.
