### ISSUE TITLE
How to apply multiple globs?

### ISSUE THREAD

**Issue by NemoAlex** [archiverjs/node-archiver#299]
Since glob is supported, is it possible to apply multiple globs? 

e.g.

```
[ '**/*',
  '!**/node_modules',
  '!**/node_modules/**',
  '!**/*.log',
  '!**/*.log/**',
  '!**/dist',
  '!**/dist/**' ]
```

**Comment by NemoAlex** [comment]
Finally I use [globby](https://github.com/sindresorhus/globby) to solve this:

```
  var Path = require('path')
  var globby = require('globby')
  globby(globs).then(paths => {
    paths.forEach(path => {
      archive.file(path, {
        name: Path.relative(process.cwd(), path)
      })
    })
    archive.finalize()
  })
```

It would be vary handy if node-archiver could use globby.

**Comment by soyuka** [comment]
https://github.com/archiverjs/node-archiver/blob/0bc4872daf94055ba3fafd958d6769711fa39652/lib/core.js#L744

node archiver uses [`glob`](https://www.npmjs.com/package/glob) which doesn't support arrays AFAIR.

**Comment by ctalkington** [comment]
I have considered implementing globby in the past. Feel free to open a ticket if you would like to see that happen.
