### ISSUE TITLE
symlinks broken in certain scenarios in 2.1.0

### ISSUE THREAD

**Issue by Autre31415** [archiverjs/node-archiver#301]
When zipping an Electron app for macOS generated with [Electron-Packager](https://github.com/electron-userland/electron-packager) there are many symlinks to take into consideration. In the current 2.1.0 release many of them are following incorrect paths which causes these apps to fail.

Example ls output:

Correct:
```
Electron Framework -> Versions/Current/Electron Framework
Libraries -> Versions/Current/Libraries
Resources -> Versions/Current/Resources
```

Broken (2.1.0 only):
```
Electron Framework -> ../../../../../../Versions/Current/Electron Framework
Libraries -> ../../../../../../Versions/Current/Libraries
Resources -> ../../../../../../Versions/Current/Resources
```

I did some testing and discovered that this bug is actually fixed in [this commit](https://github.com/archiverjs/node-archiver/commit/0bc4872daf94055ba3fafd958d6769711fa39652#diff-f265d6a6b6b64d4d096fddcf7d620a76).

I propose pushing a new build (2.1.1) so that this fix can go live.

**Comment by akshetpandey** [comment]
+1 to release 2.1.1, will help fix https://github.com/firebase/firebase-tools/issues/586

**Comment by Autre31415** [comment]
@akshetpandey My solution for the time being was to revert to v2.0.3 which doesn't have this issue.

**Comment by akshetpandey** [comment]
Thanks for the info @Autre31415

**Comment by ctalkington** [comment]
2.1.1 has been pushed out. sorry for the delay, thought id have time to push out a few other items with it.
