### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by Alan-Gomes** [archiverjs/node-archiver#302]
Using archiver to compress (with tar or zip) a folder with more than 20gb of content, I get the following error:

Code: https://pastebin.com/FDDbQ7RB

Error:
`
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/root/.nvm/versions/node/v8.9.3/bin/node]
 2: 0x121a7ac [/root/.nvm/versions/node/v8.9.3/bin/node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [/root/.nvm/versions/node/v8.9.3/bin/node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/root/.nvm/versions/node/v8.9.3/bin/node]
 5: v8::internal::Factory::NewInternalizedStringImpl(v8::internal::Handle<v8::internal::String>, int, unsigned int) [/root/.nvm/versions/node/v8.9.3/bin/node]
 6: v8::internal::StringTable::LookupString(v8::internal::Isolate*, v8::internal::Handle<v8::internal::String>) [/root/.nvm/versions/node/v8.9.3/bin/node]
 7: 0x10d489e [/root/.nvm/versions/node/v8.9.3/bin/node]
 8: v8::internal::Runtime_KeyedGetProperty(int, v8::internal::Object**, v8::internal::Isolate*) [/root/.nvm/versions/node/v8.9.3/bin/node]
`

Stack trace:
`
<--- Last few GCs --->

[12013:0x21d72e0]   336010 ms: Mark-sweep 1404.6 (1459.3) -> 1404.6 (1459.3) MB, 1072.0 / 1.3 ms  allocation failure GC in old space requested
[12013:0x21d72e0]   337068 ms: Mark-sweep 1404.6 (1459.3) -> 1404.6 (1436.8) MB, 1057.9 / 0.9 ms  last resort GC in old space requested
[12013:0x21d72e0]   338141 ms: Mark-sweep 1404.6 (1436.8) -> 1404.6 (1436.8) MB, 1072.2 / 1.1 ms  last resort GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x3c2d50fa5ee1 <JSObject>
    1: inflight [/home/backupjs/daemon/node_modules/inflight/inflight.js:~7] [pc=0xb4dbbdd9b9b](this=0xc2e4150be31 <JSGlobal Object>,key=0x1dcb535a131 <String[103]\: readdir\x00/home/servidores/craftlife/login/world/playerdata/a690dec1-309f-3aba-826e-dcfbd3cb719f.dat\x00true>,cb=0x1dcb535a0e9 <JSFunction (sfi = 0xc2e41502fe1)>)
    2: wrapper [/home/backupjs/daemon/node_modules/wrappy/wrappy.js:...
`

**Comment by rstortelder** [comment]
I am also experiencing a lot of memory usage using archiver with large files. Is there a solution to this?

**Comment by ctalkington** [comment]
are you streaming the files? or using buffers from other source? also are you on the latest version 2.1.x?

**Comment by rstortelder** [comment]
Our project currently is moving away from writing to archives. Memory issues occurred while using streams to write files to the archive. We used the latest version (2.1.x).

**Comment by soichih** [comment]
Same here. I had to reduce the use cases for node-archive due to its serious memory leak issue. I am creating .tar with several ssh2/sftp streams and writing out to another steam (expess / response). node-archive will buffer the entire contents from sftp in memory before start streaming it to express, but after it streams out, it leaves all memory allocated in tact.. so eventually our node process will run out of memory.

**Comment by ctalkington** [comment]
I would be interested in seeing memory allocation issues in more detail. We are mostly using built in streams which should auto garbage collect as far as I'm aware.
