### ISSUE TITLE
Zipping kicks my CPU to 100%

### ISSUE THREAD

**Issue by switz** [archiverjs/node-archiver#305]
Is there anyway to limit the CPU usage or slow down the archiving process? Time/speed is not such a major issue but choking my CPU is.

**Comment by Bnaya** [comment]
archiver supports passing stream to append,
You will pass stream that streaming data slower, your CPU will be less busy

**Comment by ctalkington** [comment]
high amount of compression can usually equate to higher cpu usage. you could also look at adjusting the zlib compression level, though 1 is used by default (for best speed). otherwise make sure you are using streamed data sources. 

you could try without compression:
```js
archiver('zip', { store: true })
```
