### ISSUE TITLE
How can i tell if operation is over? `end` or `close`  events? or maybe the promise of finalize?

### ISSUE THREAD

**Issue by Bnaya** [archiverjs/node-archiver#309]
How can i tell if operation is over? `end` or `close`  events? or maybe the promise of finalize?

**Comment by Adidi** [comment]
the finish event emit after the archive is done

**Comment by Bnaya** [comment]
@Adidi i don't see this event in the docs im afraid

**Comment by markus-wi** [comment]
Worked for me. This should definitely be added to the docs

**Comment by Adidi** [comment]
@Bnaya The `finish` event belongs to the writeable stream not to the `archiverjs` itself:
its in the docs of node:
https://nodejs.org/api/stream.html#stream_event_finish
`archiverjs` definitely need to add it: here is a working example:
```
const archiver = require('archiver');
const path = require('path');
const fs = require('fs');

const zipFile = path.resolve(__dirname,'somefile.zip');
const output = fs.createWriteStream(zipFile);

const archive = archiver('zip', {
    zlib: { level: 9 } 
});

archive.pipe(output);
archive.file(path.resolve(__dirname,'file.txt'));

output.on('finish', () => {
    console.log('completely done!');
});

archive.finalize();
```

**Comment by ctalkington** [comment]
there are a few references that show/note/elude to this in documentation. though i think the point that archiver is a stream and you should be monitoring the fs/http/etc stream for true completion may be missed and could be better documented in the jsdoc that generates the docs.

the finish event on archiver just means that it has finished receiving data, not emitting it. only the next link the chain (ie fs) would know if its been written to disk.

https://archiverjs.com/docs/#quick-start
https://archiverjs.com/docs/Archiver.html#finalize

```The end, close or finish events on the destination stream may fire right after calling this method so you should set listeners beforehand to properly detect stream completion.```
