### ISSUE TITLE
Pass a parameter to archive.on('finish',...)

### ISSUE THREAD

**Issue by axi92** [archiverjs/node-archiver#310]
Is there a way to pass a parameter to the 'finish'?
I would need the filename/path but it is not in the "archive"...
```
archive.on('finish', function() {
	console.log('archiv' + JSON.stringify(archive) );
	console.log(archive.pointer() + ' total bytes');
});
```

**Comment by ctalkington** [comment]
archiver isnt tied to the filesystem (you can stream it in memory, to s3, and anything that really accepts streams as an input) so usually you would listen to `end` or `close` of the fs stream and maintain the information such as file name separately.
