### ISSUE TITLE
npm link packages in node_modules folder are not zipped using glob

### ISSUE THREAD

**Issue by ChemaMX** [archiverjs/node-archiver#311]
if I use glob:
    zipArchive.glob('**/*', {
        cwd: srcFolder,
        ignore: ['./*.json', './*.njsproj', 'obj/**', 'bin/**', 'tests/**', 'publish.js'],
        expand: true
    }, {})

all my npm link modules are not copied. It used to work fine when using .bulk before it was deprecated.

**Comment by ChemaMX** [comment]
I actually found how to solve this. by adding **_follow: true_** to the glob, it will go ahead and zip the linked packages (folders). e.g.
```
zipArchive.glob('**/*', 
            {
                cwd: source,
                ignore: ignore,
                nodir: true,
                dot: true,
                follow: true
            }
        )
```

**Comment by ctalkington** [comment]
@ChemaMX glad you found that, i was wondering if that would help here but hadn't had time to test it yet

**Comment by justinmchase** [comment]
I just want to add a piece of extra info in case anyone else lands here; the `nodir: true` is important. Without it, it _will_ follow the symlinks, but before it does that it will create a symlink entry in the zip file and will essentially fail to copy the sub files in the symlink dir.
