### ISSUE TITLE
on end being called too soon?

### ISSUE THREAD

**Issue by borie88** [archiverjs/node-archiver#313]
After finalize is called and on 'end' fires, I send the zip file as an attachment to the client. Each zip archive was coming back as corrupt with only the first few files actually finished being inserted, but when I look in the tmp folder on the server, the zip was done. I had to add a 1500ms timeout after end fires before sending the file and it works fine, even with 300mb archives. What could be the cause for this?

**Comment by vista2001** [comment]
I got the same problem with you.Have you solved the problem?
