### ISSUE TITLE
nodejs使用node-archiver 压缩后 不能解压文件 提示不可预料的压缩文件末端

### ISSUE THREAD

**Issue by siburuxue** [archiverjs/node-archiver#314]
我希望将xxx.tgz.tar文件压缩到zip压缩包中，压缩后 不能解压文件 提示不可预料的压缩文件末端 
但是同样的压缩的代码压缩js文件就正常解压
 var output = fs.createWriteStream(path);
 var archive = archiver('zip');
 archive.pipe(output);
 rows.forEach(function (v,k) {
         archive.file(v.path, { name:v.name});
 });
 archive.finalize();
以上是我的代码

**Comment by luqingxuan** [comment]
我也碰到了这个问题，请问如何解决的呢？
