### ISSUE TITLE
Archiver + s3 download example?

### ISSUE THREAD

**Issue by alexminnaar** [archiverjs/node-archiver#316]
I am new to Node and I am trying to download all of the files (images) from a s3 folder, then zip them with archiver and return this zip file to the client using the express framework.  I found the example of [using archiver in the express framework](https://github.com/archiverjs/node-archiver/blob/master/examples/express.js) but I cannot find an example of using archiver to zip the contents of an s3 folder.  Is this something archiver can do and if so can someone point me to an example of this? Thanks

**Comment by ctalkington** [comment]
i think ive seen an example or two in a few tickets in the past but nothing fully documented. it should mostly consist of using aws module to loop over the s3 contents and using streams to pass data to archiver.

**Comment by vladbalan** [comment]
Hi @ctalkington. I apologize if this has been discussed already. I'm trying to understand how archiver works. In the example above, are the `objectSrc`s stored in RAM one after the other and only sent to disk when they're all `archive.append()`ed? Let's say if my S3 folder has 10GB worth of files will these 10BG get stored into RAM before writing the archive to disk or is there some optimization going on under the hood?

**Comment by Noob7** [comment]
I did the exact same thing but anythig over 4 files of 40mb each start getting corrupted :( 
var fs = require('fs');
var stream =require('stream');
var archiver = require('archiver');
const aws = require('aws-sdk');
var async = require('async');
const path = require('path');
const bucket = 'testbucket-download'

const s3 = new aws.S3();
exports.handler = (event, context, callback) => {
 let urls = [];   
 var params = {
    Bucket: bucket
   };
   s3.listObjects(params, function(err, data) {
     if (err) {
         console.log("error",err);
        return callback(err) // an error occurred
     }
     else {
        urls = data.Contents.map(function(obj){
         let url = obj.Key;
         if(url[url.length - 1]==='/'){
             return
         }
         return url;
        });
        urls = urls.filter(function(url){
            if(url==null){
                return false
            }
            return true;
        })
        
        function uploadFromStream() {
            var pass = new stream.PassThrough();
            var params = {Bucket: bucket, Key: 'download.zip', Body: pass};
            s3.upload(params, function(err, data) {
              console.log(err, data);
            });
            return pass;
          }
         
          var archive = archiver('zip', {});

         
          
          // This event is fired when the data source is drained no matter what was the data source.
          // It is not part of this library but rather from the NodeJS Stream API.
          // @see: https://nodejs.org/api/stream.html#stream_event_end
         
          // good practice to catch warnings (ie stat failures and other non-blocking errors)
          archive.on('warning', function(err) {
            if (err.code === 'ENOENT') {
              // log warning
            } else {
              // throw error
              throw err;
            }
          });
          
          // good practice to catch this error explicitly
          archive.on('error', function(err) {
            throw err;
          });
          let s3OutputStream = uploadFromStream();
          // pipe archive data to the file
          archive.pipe(s3OutputStream);
          
          let asyncSeries = [];
          urls.forEach(function(url){
            let name = url.substring(url.lastIndexOf('/')+1);
            asyncSeries.push(function(callback){
              let rs = s3.getObject({Bucket:bucket,Key:url}).createReadStream();
              console.log(rs);
                archive.append(rs, { name: name });
                callback(null)  
            })
            async.parallel(asyncSeries,function(err,res){
            console.log('yolo');
            archive.finalize();  
          });
          })
          archive.on('end',function(err){
            return callback(null,'yess')
          })            
          
          
     }       

   });
};
