### ISSUE TITLE
get empty zip file 

### ISSUE THREAD

**Issue by mortenko** [archiverjs/node-archiver#317]
Im trying to archive my folder that contains multiple files using archiverjs library.

As param, Im sending absolute path to the dir that contains my files. I would like to get zipped directory with files in the root of archive. Im creating zip file using createWriteStream. From some reason it does not work properly.Files weren't written in my zip file means it becomes empty. 

What I want to achieve:

lets say I have folder download where are my files I would like to archive. then Im creating download.zip where I would like to have all my files in the root of archive.

Where should be the problem ?
```
function createArchiveZip(destinationDir) {
      const archive = archiver("zip", { zlib: { level: 9 } }); 
      const archiveDir = `${destinationDir}.zip`;
      const zipOutput = fs.createWriteStream(archiveDir);
     
      zipOutput.on("error", writeStreamError => {
        console.log("writeStreamError", writeStreamError);
      });
      zipOutput.on("end", writeStreamEnd => {
        console.log("writeStream finish", writeStreamEnd);
      });
      archive.on("warning", archiveWarnings => {
        console.log("archiveWarnings", archiveWarnings);
      });
      archive.on("error", archiveErr => {
        console.log("archiveErr", archiveErr);
      });
      archive.pipe(zipOutput);
      archive.directory(destinationDir, false);
      archive.finalize();
      return archiveDir;
    }

```

**Comment by mortenko** [comment]
the issue was not related to the archiverjs.

**Comment by Tuuleh** [comment]
Hey! 
What was the issue?
I'm seeing similar behavior where I have a bunch of csv files in /tmp/csv/. If I call archive.directory(tmp/, false), I get a zip archive with the csv directory in it. If I call `achive.directory(tmp/csv/, false)`, I get an empty zip archive.

**Comment by inventgm** [comment]
> Hey!
> What was the issue?
> I'm seeing similar behavior where I have a bunch of csv files in /tmp/csv/. If I call `archive.directory(tmp/, false)`, I get a zip archive with the csv directory in it (as expected). If I call `achive.directory(tmp/csv/, false)`, I get an empty zip archive. The reason this is an issue for me is that I'm running this on Lambda, where I can only write files to /tmp. So I need to first create my zip output in /tmp/, and then zip /tmp/ itself, so my resulting archive contains the zipfile itself.

Did you ever get to understand the issue. I am facing a similar issue. Can you provide any inputs please?

**Comment by Tuuleh** [comment]
I worked around it by explicitly getting only all cvs files from the directory. Here's the code in question. In the arguments, `dir` is `${__dirname}/tmp` on local environment and `/tmp` on Lambda because I don't want to write to `/tmp` locally, and `filename` for this purpose was the name of the zipfile. 

```    
export function zipCSVFiles(dir, filename) {
  return new Promise(function(resolve, reject) {
    const zipPath = `${dir}/${filename}`;
    var output = fs.createWriteStream(zipPath);
    var archive = archiver('zip', {
      zlib: { level: 9 },
    });

    archive.on('error', function(err) {
      reject(err);
    });

    archive.on('warning', function(err) {
      if (err.code === 'ENOENT') {
        console.log('Archiver warning: ', err);
      } else {
        reject(err);
      }
    });

    archive.pipe(output);
    archive.glob('**/*.csv', { cwd: `${dir}` });
    archive.finalize();

    output.on('close', function() {
      resolve(zipPath);
    });
  });
}

```
