### ISSUE TITLE
Is it possible to cancel compression?

### ISSUE THREAD

**Issue by Tvrqvoise** [archiverjs/node-archiver#322]
Hello,

In my code, there is a condition when I may want to abort execution.  Currently, I have to wait for any in-progress archiver runs to finish.  Is there a way to cancel compression prematurely?

**Comment by conceptualspace** [comment]
yes, https://archiverjs.com/docs/Archiver.html#abort

**Comment by Tvrqvoise** [comment]
Wonderful, not sure how I missed that.
