### ISSUE TITLE
Option to exclude hidden files when using directory method

### ISSUE THREAD

**Issue by alexandercerutti** [archiverjs/node-archiver#327]
Hi! I'm looking, as the issue title says, for a way to add all files of a directory to a file zip, excluding hidden files (like .DS_Store on macOS) and other custom files.

I was looking into the code of `.directory` method and discovered that it is possible to pass a function as third parameter which can determine, if I've understood correctly, if a file should be added to the archive or not.

I tried to make some test on my own and discovered that the passed function doesn't get called since `onGlobMatch` doesn't get called ever, probably due to the expression passed to `glob`.
I'm now understanding the reason for which this third parameter is not documented... 😂

Is there another way? At the moment I'm iterating through the files in a folder and adding them one by one, but I'll need soon to add subfolders content by excluding hidden files also in there and iterating "manually" may take very long time.

Thank you very much.

**Comment by ctalkington** [comment]
hum, I'll review our tests but last I checked the custom function did work.

I think though you want to use glob with a similar pattern of ** but with dot: false option.

The current advantage to directory is that it handles CWD automatically and allows setting the destination path. It may indeed be worth having some option to refine the glob options but then again it might be worth merging glob and directory logic. I'll have to think on this a bit more.

**Comment by cawa-93** [comment]
@ctalkington Are there any changes? The .directory() method works fine. But there is no way to specify a pattern to exclude files

**Comment by ChazUK** [comment]
I was wondering if there's been any movement on this, I've seen in previous versions there was a `{ dot: false }` property on the `.bulk` method. But that has since been removed.

**Comment by ChazUK** [comment]
I solved this by using the `glob` method

```
archive.glob("**/*", {
  cwd: path.join("./"),
  ignore: [".*"]
});
```
