### ISSUE TITLE
Dependency Checks

### ISSUE THREAD

**Issue by ctalkington** [archiverjs/node-archiver#329]
given the upgrade to newer versions of node that I'm going to be pushing out across the board soon. seems worth it to explore dependencies and use new node and/or es5 native functions.

**Comment by joemanfoo** [comment]
[If I understand the question above] Personally I'd probably keep the dependency to nothing greater than what Google Cloud Functions supports (currently node v6.14.0) so that this package remains available for those folks out of the box.
