### ISSUE TITLE
Error with webpack

### ISSUE THREAD

**Issue by fpsqdb** [archiverjs/node-archiver#349]
With wepback latest version `4.21.0` will cause `input source must be valid Stream or Buffer instance` error.
But if downgrade to webpack `4.17.1` it works fine,
I found a similar issue here.
#https://github.com/webpack/webpack/issues/1815

**Comment by pajryan** [comment]
Having a similar problem.  Treating it as an external solves it for the moment...
```
externals: {
    "archiver": "require('archiver')"   
}
```

**Comment by danielehrhardt** [comment]
Some Problem if i try to use it with Angular
