### ISSUE TITLE
Archiver seems leaking memory in Jest tests just by importing it

### ISSUE THREAD

**Issue by voroshkov** [archiverjs/node-archiver#353]
Running Jest tests on my project I noticed a constant memory consumption growth. A short investigation revealed that if I comment out the archiver import statement, memory gets released after each tests set execution. 
Here's the simple setup that reproduces the issue:

There's a set of 20 test files, each having the same code:
```js
// my_test1.e2e.js, my_test2.e2e.js ...

import archiver from 'archiver';

describe(`describe`, () => {
    // make sure to collect garbage before each test (run node with --expose-gc option)
    beforeEach(() => global.gc());
    // introducing a timeout to watch for memory growth
    test('test', async () => await new Promise(r => setTimeout(r, 3000)));
});
```

Jest config is as simple as:
```js
// jest.config.e2e.js

module.exports = {
    // The test environment that will be used for testing
    testEnvironment: 'node',

    // The glob patterns Jest uses to detect test files
    testMatch: ['**/__tests__/**/my_test*.e2e.js'],
};
```

Run the tests with the following command (use --runInBand to make Jest run all tests subsequently in a single node process):

`node --expose-gc node_modules/jest/bin/jest --config="jest.config.e2e.js" --runInBand`

**Result:**

And here's the Node process monitoring results captured while running the tests. It clearly shows that memory allocation grows with each subsequent tests set execution:

![image](https://user-images.githubusercontent.com/8790856/48401341-fdae2280-e739-11e8-8651-bb45c08b0bd4.png)

And here's what I have after commenting out the `import archiver from 'archiver';` statement in all test files:
![image](https://user-images.githubusercontent.com/8790856/48401489-5c739c00-e73a-11e8-8c1a-1484fdef2c72.png)

**Comment by voroshkov** [comment]
This seems to be the issue in `graceful-fs`, which had been fixed 11 days ago: https://github.com/isaacs/node-graceful-fs/pull/137

**Comment by oleksiygontariownit** [comment]
Any update on this issue?
