### ISSUE TITLE
What event can listen to the zip file is already form?

### ISSUE THREAD

**Issue by TongDaDa** [archiverjs/node-archiver#356]
I want to know the event what the zip file exists and it can be usable? I try to open the zip file when I debug in my webstorm in the archive.on('end') or `finish` function, it is not open, and then I resume the process that there no debugger, it can be opened.

**Comment by trollkotze** [comment]
You have to wait for the output stream to close, i.e.:

```
const archive: archiver.Archiver = archiver('zip', {
  zlib: { level: 9 }
});

const output = fs.createWriteStream('./hello.zip');

output.on('close', () => {
  console.log('I\'m done! You can open the file now.');
});

archive.pipe(output);

// put stuff into the archive ...
archive.file('./hello.txt', { name: 'hello.txt'});

```

**Comment by TongDaDa** [comment]
Thanks @trollkotze
