### ISSUE TITLE
Result archive have the same size as packed file

### ISSUE THREAD

**Issue by Rkrushanovskij** [archiverjs/node-archiver#360]
I\`m trying to make archiving but result archive have the same size as storing file. It is the same with different compressions levels - 1, 9, etc.
```
let archive = archiver('tar', {
                    zlib: { level: zlib.constants.Z_BEST_COMPRESSION } // Sets the compression level.
                });
```

The same happens with 'zip' format...
Could you please help me?

**Comment by trollkotze** [comment]
What kind of files are you trying to compress?
Maybe the files in question are already in a compressed format?

**Comment by Rkrushanovskij** [comment]
@trollkotze as i understood, it is... .pdf, .png
Folder with multiple files compresses to smaller size, i think this thread could be resolved
