### ISSUE TITLE
Can we get the size of the zip?

### ISSUE THREAD

**Issue by amitdhawan** [archiverjs/node-archiver#368]
Im appending file streams in the zip archiver modules and need to get the size of the zip sent to the client for analytics purposes. Is there an api or way to get the size of the zip from archiver module?

**Comment by ctalkington** [comment]
there is a progress event that is emitted which has some data that might be useful for analytics but also if you use archive.pointer() on the `end` event (https://www.archiverjs.com/archiver#pointer). this mainly tells how many bytes we've emitted. 

semi-related: https://github.com/archiverjs/node-archiver/blob/master/examples/progress.js
