### ISSUE TITLE
Documentation website certificate expired

### ISSUE THREAD

**Issue by ryanmr** [archiverjs/node-archiver#370]
As of today, the [documentation website](https://archiverjs.com/docs/) has had its Let's Encrypt certificate expired since February 1st it seems. This causes a warning page in Chrome and for the site to be marked as insecure.

**Comment by ctalkington** [comment]
I've moved the docs to netlify to streamline building and uptime

**Comment by pratikgaikwadhive** [comment]
@ctalkington, it says _page not found_ 
![image](https://user-images.githubusercontent.com/36861239/53887527-7b02e900-3ff0-11e9-8c32-8a3a93091805.png)

**Comment by ryanmr** [comment]
@pratikgaikwadhive Hi - it looks like the `/docs` was removed; the top level now holds the docs - https://archiverjs.com/docs/
