### ISSUE TITLE
new Buffer() causes Deprecation warnings in Node 12

### ISSUE THREAD

**Issue by CliffReimers** [archiverjs/node-archiver#380]
The dependency node-compress-commons (lib/archivers/zip/constants.js) causes Deprecation warnings in Node 12:

https://nodejs.org/api/deprecations.html#deprecations_dep0005_buffer_constructor

I could make a PR to node-compress-commons if that is wanted.

**Comment by ctalkington** [comment]
should be resolved in v3.0.3
