### ISSUE TITLE
High Vulnerability in lodash 4.17.11

### ISSUE THREAD

**Issue by rutanika** [archiverjs/node-archiver#382]
snyk test lodash@4.17.11

Testing lodash@4.17.11...

✗ High severity vulnerability found in lodash
Description: Prototype Pollution
Info: https://snyk.io/vuln/SNYK-JS-LODASH-450202
Introduced through: lodash@4.17.11
From: lodash@4.17.11

Package manager: npm
Open source: yes
Project path: lodash@4.17.11

Tested lodash@4.17.11 for known vulnerabilities, found 1 vulnerability, 1 vulnerable path.

**Comment by ctalkington** [comment]
v3.0.1 should resolve lodash introduced by non-devdeps. jsdoc them will be updated shortly.
