### ISSUE TITLE
Define file permissions

### ISSUE THREAD

**Issue by gimenete** [archiverjs/node-archiver#39]
Hi,

First of all, thanks for this neat and useful module.

I'm generating zip files and now I need to define a file entry as executable. The zip format does not support this. But the tar format should support it. However I don't see how tell this npm module the permissions of a file entry. I've seen the source code for the tar format and I just see that you can specify the name and date of the file in the "data" argument. Maybe this argument could be extendend to support a "mode" like [fs.createWriteStream](http://nodejs.org/api/fs.html#fs_fs_createwritestream_path_options).

Thank you.

**Comment by julianpoemp** [comment]
For anyone who faces this issue in 2023 using Typescript: You can add the file permissions for zip via `mode` attribute:

````typescript
zip.append(content, {
  mode: 0o755
}
````

Before setting this extracted files on MacOS had read permissions only.
