### ISSUE TITLE
Filenames with Japanese characters garbled

### ISSUE THREAD

**Issue by adbutterfield** [archiverjs/node-archiver#392]
Hi!

We've had a report from several of our customers, that filenames for zipped csv files are garbled. The filenames are a mix of numbers and Japanese characters.

I'm trying to get more information about the exact systems, but I'm pretty sure all the complaints are all coming from Windows/IE users.

We have not been able to reproduce the issue in house, even on Windows machines. I know it's not a lot to go off of, but I'm hoping possibly someone has come across this in the past, and there's a fix for it. I already looked through all the other open/closed issues and didn't find anything.

Let me know if you think of anything! Or else feel free to close.

I'll make an update if I get some more information.

**Comment by adbutterfield** [comment]
Just remembered about this issue. Short of it is, don't use non-ascii characters in filenames.

**Comment by ueda000** [comment]
Jumping in on this. I faced the same issue with Japanese filenames. Setting store: true when configuring archiver solved it for me.

```js
const archive = archiver('zip', {
    // ... your other options ...
    store: true
});
```

Hope it helps someone!
