### ISSUE TITLE
Corrupt Zip when generated on Azure Web App

### ISSUE THREAD

**Issue by MartinHepplewhiteEducationGovUk** [archiverjs/node-archiver#410]
[SimpleZip.zip](https://github.com/archiverjs/node-archiver/files/4337977/SimpleZip.zip)
This works great running locally on a VM but once published to an Azure Web App the zip file generated can't be opened ("The compressed (zipped) folder....is invalid").

There's no errors thrown on the node side to investigate. Any ideas?

Simplest test code example 
```
res.setHeader('Content-Type', 'application/zip');
res.attachment('SimpleZip.zip');
const archive = archiver.create('zip', { zlib: { level: 9, }, });
archive.pipe(res);
archive.append('Testing', { name: 'Tst.txt' });
archive.finalize();
```

**Comment by gb909013** [comment]
I got the same issue. Any solution?

**Comment by MartinHepplewhiteEducationGovUk** [comment]
Without anything to go on I put this on the back burner. Good news is that it auto-magically resolved itself. Bad news is I can't pin point when this happened or offer any suggestions on what may have resolved it.

**Comment by gb909013** [comment]
Thanks. I also experienced the magic. It has resolved itself. However, the issue happen again once I restarted the app.

Finally, I figured out it is related to the response buffer on iis.

Added <iisnode flushResponse="true"/> to web.config to disable the response buffer resolved the issue.

**Comment by mattvasc** [comment]
@MartinHepplewhiteEducationGovUk shall we close this bug?
