### ISSUE TITLE
Archiver does not handle multiple streams

### ISSUE THREAD

**Issue by alesmenzel** [archiverjs/node-archiver#415]
Hello, I am working on an excel library that needs to write to multiple files at once and only end the stream when I write enough of data to both streams. Why does archiver can only process 1 stream at a time?

```js
const archiver = require('archiver');
const fs = require('fs');
const stream = require('stream');
const {once} = require('events');

const arch = archiver('zip');

async function writeTo(stream, data) {
  if (!stream.write(data)) {
    console.log('BACKPRESSURE');
    await once(stream, 'drain');
  }
}

arch.pipe(fs.createWriteStream('output.zip'));

async function run() {
  const a = new stream.PassThrough({highWaterMark: 1});
  const b = new stream.PassThrough({highWaterMark: 1});

  arch.append(a, {name: 'a.txt'});
  arch.append(b, {name: 'b.txt'});

  await writeTo(a, Buffer.alloc(17000));
  await writeTo(a, Buffer.alloc(17000));
  await writeTo(a, Buffer.alloc(17000));
  await writeTo(a, Buffer.alloc(17000));
  await writeTo(a, Buffer.alloc(17000));

  await writeTo(b, Buffer.alloc(17000));
  await writeTo(b, Buffer.alloc(17000));
  await writeTo(b, Buffer.alloc(17000));

  // never finishes because the second stream buffers fill up due to Archiver processing only one stream at a time

  a.end();
  a.end();

  arch.finalize();
}

run().then(() => {
  console.log('DONE');
  process.exit();
}).catch(err => {
  console.log('ERR', err);
  process.exit(1);
});
```

Would it be possible to handle multiple streams in archiver?

**Comment by ctalkington** [comment]
archiver can only write one file at a time due to zip format not being friendly to such streaming so archiver has to rely on the streams to queue and process as possible. it wasnt really written with promises or await support in mind but it something that is on the bucket list for a future overhaul.

**Comment by ctalkington** [comment]
your highWaterMark is also not allowing for streams to manage their own flow very well since its only allowing 1 byte at a time to passthrough

**Comment by alesmenzel** [comment]
thanks, I thought it was a no go due to the zip file format. In my case it does not make a difference whether the highWaterMark is 1 or 16k since I would eventually fill up the internal buffer anyway because the 2nd stream is not piped (read from).
