### ISSUE TITLE
Vulnerability: https://snyk.io/test/npm/archiver/4.0.1

### ISSUE THREAD

**Issue by ihargit** [archiverjs/node-archiver#419]
Hi guys,,
Please, fix this https://snyk.io/test/npm/archiver/4.0.1.
Looks like just async package update is needed.
Regards, Ihar.

**Comment by sseide** [comment]
yes  - latest async versions 3.x dropped dependency lodash as this is mostly unmaintained by now.
This will fix the Snyk and "npm audit" warnings...

**Comment by Siemienik** [comment]
I have this issue too, https://github.com/Siemienik/xlsx-renderer/issues/24
