### ISSUE TITLE
Compression abort cannot be deleted！！！

### ISSUE THREAD

**Issue by w602542704** [archiverjs/node-archiver#421]
system: windows10
development environment：electron 9+、node 12+
Recurrence：Compress the file in electron. When. On ("progress") is compressed to 50%, execute archive.abort (), in execution fs.unlink (), unable to delete. Appears to be in use.
code:
`const fs = window.require("fs");

var archiver = window.require("archiver");

export default function archiverZip(){

    var output = fs.createWriteStream( "D:/images.zip");

    var archive = archiver("zip", {

      zlib: { level: 5 }, // Sets the compression level.

    });

    archive.pipe(output);

    archive.on("progress", function (res) {

      console.log(">>>>>>>>>",res)

      if( parseInt(
        (res.entries.processed / res.entries.total) * 90 + 10,
      )>20){

         console.log('archive',archive)          

        archive.abort()         
       
        fs.unlink("D:/images.zip",function(res){})

      }  

    });

       archive.directory('D:/images', "images");

       archive.finalize();

}`

**Comment by w602542704** [comment]
![image](https://user-images.githubusercontent.com/24689873/87110535-d9517300-c299-11ea-8f95-8a07bfeb4b69.png)
![image](https://user-images.githubusercontent.com/24689873/87110606-0140d680-c29a-11ea-82ad-f7993dfae428.png)

**Comment by w602542704** [comment]
@ctalkington  @Siemienik   I'm sorry to interrupt your.

**Comment by w602542704** [comment]
It seems that archiver does not release resources in time when it aborts compression

**Comment by zhangpengyue1985** [comment]
I had the same problem.I create a zip file and upload it to my service.Then I need to delete the file.But the file still exists.The finally I closed my electron program, the zip file disappeared.

**Comment by zhangpengyue1985** [comment]
![无标题](https://user-images.githubusercontent.com/54656144/96108969-c42b5680-0f10-11eb-8daa-a6bc424f9461.png)
![无标题1](https://user-images.githubusercontent.com/54656144/96108974-c5f51a00-0f10-11eb-870d-8a548fcd2401.png)
![无标题2](https://user-images.githubusercontent.com/54656144/96108984-c7264700-0f10-11eb-9552-c74e7a1552c0.png)
