### ISSUE TITLE
Performance of archiver vs native zip child process?

### ISSUE THREAD

**Issue by sunknudsen** [archiverjs/node-archiver#440]
This is perhaps a naive question, but couldn’t find documentation explaining the value prop of using archiver vs a native zip child process.

Love the idea of using archiver vs a native zip child process.

Planning on zipping folders on a server with limited memory.

What are the benefits of each option?

**Comment by ctalkington** [comment]
native zip is likely faster but archiver also does tar and has a nodejs streaming api for peogrammers. i dont benchmarl against native implementations
