### ISSUE TITLE
NPM Advisory - BL - Remote Memory Exposure

### ISSUE THREAD

**Issue by goyney** [archiverjs/node-archiver#446]
The version of `bl` that is included in `tar-stream` is affected by https://npmjs.com/advisories/1555. `bl` has released 4.0.3 which fixes this. An update request has been asked of `tar-stream` here: https://github.com/mafintosh/tar-stream/issues/126

Once that request has been fulfilled and an update released, an update of `tar-stream` here would be appreciated to resolve this security vulnerability.

**Comment by goyney** [comment]
`tar-stream` has released version v2.1.4 to NPM, which includes the fix to `bl`. An update to the lasest version of `tar-stream` and a publish of `archiver` as v5.0.1 to NPM would be highly appreciated.

**Comment by ctalkington** [comment]
https://github.com/archiverjs/node-archiver/releases/tag/5.0.1

**Comment by goyney** [comment]
I might be missing something here, but you only updated your lockfile, not your package.json. Your lockfile doesn't translate to my lockfile, so when I install the latest version, I still get tar-stream 2.1.2, as instructed by your package.json. There, installing this fresh, I don't get the latest updates of your downstream dependencies and we're still affected by the NPM advisory.

**Comment by ctalkington** [comment]
try `npm update archiver` package.json just says you need atleast 2.1.2 but if you ask npm to do the update it should sort itself out
