### ISSUE TITLE
.glob() with options.cwd is not working at 5.x

### ISSUE THREAD

**Issue by hyoo** [archiverjs/node-archiver#455]
Just found the source problem, in the pr 

https://github.com/archiverjs/node-archiver/pull/433

The non-backward compatibility needs to be documented or clearly communicated to the users !!!

Is there any workaround that can avoid including absolute path?

**Comment by ctalkington** [comment]
This was communicated in the changes for 5.0. Its also why it was released as a new major version per semver.

please provide an example of your usage

**Comment by simpixelated** [comment]
I ran into the same problem, found the breaking change note in the changelog, and updated my usage:
```diff
-archive.glob('../frontend/build/static/js/main.*.js', null, { name: 'ghost-inspector.js', prefix });
+archive.glob('main.*.js', { cwd: '../frontend/build/static/js/'}, { name: 'ghost-inspector.js', prefix });
```
However the problem I'm having now is that it doesn't seem to be using `options.name` anymore. The final archive is using the original filenames it found via `glob`.

**Comment by ctalkington** [comment]
@simpixelated can you provide sn example of file names inside archive and expected names?

**Comment by simpixelated** [comment]
@ctalkington 

filename inside the archive (matches original filename):
```
main.7f7102c9.js
```
expected (with `{name: 'ghost-inspector.js'}`:
```
ghost-inspector.js
```

**Comment by hyoo** [comment]
Here is my use-case. I have files in `/a/b/c1/fileN/` and `/a/b/c2/filesN` for example, and I want to build archive files based on the level of C, keeping the sub-directory structures. So, when user downloaded and unzipped, it shows like `c1/filesN` and `c2/filesN`.

**Comment by ctalkington** [comment]
@hyoo you should be able to do that with:

```js
archive.directory('a/b/c1', 'c1')
```

**Comment by ctalkington** [comment]
`cwd` stands for current working directory and tells glob where it should base its search. the glob pattern should be relative to `cwd`
