### ISSUE TITLE
Producing broken (bad CRC) zip archives on Node v15.6.0

### ISSUE THREAD

**Issue by pgrzesik** [archiverjs/node-archiver#491]
Hello team :wave:

During the investigation of an issue reported in Serverless Framework (https://github.com/serverless/serverless/issues/8772), I've noticed that for the latest release of Node, `v15.6.0`, archiver will produce broken zip archives with bad CRCs. I've also tested for node10, node12, node14 as well as `v15.5.0` and there is no issue, so it seems like it was caused by the latest node [release](https://nodejs.org/en/blog/release/v15.6.0/).

Archiver version used: `5.2.0`

Below you can find steps to reproduce it using dumbed down version of example from documentation

<details>
<summary>Snippet</summary>

```
const fs = require('fs');
const archiver = require('archiver');

const output = fs.createWriteStream(__dirname + '/example.zip');
const archive = archiver('zip');

output.on('close', function() {
  console.log(archive.pointer() + ' total bytes');
  console.log('archiver has been finalized and the output file descriptor has closed.');
});

output.on('end', function() {
  console.log('Data has been drained');
});

archive.on('warning', function(err) {
  if (err.code === 'ENOENT') {
    // log warning
  } else {
    // throw error
    throw err;
  }
});

archive.on('error', function(err) {
  throw err;
});

archive.pipe(output);

// append a file from string
archive.append('string cheese!', { name: 'file.txt' });

archive.finalize();
```
</details>

Executing it on `v15.6.0` results in archive that when unzipping results in:
```
> unzip example.zip
Archive:  example.zip
  inflating: file.txt                 bad CRC d1cd8993  (should be 00000000)
```

While on anything below `v15.6.0` it's working without issues:
```
> unzip example.zip
Archive:  example.zip
  inflating: file.txt
```

I'd be happy to provide more details if needed, please let me know if there's any way I can help resolving this issue, thanks in advance :bow:

**Comment by Aaron1011** [comment]
This is reproduceable with just `node-zip-stream`:

```node
const Packer = require('./index.js');
const fs = require('fs');
const archive = new Packer(); // OR new Packer(options)

archive.on('error', function(err) {
  throw err;
});

const output = fs.createWriteStream(__dirname + '/new.zip');
archive.pipe(output);

archive.entry('string contents', { name: 'string.txt' }, function(err, entry) {
  if (err) throw err;
  archive.entry(null, { name: 'directory/' }, function(err, entry) {
    if (err) throw err;
    archive.finish();
  });
});
```

**Comment by xfournet** [comment]
Probable root cause : https://github.com/archiverjs/node-crc32-stream/issues/31

**Comment by Aaron1011** [comment]
The root cause is https://github.com/nodejs/node/issues/37027

**Comment by ctalkington** [comment]
thanks everyone. a new release of crc32-stream has been made.
