### ISSUE TITLE
create "part" with multiple archive

### ISSUE THREAD

**Issue by Jcbobo** [archiverjs/node-archiver#498]
I need to archive some big folders and make the user download the archive (zip), but since the folders are really big I need to build 
different archives, at this point I have two options:

1. estimate using the compression factor the size of the archive for a given set of files and decide if create one or more archives (and actually where do the splits)
2. start archiving and checking when a specific threshold is reached, 
    -  if is not add an other files to the stream to be archived
    - if yes finalize the archive and create an other one 

do you have any advice about how to preceed with the second option?
is the entry event a good place where insert this logic?

**Comment by bneigher** [comment]
@Jcbobo curious what you landed up with

**Comment by Jcbobo** [comment]
I was lucky that on average the file size was small, no need to split files on different archives, if the file is bigger than the part size simply the part will be bigger( the size is not a fixed requirement ).

Since the part size is not a requirements we use a "stupid" heuristic to create the parts:
- sum(files to add)/compression rate >partSize --> create part

To make something without reply on "pre-compute" the part size, a wait  archive queue is empy API is needed so the (almost) real archive size can be checked
