### ISSUE TITLE
Allow leading slash in root path of Zip file

### ISSUE THREAD

**Issue by andrecadete** [archiverjs/node-archiver#502]
Hi,

For reasons out of my control (external partner) I have to create a zip with an explicit root path. Providing `"/"` as value of the Destination path or Prefix option does nothing, it seems to be removed by your library intentionally.

Below an output of the desired and produced result (also note the "documents" directory is for some reason also different in the "desired" result than the one produced by this library).

Desired:
![example](https://user-images.githubusercontent.com/15102473/109705617-46eb4000-7b98-11eb-8b43-4231384cf173.jpg)

Actual result:
![result](https://user-images.githubusercontent.com/15102473/109705663-4f437b00-7b98-11eb-8057-02f28bfae183.jpg)

The latter is naturally produced when adding a File to a zip and providing a leading slash in the destination name (i.e. "/filename.xml"), but I'm trying to migrate a few Java applications to serverless using Node (typescript) and this is the only show stopper. I've also looked around in all other decent zip libraries for node and none seems to be able to produce these zip contents.

Please confirm if there is no way to have this result with your library and if not:
- Can this become a feature (request) and when could one expect it to be available? (to manage internal company expectations)
- If it can't become a feature (request) can you point me out where I can change the code to allow this?

Cheers

**Comment by ctalkington** [comment]
@andrecadete what code do you use to generate?

**Comment by ctalkington** [comment]
working on an option for this. it'll be opt-in only for those that need it because the sanitization does have some benefit for preventing zips that can unpack over root level files.

**Comment by andrecadete** [comment]
Hey @ctalkington.

First of, thanks for the super speedy answer and action :+1: :100: 

To answer your first question, we're using a simple `directory('/tmp/path/to/folder/', false)` call, where we'd like to replace `false` with `'/'` but We can also iterate the files and add them to the archive 1 by 1 if you prefer to add this to the `prefix` option.

I tried to replicate this behavior with the zip cli and couldn't. Can it be that it falls outside the standard of `zip` itself? I can try to find out if behind the scenes the current Java application uses `tar` instead. Let me know if that would help in any way.

**Comment by ctalkington** [comment]
@andrecadete archiver v5.3.0 should allow you to pass `namePrependSlash: true` via main options or per entry as entry data.

https://www.archiverjs.com/docs/archiver#zip-options
