### ISSUE TITLE
How to exclude files and put the contents at the root of archive?

### ISSUE THREAD

**Issue by mattp0123** [archiverjs/node-archiver#509]
Something like:
```Javascript
archieve.directory('dirname/', false, {
  ignore: ['.DS_Store'],
});
```
Or
```Javascript
archieve.glob('dirname/**', {
  ignore: ['.DS_Store'],
  subDir: false,
})
```

**Comment by evanre** [comment]
About excluding files I came across with this solution. About root, try to check out the second parameter from this method.
`archive.directory(dstPath, false, file => file.name.endsWith('.zip') ? false : file);`

**Comment by mattp0123** [comment]
> About excluding files I came across with this solution. About root, try to check out the second parameter from this method.
> `archive.directory(dstPath, false, file => file.name.endsWith('.zip') ? false : file);`

@evanre It works perfectly! thank you. It's kind of weird the entry data function should return file but true if the file should be included in tho.
