### ISSUE TITLE
archive.finalize is timing out my requests

### ISSUE THREAD

**Issue by randomprogramming** [archiverjs/node-archiver#517]
Hello, 
I have a NextJS app where I have to generate loads of QR codes, 300,400,500 at a time. I want to put them inside a zip and let the user download them. Here's the code which puts the codes into a zip

```
  const archive = archiver.create("zip", {});

  let index = 1;
  for (const code of codes) {
    // @ts-expect-error
    const qrCode = new QRCodeStyling({
      nodeCanvas: canvas,
      width: 300,
      height: 300,
      data: code.url
    });

    archive.append(
      await qrCode.download({
        name: "testName",
        extension: "png",
        skipDownload: true,
        buffer: true,
      }),
      {
        name: `${code.name}-${index}.png`,
      },
    );

    index++;
  }

  console.log("before finalizing");
  await archive.finalize();
  console.log("after finalizing");

  return archive;
```

The request takes like 8-9s on a local machine, and when in production it just times out every time. The program sometimes doesn't even respond, it just hangs on before finalizing. I am using the Vercel platform in production and on the free plan requests time out after 10s.

Please note that these zip files are usually around 3-5mb, so size should not be a problem I don't think.

**Comment by dserranog1** [comment]
how did you solve it?

**Comment by randomprogramming** [comment]
@dserranog1 I switched to JSZip.
