### ISSUE TITLE
Any way to create folders in the archive?

### ISSUE THREAD

**Issue by newmanw** [archiverjs/node-archiver#52]
I would like to create folders in my zip, is it possible?

**Comment by ltomes** [comment]
> archive.append(null, { name: 'directory/' });

Does this still work in the latest versions of `node-archiver`?

**Comment by mhemrg** [comment]
@ltomes Yes. It works with `3.0.0`.

**Comment by briancullinan** [comment]
No it does not 
```
ArchiverError: entry name must be a non-empty string value
    at Archiver.append (/Users/briancullinan/planet_quake/node_modules/archiver/lib/c
    at compressDirectory (/Users/briancullinan/planet_quake/misc/quakejs/bin/compress
    at repack (/Users/briancullinan/planet_quake/misc/quakejs/bin/repack.js:691:11)
    at async repackGames (/Users/briancullinan/planet_quake/misc/quakejs/bin/repack.j
  message: 'entry name must be a non-empty string value',
  code: 'ENTRYNAMEREQUIRED',
  data: undefined
}

```

**Comment by guanguanqingchao** [comment]
> you can now use the following in `v0.8.0`:
> 
> ```js
> archive.append(null, { name: 'directory/' });
> ```

how to fill content into 'directory/ ?

**Comment by shen-lin** [comment]
> > you can now use the following in `v0.8.0`:
> > ```js
> > archive.append(null, { name: 'directory/' });
> > ```
> 
> how to fill content into 'directory/ ?

@guanguanqingchao 

The 2nd parameter of directory() and the name attribute in the 2nd param of append() can take file path as inputs. 

```
        archive.directory('.../yourfolder', 'directory/yourfoler');
        archive.append(fs.createReadStream('.../yourfile'), { name: 'directory/yourfile' });
```

**Comment by tsulatsitamim** [comment]
in version 7.0.1, use null create empty file inside the folder
