### ISSUE TITLE
Trimming library size

### ISSUE THREAD

**Issue by RWOverdijk** [archiverjs/node-archiver#527]
This lib works great for what I need, but it is a bit too large for my taste. I checked out the cause and found:

https://bundlephobia.com/package/archiver@5.3.0 (221.5kB)

Comparing this to what I used before this lib: https://bundlephobia.com/package/adm-zip@0.5.5 (28.3kB)

Is a pretty big jump.

I understand that the addition of streams is worth sacrificing some storage, but I don't think all of the dependencies are that important.

For example the async lib is primarily used for a queue but takes up a pretty large chuck of the size.

Would it be an option to replace some of the dependencies with either smaller ones or tailored (rewritten) to reduce file size? Normally I wouldn't care, but the deploys, storage and startup time of my firebase functions do hurt a bit so I wanted to at least ask.

**Comment by fspoettel** [comment]
depending on your use case, you could try to directly use the core of this library. this is published as package [zip-stream](https://www.npmjs.com/package/zip-stream) on npm. It comes in at `164.2 kB` and does not contain `async`.

**Comment by ctalkington** [comment]
I do really want/plan to go full ES6 with async, just have to find the time. indeed zip-stream is the core of the zip logic and archiver is more the sugar on top
