### ISSUE TITLE
Appending empty file via stream hangs

### ISSUE THREAD

**Issue by robinmessage** [archiverjs/node-archiver#532]
If I fetch a URL which is empty and append it to a zip archive, the archive hangs on `finalize`.

```
const data = await fetch(url);
const readable = new Readable().wrap(data.body);
zip.append(readable, {
    name: `empty file`,
});
zip.finalize();
```

**Comment by devuser15** [comment]
archive.append(null, { name: 'directory/' });

this works for me - folder without a file
issue# 52

**Comment by ctalkington** [comment]
Likelt need to pipe archive to get data flowing before calling append or finalize
