### ISSUE TITLE
Getting duplicate parent zip upon extracting

### ISSUE THREAD

**Issue by pawan-saxena** [archiverjs/node-archiver#548]
Hello all,
Hope you guys are well and safe.
Need some help.

I have written below for zipping a directory :

```
	const archiver = require('archiver');
	let createArchive = function(sourceDir, destDir) {
		const archive = archiver('zip');
		const stream = fs.createWriteStream(destDir);
		return new Promise((resolve, reject) => {
	    archive
	      .directory(sourceDir, false)
	      .on('error', err => reject(err))
	      .pipe(stream)
	    ;

	    stream.on('close', () => resolve());
	    archive.finalize();
	  });
	}
```

Before zipping my directory looked like this :

<img width="202" alt="Screenshot 2021-09-16 at 1 18 34 AM" src="https://user-images.githubusercontent.com/13232149/133499755-06411e86-942a-4510-80c8-719e2792b8d6.png">

After zipping it looked like this 
<img width="209" alt="Screenshot 2021-09-16 at 1 20 11 AM" src="https://user-images.githubusercontent.com/13232149/133499955-71347b7a-9b16-453a-9588-147f3b618d43.png">

Now when i unzipped the final result looks like this :

<img width="425" alt="Screenshot 2021-09-16 at 1 21 55 AM" src="https://user-images.githubusercontent.com/13232149/133500136-16d06b08-52e7-47de-9609-6563dbacc25f.png">

The problem is after extracting i can see the duplicate yayy.zip upon opening which it gives me following error.
<img width="391" alt="Screenshot 2021-09-16 at 1 22 45 AM" src="https://user-images.githubusercontent.com/13232149/133500258-ea5edea2-292a-4d2f-8e0a-9f3c5e2b9a22.png">

What i am missing ?
Is there a way to achieve it without diverting much from my approach, i want to know the issue.

Thank you.

**Comment by ve3** [comment]
The `.directory()` method is working recursive. If this **archiver** created .zip file when not finish all progress, it is possible to be duplicate .zip in .zip file.

It is better to set .zip destination on different folder or do not use `.directory()` that can be included location where .zip will be created.
