### ISSUE TITLE
Two `readable-stream` in dependencies

### ISSUE THREAD

**Issue by Semigradsky** [archiverjs/node-archiver#589]
`archiver 5.3.1` has `readable-stream ^3.6.0` and `archiver-utils ^2.1.0` in dependencies. 
But `archiver-utils 2.1.0` has `readable-stream ^2.0.0` in dependencies.

Could you update `archiver-utils` to v3 without updating `node-archiver`'s major version? Or publish `archiver-utils 2.x` with updated `readable-stream`.

**Comment by Semigradsky** [comment]
As I see v3 wasn't published https://github.com/archiverjs/archiver-utils/issues/99

**Comment by namoscato** [comment]
@ctalkington, any plans to address this discrepancy? These conflicting versions seems to be causing issues during a Webpack compilation process (i.e. via [ncc](https://github.com/vercel/ncc)).

**Comment by beanshearer** [comment]
This seems to cause issues when using `pnpm install` too. We get `Cannot find module 'readable-stream/passthrough'` after using `pnpm install`. Has anyone worked out a way around it yet?

**Comment by arsentabaku** [comment]
The issue still persists. Were you able to solve it @beanshearer ?

**Comment by ctalkington** [comment]
multiple updates released for archiver. should be more streamlined on deps now
