### ISSUE TITLE
Windows => Error: EBUSY: resource busy or locked, read

### ISSUE THREAD

**Issue by jtourisNS** [archiverjs/node-archiver#591]
Hello, 

I am getting this issue `Error: EBUSY: resource busy or locked, read` everytime I try to zip a directory on **Windows**. This code works perfectly fine on MacOS but it keeps crashing on windows every single time. I honestly don't know what to do anymore, my next step was to stop using the archiver lib and use another approach to zip the directory but I'll give it a last try by submitting an issue here. 

```js
async compressSession() {
        try {
            const archive = archiver('zip');
            const stream = fs.createWriteStream(`${this.sessionName}.zip`);
    
            return new Promise((resolve, reject) => {
                archive
                    .directory(this.userDataDir, false). // => Crashes here
                    .on('error', err => reject(err))
                    .pipe(stream);
    
                stream.on('close', () => resolve());
                archive.finalize();
            });
        } catch (error) {
            console.log('compressSession: ', error);
        }
    }
```

Please help me understand why this keeps crashing and/or if there is a possible solution for it. I NEED this to be an async task because I will later on save the compressed dir onto a remote database.

Thanks

**Comment by alumag** [comment]
Did you find a solution?

**Comment by jtourisNS** [comment]
> Did you find a solution?

@alumag Yes, for windows operating system I had to create a temp clone of the directory I wanted to compress and use that one instead of the real directory. This way the original resource used by the system would no be affected by the archiver process. 

Hope this helps
