### ISSUE TITLE
Lodash 4.17.5 vulnerability 

### ISSUE THREAD

**Issue by Coooi** [archiverjs/node-archiver#614]
I kindly ask you to upgrade Lodash to latest version (4.17.21) due to older versions vulnerability.

Report details:

> lodash node module before 4.17.5 suffers from a Modification of Assumed-Immutable Data (MAID) vulnerability via defaultsDeep, merge, and mergeWith functions, which allows a malicious user to modify the prototype of "Object" via __proto__, causing the addition or modification of an existing property that will exist on all objects. | Medium
> 
> A prototype pollution vulnerability was found in lodash <4.17.11 where the functions merge, mergeWith, and defaultsDeep can be tricked into adding or modifying properties of Object.prototype. | Medium
> 
> Versions of lodash lower than 4.17.12 are vulnerable to Prototype Pollution. The function defaultsDeep could be tricked into adding or modifying properties of Object.prototype using a constructor payload. | Medium

Thank you

**Comment by ctalkington** [comment]
v6.0.1 should resolve this as part of archiver-utils updates.
