### ISSUE TITLE
Invalid zip file created from "append" (archiver@5.3.1)

### ISSUE THREAD

**Issue by unbornchikken** [archiverjs/node-archiver#628]
Append doesn't work entirely, doesn't matter what you include. It even doesn't work for strings. Minimal example:

```
cost archive = require('archiver')("zip")
archive.append("hello", { name: "test.txt" })
archive.finalize()
archive.pipe(require('fs').createWriteStream('example.zip'));
```
This produces a zip with CRC error.

I'm using Node 16 on Windows.

**Comment by crice88** [comment]
I'm also running into issues with Windows. Getting duplicate files in the zipped archive. On Mac, it works fine... not sure of the cause yet.

**Comment by ctalkington** [comment]
it's likely order of operation issue, to get data flowing/streaming you need to pipe to file first before appending
