### ISSUE TITLE
Update dependency for `archiver-utils` (deprecation warning)

### ISSUE THREAD

**Issue by squio** [archiverjs/node-archiver#659]
Current dependency on `archiver-utils` is outdated (`package.json`):

```json
"dependencies": {
    "archiver-utils": "^2.1.0",
```

Current release `3.0.0` fixes a deprecation warning, see https://github.com/archiverjs/archiver-utils/issues/128

Is there a reason this package has not been updated yet?

**Comment by ctalkington** [comment]
it should be OK to bump that, I plan to do a maintenance release around US labor day weekend ( ~2 weeks)

**Comment by ctalkington** [comment]
closing as v6.0.0 was released ahead of original plan
