### ISSUE TITLE
Question: Were there any API changes from 5.3 to 6.x?

### ISSUE THREAD

**Issue by cakoose** [archiverjs/node-archiver#715]
- I'm using `archiver` in my TypeScript project.
- For type information, I'm using the `@types/archiver` package from DefinitelyTyped: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/archiver
- The latest version of `@types/archiver` is 5.x, which is meant to be used with `archiver` 5.x, according to the DefinitelyTyped versioning pattern.
- I want to create `@types/archiver` version  6.x to be used with `archiver` 6.x, but I'm not sure if any APIs changed.

Are there any API changes in `archiver` from 5.3 to 6.x? If not, I'll just submit a PR to `@types/archiver` to bump the version number to 6.x.

(I looked through the `archiver` changelog and it looks like there aren't any API changes from 5.3 to 6.x, but I wanted to double check that here.)

**Comment by ctalkington** [comment]
just node v10 dropped

https://github.com/archiverjs/node-archiver/compare/5.3.2...6.0.0
