### ISSUE TITLE
Archiver Version 7.0 might be breaking due to ESM

### ISSUE THREAD

**Issue by robence** [archiverjs/node-archiver#744]
https://github.com/archiverjs/node-archiver/compare/6.0.2...7.0.0

package lock includes strip-ansi in dependencies both 6.0.1 and 7.1.0

strip ansi v7.0.0 is breaking, contains pure ESM https://github.com/chalk/strip-ansi/releases/tag/v7.0.0

**Comment by ctalkington** [comment]
it seems the glob update includes `jackspeak` which relies on `cliui` which uses newer strip-anti. I suspect this dependency is for the glob package CLI shouldn't impact archiver and CI runs represent no issues.

If you find otherwise, please post back and
