### ISSUE TITLE
Checksum of generated zip file differs on successive executions

### ISSUE THREAD

**Issue by zarko-tg** [archiverjs/node-archiver#82]
Say you run "node pack-zip.js"
and then put the resulting zip file aside ( or just rename it ),
and then you run the script again.

The generated zip files will differ binary even though the source is the same.

Is there any dependency on time, something by specification?

I'd expect them to be binary equal, or at least have that configurable through an option.

**Comment by mistercorea** [comment]
I am still having same issue. 

```
async compressToZip(outputFilename, files, opt = {}) {
    const output = fs.createWriteStream(outputFilename);
    const archive = Archiver('zip', {
      gzip: true,
      zlib: { level: 9 }, // Sets the compression level.
    });

    // good practice to catch this error explicitly
    archive.on('error', function (err) {
      throw err;
    });
    archive.pipe(output);
    files.forEach((file) => archive.file(file, { ...opt, name: file }));
    return await archive.finalize();
  }
```

where i would pass opt as { new Date(0)}

but I kept getting few bytes off
