### ISSUE TITLE
Slower ZIP creation after upgrade to 0.11

### ISSUE THREAD

**Issue by steveoh** [archiverjs/node-archiver#94]
I am on a windows machine running node `0.10.28`. I am using this module from `grunt-contrib-compress`.

To compress this folder structure

![image](https://cloud.githubusercontent.com/assets/325813/4394320/5c6d1ea0-4420-11e4-9a9b-a9bf950177c5.png)

When using `grunt-contrib-compress` versions these are the results.
v0.12.0 took me over 4 minutes. this produces a 18913229 byte zip file
v0.11.0 took over 4 minutes and produced a zip file.
v0.10.0 took 45 seconds and produced a 18913229 byte zip file
v0.9.0 took 45 seconds and produced a 18809351 byte zip file.
v0.8.0 took 46 seconds for the same file. this produces a 18809351 byte zip file.

version 0.11 is where they updated to archiver 0.11. Version 0.10 and below are using archiver 0.9 and are ~4 times faster on my windows machine.  I would assume that the regression is in there somewhere.

**Comment by IonicaBizau** [comment]
Please do something in optimizing the things. When zipping a big git repository, it is very slow, consuming the resources:

![image](https://cloud.githubusercontent.com/assets/2864371/5737291/d37b91e2-9be7-11e4-8290-e64866fc973d.png)

And I'm on a SSD... :disappointed:

**Comment by ctalkington** [comment]
@IonicaBizau how many files did that entail? what was resulting zip size? and how long did it take?

**Comment by IonicaBizau** [comment]
The zipped directory has 70MB, and using `zip -r foo.zip mydir`, `mydir` was archived quickly:

```sh
real	0m10.109s
user	0m6.050s
sys	0m3.064s
```

For the same directory, the archiving process started on `Fri Jan 16 2015 16:04:15 GMT+0200 (EET)`, and haven't finished yet (after 50 minutes).

Also, the processor jumps to `100%`.

![screenshot from 2015-01-16 16 05 03](https://cloud.githubusercontent.com/assets/2864371/5778023/92599d5c-9da0-11e4-9ab1-e8585b8838b8.png)

The `node` process was consuming  `1.4 GB`, but now it is consuming `2 GB`...

![screenshot from 2015-01-16 16 12 23](https://cloud.githubusercontent.com/assets/2864371/5778025/925d5244-9da0-11e4-8e38-f1997576fe56.png)

**Comment by silverwind** [comment]
So I finally came around to compare archiver, yazl and native zip. First a moderately small project, then on a full linux source tree:

Moderate project, 4549 files:
---
zip: 6.0s
yazl: 7.9s
archiver: 10.1s

Linux tree, 48410 files:

zip: 64s
yazl: 115s
archiver: 45min and still going

I tried various sized trees, and I think after a certain amount of files, archiver doesn't finish the job. Right now the last write to the archive happened 3 minutes ago, CPU sitting at 100%.

@ctalkington Test with the contents of https://github.com/torvalds/linux/archive/master.zip
@IonicaBizau Please do tell how many files you're zipping, the size is pretty irrelevant to this issue it seems.

**Comment by ctalkington** [comment]
@silverwind thanks, id also be curious to know if its better or worse when `store: true` is used (ie removing nodes zlib from mix)

also, was this using bulk? does yazl stat files?

**Comment by ctalkington** [comment]
also, if i had to guess on the moderate tree the 3s difference comes from archiver auto sorting out what the input is.

the linux tree though, that seems like its stuck somewhere in the queue.

@silverwind do you have the script you used to compare? so that I can fiddle

**Comment by silverwind** [comment]
Here you go: https://gist.github.com/silverwind/ac8ec0c33753057cafe7

`npm install yazl archiver graceful-fs`

**Comment by IonicaBizau** [comment]
@silverwind *Please do tell how many files you're zipping* -- I forgot to include that, I know it makes the difference. The directory I am zipping is a git repository, containing **219623 files**.

```sh
$ find . -type f | wc -l
219623
```

**Comment by ctalkington** [comment]
thats way more than i ever thought this library would be used for. guessing the bottleneck is the queuing but ill have to dig into it to try and figure out what changes when you get into big volumes of files.

**Comment by ctalkington** [comment]
been testing some things, it would appear that finalize does get ran, things just never close.

**Comment by ctalkington** [comment]
@silverwind can you confirm if running your tests back to back change the results? im noticing on windows that it seems like drive buffer or something is speeding it up ~5000 test to 14s but some times its jumps to a minute.

**Comment by silverwind** [comment]
@ctalkington I get pretty consistent results on OS X:

yazl took 8516 ms
archiver took 10437 ms

yazl took 8530 ms
archiver took 10592 ms

yazl took 8717 ms
archiver took 10482 ms

yazl took 8819 ms
archiver took 10442 ms

yazl took 8549 ms
archiver took 10563 ms

Probably Windows prefetch or something.

**Comment by IonicaBizau** [comment]
I use this module in the [`github-contributions`](https://github.com/IonicaBizau/github-contributions) project. If you like to test, checkout the `1.0.0` branch before.

**Comment by IonicaBizau** [comment]
@ctalkington Supposing I want to fix this issue, where should I start? Where the things are getting fishy?

**Comment by ctalkington** [comment]
@IonicaBizau ive been looking at it. it seems related to the streaming getting backed up. i have noticed  the new directory function to be a bit more reliable.

maybe if you wanted to test that on your samples.

**Comment by IonicaBizau** [comment]
Is the fix pushed in the repository, or how can I test?

**Comment by ctalkington** [comment]
0.14.0 has the new directory helper, albeit in the most basic of form.

if you want to throw your massive payload at it, then itd be good to know if it gets through it or hangs like before.

**Comment by IonicaBizau** [comment]
Wow, testing it! Thanks!

**Comment by ctalkington** [comment]
also, lets move this to #114 as its a little different of an issue.

**Comment by ctalkington** [comment]
closing it out as its been a mix of issues. feel free to compare your results with the latest release and open a new issue if you still see such a slow down.
