### ISSUE TITLE
Zip binary data

### ISSUE THREAD

**Issue by rgallagher27** [archiverjs/node-archiver#96]
Is it possible to zip up binary excel data created using this module: [excel-export](https://www.npmjs.org/package/excel-export)

I've tried to replicate a few examples but the unzipped excel files are corrupt and can't be opened

**Comment by josephchan91** [comment]
Hi,

Thanks for this super helpful library!

I have an API that accepts transaction data and generates two files: 1 excel file and 1 pdf file. Using node-archiver, I'd like to zip these together into a folder for the client to download. However, when I download and open the zip file, I see that the pdf file is 0kb (can't open), while the excel file works fine. Any tips?

Thanks!
Joseph
